/*
 * Cmnintr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): oak-m107-cmnintr.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CMNINTR_H
#define AKARI_CMNINTR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/*  *
 * HELD (nothing compiled): these are compiler/BSP intrinsic-control
 * macros (`_INTRINSIC_IS_HELPER(arg)` etc.).  The pages name the
 * macros and classify them, and one prints an expansion that
 * references the compiler-internal `_INTRINSIC_ ## arg` machinery
 * (not published as a CE SDK identifier); no page publishes a usable
 * definition, so the four names are carried as records. */

/* ------------------------------------------------------------------
 * Book surface: oak-m107-cmnintr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms879755 _INTRINSIC_IS_HELPER: print `_INTRINSIC_IS_HELPER(arg)` */
/* (record-only: parameter or return type unpublished) */
/* ms879756 _INTRINSIC_IS_INLINE: print `_INTRINSIC_IS_INLINE(arg) ( ( (_INTRINSIC_ ## arg) & _INTRINSIC_INLINE ) != 0 )` -- recorded verbatim (no compiled prototype) */
/* ms879757 _INTRINSIC_IS_SAFE: print `_INTRINSIC_IS_SAFE(arg)` */
/* (record-only: parameter or return type unpublished) */
/* ms879758 _INTRINSIC_IS_SUPPORTED: print `_INTRINSIC_IS_SUPPORTED(arg)` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CMNINTR_H */
