/*
 * Giisr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): oak-m107-giisr.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_GIISR_H
#define AKARI_GIISR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: oak-m107-giisr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms906087 GIISR_INFO (page print, compiled) */
typedef struct _GIISR_INFO {
    DWORD SysIntr;
    BOOL CheckPort;
    BOOL PortIsIO;
    BOOL UseMaskReg;
    DWORD PortAddr;
    DWORD PortSize;
    DWORD Mask;
    DWORD MaskAddr;
} GIISR_INFO, *PGIISR_INFO;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_GIISR_H */
