/*
 * Nled.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-nled.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_NLED_H
#define AKARI_NLED_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms905297 NLED_COUNT_INFO: prototype printed by the page; derived at the M99 sweep. */
typedef struct NLED_COUNT_INFO {
    UINT cLeds;
} NLED_COUNT_INFO;

/* ms905326 NLED_SETTINGS_INFO: prototype printed by the page; derived at the M99 sweep. */
typedef struct NLED_SETTINGS_INFO {
    UINT LedNum;
    INT OffOnBlink;
    LONG TotalCycleTime;
    LONG OnTime;
    LONG OffTime;
    INT MetaCycleOn;
    INT MetaCycleOff;
} NLED_SETTINGS_INFO;

/* ms905332 NLED_SUPPORTS_INFO: prototype printed by the page; derived at the M99 sweep. */
typedef struct NLED_SUPPORTS_INFO {
    UINT LedNum;
    LONG lCycleAdjust;
    BOOL fAdjustTotalCycleTime;
    BOOL fAdjustOnTime;
    BOOL fAdjustOffTime;
    BOOL fMetaCycleOn;
    BOOL fMetaCycleOff;
} NLED_SUPPORTS_INFO;

#ifdef __cplusplus
}
#endif

/* --- The two exported functions of the notification-LED API. ------
 *
 * M134: these were declared in Pwinuser.h, which is the header the CE 4.x
 * pages name (ms905318, ms905321).  The Windows Embedded CE 6.0 pages for
 * the same two functions (ee482640, ee484693) print "Header: nled.h" --
 * this file -- so a program following the CE 6.0 pages could not reach
 * them.  Both generations print "Link Library: coredll.dll" and CE 1.0 and
 * later; Pwinuser.h now includes this header, so both spellings work. */

/* ms905318 NLedGetDeviceInfo: print
 * `BOOL WINAPI NLedGetDeviceInfo(UINT nInfoId,void* pOutput);`
 * (CE 6.0 page ee482640; Link Library: coredll.dll) */
AKARI_CE_IMPORT BOOL WINAPI NLedGetDeviceInfo(UINT nInfoId, void *pOutput)
    AKARI_CE_NAME(NLedGetDeviceInfo);

/* ms905321 NLedSetDevice: print
 * `BOOL WINAPI NLedSetDevice(UINT nDeviceId,void* pInput);`
 * (CE 6.0 page ee484693; Link Library: coredll.dll) */
AKARI_CE_IMPORT BOOL WINAPI NLedSetDevice(UINT nDeviceId, void *pInput)
    AKARI_CE_NAME(NLedSetDevice);

#endif /* AKARI_NLED_H */
