/*
 * Ntcompat.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): oak-m107-ntcompat.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_NTCOMPAT_H
#define AKARI_NTCOMPAT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/*  *
 * HELD (nothing compiled): the pages print real prototypes, but the
 * list types they are built from -- LIST_ENTRY / PLIST_ENTRY /
 * SINGLE_LIST_ENTRY / PSINGLE_LIST_ENTRY -- have no defining page
 * anywhere in the harvested official corpus (48,849-page scan
 * negative; oak/Ndis.h and Nuiouser.h record the same finding).  The
 * printed signatures are carried verbatim; no layout is invented. */

/* ------------------------------------------------------------------
 * Book surface: oak-m107-ntcompat (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* wceddkInitializeListHead InitializeListHead (Windows CE 3.0 Device Driver Developement): print `VOID InitializeListHead( IN PLIST_ENTRY ListHead );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkInsertHeadList InsertHeadList (Windows CE 3.0 Device Driver Developement): print `VOID InsertHeadList( IN PLIST_ENTRY ListHead , IN PLIST_ENTRY Entry );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkInsertTailList InsertTailList (Windows CE 3.0 Device Driver Developement): print `VOID InsertTailList( IN PLIST_ENTRY ListHead , IN PLIST_ENTRY Entry );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkIsListEmpty IsListEmpty (Windows CE 3.0 Device Driver Developement): print `BOOLEAN IsListEmpty( IN PLIST_ENTRY ListHead );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkPopEntryList PopEntryList (Windows CE 3.0 Device Driver Developement): print `PSINGLE_LIST_ENTRY PopEntryList( IN PSINGLE_LIST_ENTRY ListHead );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkPushEntryList PushEntryList (Windows CE 3.0 Device Driver Developement): print `VOID PushEntryList( IN PSINGLE_LIST_ENTRY ListHead , IN PSINGLE_LIST_ENTRY Entry );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkRemoveEntryList RemoveEntryList (Windows CE 3.0 Device Driver Developement): print `VOID RemoveEntryList( IN PLIST_ENTRY Entry );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkRemoveHeadList RemoveHeadList (Windows CE 3.0 Device Driver Developement): print `PLIST_ENTRY RemoveHeadList( IN PLIST_ENTRY ListHead );` */
/* (record-only: parameter or return type unpublished) */
/* wceddkRemoveTailList RemoveTailList (Windows CE 3.0 Device Driver Developement): print `PLIST_ENTRY RemoveTailList( IN PLIST_ENTRY ListHead );` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_NTCOMPAT_H */
