/*
 * Ohcdddsi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): oak-m107-ohcdddsi.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_OHCDDDSI_H
#define AKARI_OHCDDDSI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: oak-m107-ohcdddsi (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* wceddkOhcdMdd_CreateMemoryObject OhcdMdd_CreateMemoryObject (Windows CE 3.0 Device Driver Developement): print `LPVOID OhcdMdd_CreateMemoryObject( DWORD cbSize , DWORD cbHighPrioritySize , PUCHAR pVirtAddr , PUCHAR pPhysAddr );` */
LPVOID OhcdMdd_CreateMemoryObject(DWORD cbSize, DWORD cbHighPrioritySize, PUCHAR pVirtAddr, PUCHAR pPhysAddr);
/* wceddkOhcdMdd_CreateOhcdObject OhcdMdd_CreateOhcdObject (Windows CE 3.0 Device Driver Developement): print `LPVOID OhcdMdd_CreateOhcdObject( LPVOID lpvOhcdPddObject , LPVOID lpvMemoryObject , LPCWSTR szRegKey , PUCHAR ioPortBase , DWORD dwSysIntr );` */
LPVOID OhcdMdd_CreateOhcdObject(LPVOID lpvOhcdPddObject, LPVOID lpvMemoryObject, LPCWSTR szRegKey, PUCHAR ioPortBase, DWORD dwSysIntr);
/* wceddkOhcdMdd_DestroyMemoryObject OhcdMdd_DestroyMemoryObject (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdMdd_DestroyMemoryObject( LPVOID lpvMemoryObject );` */
BOOL OhcdMdd_DestroyMemoryObject(LPVOID lpvMemoryObject);
/* wceddkOhcdMdd_DestroyOhcdObject OhcdMdd_DestroyOhcdObject (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdMdd_DestroyOhcdObject( LPVOID lpvOhcdObject );` */
BOOL OhcdMdd_DestroyOhcdObject(LPVOID lpvOhcdObject);
/* wceddkOhcdMdd_PowerDown OhcdMdd_PowerDown (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdMdd_PowerDown( LPVOID lpvOhcdObject );` */
BOOL OhcdMdd_PowerDown(LPVOID lpvOhcdObject);
/* wceddkOhcdMdd_PowerUp OhcdMdd_PowerUp (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdMdd_PowerUp( LPVOID lpvOhcdObject );` */
BOOL OhcdMdd_PowerUp(LPVOID lpvOhcdObject);
/* wceddkOhcdPdd_CheckConfigPower OhcdPdd_CheckConfigPower (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdPdd_CheckConfigPower( UCHAR bPort , DWORD dwConfigPower , DWORD dwTotalPower );` */
BOOL OhcdPdd_CheckConfigPower(UCHAR bPort, DWORD dwConfigPower, DWORD dwTotalPower);
/* wceddkOhcdPdd_Close OhcdPdd_Close (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdPdd_Close( DWORD dwOpenContext );` */
BOOL OhcdPdd_Close(DWORD dwOpenContext);
/* wceddkOhcdPdd_Deinit OhcdPdd_Deinit (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdPdd_Deinit( DWORD dwDeviceContext );` */
BOOL OhcdPdd_Deinit(DWORD dwDeviceContext);
/* wceddkOhcdPdd_DllMain OhcdPdd_DllMain (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdPdd_DllMain( HANDLE hinstDLL , DWORD dwReason , LPVOID lpvReserved );` */
BOOL OhcdPdd_DllMain(HANDLE hinstDLL, DWORD dwReason, LPVOID lpvReserved);
/* wceddkOhcdPdd_Init OhcdPdd_Init (Windows CE 3.0 Device Driver Developement): print `DWORD OhcdPdd_Init( DWORD dwContext );` */
DWORD OhcdPdd_Init(DWORD dwContext);
/* wceddkOhcdPdd_IOControl OhcdPdd_IOControl (Windows CE 3.0 Device Driver Developement): print `BOOL OhcdPdd_IOControl( DWORD dwOpenContext );` */
BOOL OhcdPdd_IOControl(DWORD dwOpenContext);
/* wceddkOhcdPdd_Open OhcdPdd_Open (Windows CE 3.0 Device Driver Developement): print `DWORD OhcdPdd_Open( DWORD dwDeviceContext , DWORD dwAccessCode , DWORD dwShareMode );` */
DWORD OhcdPdd_Open(DWORD dwDeviceContext, DWORD dwAccessCode, DWORD dwShareMode);
/* wceddkOhcdPdd_PowerDown OhcdPdd_PowerDown (Windows CE 3.0 Device Driver Developement): print `void OhcdPdd_PowerDown( DWORD dwDeviceContext );` */
void OhcdPdd_PowerDown(DWORD dwDeviceContext);
/* wceddkOhcdPdd_PowerUp OhcdPdd_PowerUp (Windows CE 3.0 Device Driver Developement): print `void OhcdPdd_PowerUp( DWORD dwDeviceContext );` */
void OhcdPdd_PowerUp(DWORD dwDeviceContext);
/* wceddkOhcdPdd_Read OhcdPdd_Read (Windows CE 3.0 Device Driver Developement): print `DWORD OhcdPdd_Read( DWORD dwOpenContext );` */
DWORD OhcdPdd_Read(DWORD dwOpenContext);
/* wceddkOhcdPdd_Write OhcdPdd_Write (Windows CE 3.0 Device Driver Developement): print `DWORD OhcdPdd_Write( DWORD dwOpenContext );` */
DWORD OhcdPdd_Write(DWORD dwOpenContext);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_OHCDDDSI_H */
