/*
 * Romldr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): oak-m107-romldr.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_ROMLDR_H
#define AKARI_ROMLDR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/*  *
 * HELD (nothing compiled): the page prints
 * `typedef struct ROMChain_t{ struct ROMChain_t* pNext; ROMHDR* pTOC; }
 * ROMChain_t, OEMRomChain;` but ROMHDR has no defining page in the
 * harvested official corpus, so the member type cannot be resolved
 * without inventing it. */

/* ------------------------------------------------------------------
 * Book surface: oak-m107-romldr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms903513 OEMRomChain -- HELD (page print; member types unpublished):
 *   typedef struct ROMChain_t { ... } ROMChain_t, OEMRomChain; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_ROMLDR_H */
