/*
 * Addauto.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-addauto.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_ADDAUTO_H
#define AKARI_ADDAUTO_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-addauto (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms938472 IDSAddIn::OnConnection (Header: Addauto.h.): print `HRESULT OnConnection(IApplication* pApp, VARIANT BOOL bFirstTime, Long dwCookie VARIANT_BOOL* OnConnection);` */
/* ms938476 IDSAddIn::OnDisconnection (Header: Addauto.h.): print `HRESULT OnDisconnection(VARIANT_BOOL bLastTime);` */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_ADDAUTO_H */
