/*
 * Appdefs.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-appdefs.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_APPDEFS_H
#define AKARI_APPDEFS_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-appdefs (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms926091 IApplication::AddCommand (Header: Appdefs.h.): print `HRESULT AddCommand(BSTR szCmdName, BSTR szMethodName, long nBitmapOffset, long dwCookie VARIANT_BOOL FAR* pbResult);` */
/* ms926094 IApplication::AddCommandBarButton (Header: Appdefs.h.): print `HRESULT AddCommandBarButton(long nButtonType, BSTR szCmdName, long dwCookie);` */
/* ms926100 IApplication::EnableModeless (Header: Appdefs.h.): print `HRESULT EnableModeless(VARIANT_BOOL bEnable);` */
/* ms926113 IApplication::SetAddInInfo (Header: Appdefs.h.): print `HRESULT SetAddInInfo(long nInstanceHandle, IDispatch* pCmdDispatch, long nIDBitmapResourceMedium, long nIDBitmapResourceLarge, long dwCookie);` */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_APPDEFS_H */
