/*
 * Autoras.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-autoras.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_AUTORAS_H
#define AKARI_AUTORAS_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-autoras (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms897083 DIALER_NOTIFICATION (page print, compiled) */
typedef struct  {
    DWORD dwNotificationId;
    DWORD dwNotificationParam;
} DIALER_NOTIFICATION, PDIALER_NOTIFICATION;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_AUTORAS_H */
