/*
 * Battery.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-battery.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_BATTERY_H
#define AKARI_BATTERY_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896133 BATTERYLIFETIMEINFO (page print, compiled) */
typedef struct _BatteryLifetimeInfo_tag {
    SYSTEMTIME stLastChange;
    DWORD cmsCpuUsage;
    DWORD cmsPreviousCpuUsage;
} BATTERYLIFETIMEINFO, *PBATTERYLIFETIMEINFO;
/* ms896130 BatteryDrvrGetLevels: print `LONG BatteryDrvrGetLevels(void);` */
AKARI_CE_IMPORT LONG BatteryDrvrGetLevels(void)
    AKARI_CE_NAME(BatteryDrvrGetLevels);
/* ms896131 BatteryDrvrSupportsChangeNotification: print `BOOL BatteryDrvrSupportsChangeNotification(void);` */
AKARI_CE_IMPORT BOOL BatteryDrvrSupportsChangeNotification(void)
    AKARI_CE_NAME(BatteryDrvrSupportsChangeNotification);

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890742 Battery Driver Development Concepts */
/* ms890724 Battery Driver Global Variables */
/* ms890735 Battery Driver Registry Settings */
/* ms890749 Battery Driver Samples */
/* ms895500 Moving a Battery Driver from GWES to Device Manager */

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890742 Battery Driver Development Concepts */
/* ms890724 Battery Driver Global Variables */
/* ms890735 Battery Driver Registry Settings */
/* ms890749 Battery Driver Samples */
/* ms895500 Moving a Battery Driver from GWES to Device Manager */

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms901368 IOCTL_BATTERY_GETLEVELS: documented name-only (no value published; held) */
/* ms901369 IOCTL_BATTERY_GETLIFETIMEINFO: documented name-only (no value published; held) */
/* ms901370 IOCTL_BATTERY_GETSYSTEMPOWERSTATUSEX: documented name-only (no value published; held) */
/* ms901371 IOCTL_BATTERY_GETSYSTEMPOWERSTATUSEX2: documented name-only (no value published; held) */
/* ms901372 IOCTL_BATTERY_NOTIFYOFTIMECHANGE: documented name-only (no value published; held) */
/* ms901373 IOCTL_BATTERY_SUPPORTSCHANGENOTIFICATION: documented name-only (no value published; held) */

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890742 Battery Driver Development Concepts */
/* ms890724 Battery Driver Global Variables */
/* ms890735 Battery Driver Registry Settings */
/* ms890749 Battery Driver Samples */
/* ms895500 Moving a Battery Driver from GWES to Device Manager */

#ifdef __cplusplus
}
#endif


/* --- type definitions from official page prints
 * (tools/decl-types.py). ----------------------------- */

/* wceddkBATTERY_STATUS: page-printed definition (Windows CE OS). */
typedef struct _BATTERY_STATUS {
    BYTE ACLineStatus;
    BYTE BatteryFlag;
    BYTE BatteryLifePercent;
    BYTE Reserved1;
    DWORD BatteryLifeTime;
    DWORD BatteryFullLifeTime;
    BYTE Reserved2;
    BYTE BackupBatteryFlag;
    BYTE BackupBatteryLifePercent;
    BYTE fBatteriesChangedSinceLastCall;
    DWORD BackupBatteryLifeTime;
    DWORD BackupBatteryFullLifeTime;
} BATTERY_STATUS;


/* --- M104 declarations: printed prototypes recovered
 * from the official pages (tools/decl-d1.py). -------- */

/* _wcepb_BatteryDrvrGetStatus: page-printed prototype (Windows CE OS). */
BOOL BatteryDrvrGetStatus(PSYSTEM_POWER_STATUS_EX2 pstatus, PBOOL pfBatteriesChangedSinceLastCall);

#endif /* AKARI_BATTERY_H */
