/*
 * Buttonview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_BUTTONVIEW_HPP
#define AKARI_BUTTONVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

/* ms905076 ButtonControlRectangleStyle_t (page print, compiled):
 *   enum ButtonControlRectangleStyle_t { CBR_CLIENTRECT, CBR_CHECKBOX, CBR_CHECKTEXT, CBR_GROUPTEXT, CBR_GROUPFRAME, CBR_PUSHBUTTON }; */
enum ButtonControlRectangleStyle_t {
    CBR_CLIENTRECT,
    CBR_CHECKBOX,
    CBR_CHECKTEXT,
    CBR_GROUPTEXT,
    CBR_GROUPFRAME,
    CBR_PUSHBUTTON
};

class ButtonView_t {
public:
    /* ms905094 ButtonView_t::DrawCheckBoxandRadioStyle: print `static void DrawCheckBoxandRadioStyle(HWND hwnd, HDC hdc, HBRUSH hbr, WORD alignment);` */
    static void DrawCheckBoxandRadioStyle(HWND hwnd, HDC hdc, HBRUSH hbr, WORD alignment);
    /* ms905098 ButtonView_t::DrawGroupBoxText: print `static void DrawGroupBoxText(HWND hwnd, HBRUSH hbr, HDC hdc, WORD alignment);` */
    static void DrawGroupBoxText(HWND hwnd, HBRUSH hbr, HDC hdc, WORD alignment);
    /* ms905103 ButtonView_t::DrawPushable: print `static void DrawPushable(HDC hdc, HBRUSH hbr, RECT* lprc, UINT state, UINT flags);` */
    static void DrawPushable(HDC hdc, HBRUSH hbr, RECT* lprc, UINT state, UINT flags);
    /* ms905107 ButtonView_t::DrawPushStyle: print `static void DrawPushStyle(HWND hwnd, HDC hdc, HBRUSH hbr, UINT pbfPush, UINT state);` */
    static void DrawPushStyle(HWND hwnd, HDC hdc, HBRUSH hbr, UINT pbfPush, UINT state);
    /* ms905115 ButtonView_t::DrawText: print `static void DrawText(HWND hwnd, HDC hdc, BOOL dbt, BOOL fDepress, UINT pbfPush, enum ButtonControlRectangleStyle_t bcrs, WORD alignment);`
     *   -- HELD: parameter type `enum ButtonControlRectangleStyle_t bcrs` has no defining
     *   page in the harvested official corpus */
    /* ms905211 ButtonView_t::HitDetect: print `static bool HitDetect(HWND hwnd, POINT pt);` */
    static bool HitDetect(HWND hwnd, POINT pt);
    /* ms905216 ButtonView_t::InitDC: print `static HBRUSH InitDC(HWND hwnd, HDC hdc);` */
    static HBRUSH InitDC(HWND hwnd, HDC hdc);
    /* ms905220 ButtonView_t::PaintGroupBox: print `static void PaintGroupBox(HWND hwnd, HDC hdc, HBRUSH hbr, WORD alignment);` */
    static void PaintGroupBox(HWND hwnd, HDC hdc, HBRUSH hbr, WORD alignment);
    /* ms905231 ButtonView_t::PaintNonPushStyle: print `static void PaintNonPushStyle(HWND hwnd, HDC hdc, HBRUSH hbr);` */
    static void PaintNonPushStyle(HWND hwnd, HDC hdc, HBRUSH hbr);
};

#endif /* __cplusplus */

#endif /* AKARI_BUTTONVIEW_HPP */
