/*
 * Ce_setup.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CE_SETUP_H
#define AKARI_CE_SETUP_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa514312 Install_Exit: print `codeINSTALL_EXIT Install_Exit(HWNDhwndParent,LPCTSTRpszInstallDir,WORDcFailedDirs,WORDcFailedFiles,WORDcFailedRegKeys,WORDcFailedRegVals,WORDcFailedShortcuts);` */
/* (record-only: parameter or return type unpublished) */
/* ms864467 Uninstall_Exit: print `codeUNINSTALL_EXIT Uninstall_Exit(HWNDhwndParent);` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* (Install_Init/Install_Exit/Uninstall_Init/Uninstall_Exit:
 * prototypes declared after the enum prints below.) */

#ifdef __cplusplus
}
#endif


/* ee483720 codeINSTALL_INIT: page print
 * typedef enum { codeINSTALL_INIT_CONTINUE = 0, codeINSTALL_INIT_CANCEL } codeINSTALL_INIT;
 * (generation not stated) */
typedef enum {
    codeINSTALL_INIT_CONTINUE = 0,
    codeINSTALL_INIT_CANCEL
} codeINSTALL_INIT;

/* ee484783 codeINSTALL_EXIT: page print
 * typedef enum { codeINSTALL_EXIT_DONE = 0, codeINSTALL_EXIT_UNINSTALL } codeINSTALL_EXIT;
 * (generation not stated) */
typedef enum {
    codeINSTALL_EXIT_DONE = 0,
    codeINSTALL_EXIT_UNINSTALL
} codeINSTALL_EXIT;

/* ee485190 codeUNINSTALL_INIT: page print
 * typedef enum { codeUNINSTALL_INIT_CONTINUE = 0, codeUNINSTALL_INIT_CANCEL } codeUNINSTALL_INIT;
 * (generation not stated) */
typedef enum {
    codeUNINSTALL_INIT_CONTINUE = 0,
    codeUNINSTALL_INIT_CANCEL
} codeUNINSTALL_INIT;

/* ee486781 codeUNINSTALL_EXIT: page print
 * typedef enum { codeUNINSTALL_EXIT_DONE = 0 } codeUNINSTALL_EXIT;
 * (generation not stated) */
typedef enum {
    codeUNINSTALL_EXIT_DONE = 0
} codeUNINSTALL_EXIT;


/* ------------------------------------------------------------------
 * Setup/uninstall entry points.  All four pages print "Link Library:
 * Developer-provided" -- the application's setup program implements
 * and exports them, so these are plain prototypes (not
 * AKARI_CE_IMPORT) for type-checking.  Glued print artifacts split.
 * ------------------------------------------------------------------ */

/* aa514314 Install_Init: print `codeINSTALL_INITInstall_Init(HWND
 * hwndParent,BOOLfFirstCall,BOOLfPreviouslyInstalled,LPCTSTR
 * pszInstallDir);` (Windows CE 2.0 and later; Developer-provided) */
codeINSTALL_INIT Install_Init(HWND hwndParent, BOOL fFirstCall, BOOL fPreviouslyInstalled, LPCTSTR pszInstallDir);

/* aa514312 Install_Exit: print `codeINSTALL_EXIT Install_Exit(HWND
 * hwndParent,LPCTSTRpszInstallDir,WORDcFailedDirs,WORDcFailedFiles,
 * WORDcFailedRegKeys,WORDcFailedRegVals,WORDcFailedShortcuts);`
 * (Windows CE 2.0 and later; Developer-provided) */
codeINSTALL_EXIT Install_Exit(HWND hwndParent, LPCTSTR pszInstallDir, WORD cFailedDirs, WORD cFailedFiles, WORD cFailedRegKeys, WORD cFailedRegVals, WORD cFailedShortcuts);

/* ms864576 Uninstall_Init: print `codeUNINSTALL_INITUninstall_Init(
 * HWNDhwndParent,LPCTSTRpszInstallDir);` (Windows CE 2.0 and later;
 * Developer-provided) */
codeUNINSTALL_INIT Uninstall_Init(HWND hwndParent, LPCTSTR pszInstallDir);

/* ms864467 Uninstall_Exit: print `codeUNINSTALL_EXIT Uninstall_Exit(
 * HWNDhwndParent);` (Windows CE 2.0 and later; Developer-provided) */
codeUNINSTALL_EXIT Uninstall_Exit(HWND hwndParent);

#endif /* AKARI_CE_SETUP_H */
