/* WinCE development API surface.
 * Original declarations written from a survey of CE 4.2, 5.0, and 6.0
 * public interface facts (names, types, layouts, constants, exports).
 * Not an OS, BSP, OAK, or Platform Builder component, and not a copy
 * of upstream source.
 */

#ifndef WCE_CELOG_H
#define WCE_CELOG_H
#include "windef.h"
#include "winnt.h"
#include "wceunk.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tagCEL_CRITSEC_INIT { HANDLE hCS; } CEL_CRITSEC_INIT, *PCEL_CRITSEC_INIT, *LPCEL_CRITSEC_INIT;
typedef struct tagCEL_CRITSEC_DELETE { HANDLE hCS; } CEL_CRITSEC_DELETE, *PCEL_CRITSEC_DELETE, *LPCEL_CRITSEC_DELETE;
typedef struct tagCEL_CRITSEC_ENTER { HANDLE hCS; HANDLE hOwnerThread; } CEL_CRITSEC_ENTER, *PCEL_CRITSEC_ENTER, *LPCEL_CRITSEC_ENTER;
typedef struct tagCEL_CRITSEC_LEAVE { HANDLE hCS; HANDLE hOwnerThread; } CEL_CRITSEC_LEAVE, *PCEL_CRITSEC_LEAVE, *LPCEL_CRITSEC_LEAVE;
typedef struct tagCEL_EVENT_SET { HANDLE hEvent; } CEL_EVENT_SET, *PCEL_EVENT_SET, *LPCEL_EVENT_SET;
typedef struct tagCEL_EVENT_RESET { HANDLE hEvent; } CEL_EVENT_RESET, *PCEL_EVENT_RESET, *LPCEL_EVENT_RESET;
typedef struct tagCEL_EVENT_PULSE { HANDLE hEvent; } CEL_EVENT_PULSE, *PCEL_EVENT_PULSE, *LPCEL_EVENT_PULSE;
typedef struct tagCEL_EVENT_DELETE { HANDLE hEvent; } CEL_EVENT_DELETE, *PCEL_EVENT_DELETE, *LPCEL_EVENT_DELETE;
typedef struct tagCEL_SLEEP { DWORD dwTimeout; } CEL_SLEEP, *PCEL_SLEEP, *LPCEL_SLEEP;
typedef struct tagCEL_SEM_CREATE { HANDLE hSem; DWORD dwInitCount; DWORD dwMaxCount; WCHAR szName[0]; } CEL_SEM_CREATE, *PCEL_SEM_CREATE, *LPCEL_SEM_CREATE;
typedef struct tagCEL_SEM_RELEASE { HANDLE hSem; DWORD dwReleaseCount; DWORD dwPreviousCount; } CEL_SEM_RELEASE, *PCEL_SEM_RELEASE, *LPCEL_SEM_RELEASE;
typedef struct tagCEL_SEM_DELETE { HANDLE hSem; } CEL_SEM_DELETE, *PCEL_SEM_DELETE, *LPCEL_SEM_DELETE;
typedef struct tagCEL_HEAP_CREATE { DWORD dwOptions; DWORD dwInitSize; DWORD dwMaxSize; HANDLE hHeap; DWORD dwTID; DWORD dwPID; } CEL_HEAP_CREATE, *PCEL_HEAP_CREATE, *LPCEL_HEAP_CREATE;
typedef struct tagCEL_HEAP_ALLOC { HANDLE hHeap; DWORD dwFlags; DWORD dwBytes; DWORD lpMem; DWORD dwTID; DWORD dwPID; DWORD dwCallerPID; DWORD adwStackTrace[0]; } CEL_HEAP_ALLOC, *PCEL_HEAP_ALLOC, *LPCEL_HEAP_ALLOC;
typedef struct tagCEL_HEAP_REALLOC { HANDLE hHeap; DWORD dwFlags; DWORD dwBytes; DWORD lpMemOld; DWORD lpMem; DWORD dwTID; DWORD dwPID; DWORD dwCallerPID; DWORD adwStackTrace[0]; } CEL_HEAP_REALLOC, *PCEL_HEAP_REALLOC, *LPCEL_HEAP_REALLOC;
typedef struct tagCEL_HEAP_FREE { HANDLE hHeap; DWORD dwFlags; DWORD lpMem; DWORD dwTID; DWORD dwPID; DWORD dwCallerPID; DWORD adwStackTrace[0]; } CEL_HEAP_FREE, *PCEL_HEAP_FREE, *LPCEL_HEAP_FREE;
typedef struct tagCEL_HEAP_DESTROY { HANDLE hHeap; DWORD dwTID; DWORD dwPID; } CEL_HEAP_DESTROY, *PCEL_HEAP_DESTROY, *LPCEL_HEAP_DESTROY;
typedef struct tagCEL_VIRTUAL_ALLOC_EX { HANDLE hProcess; DWORD dwResult; DWORD dwAddress; DWORD dwSize; DWORD dwType; DWORD dwProtect; } CEL_VIRTUAL_ALLOC_EX, *PCEL_VIRTUAL_ALLOC_EX, *LPCEL_VIRTUAL_ALLOC_EX;
typedef struct tagCEL_VIRTUAL_COPY_EX { HANDLE hDestProc; DWORD dwDest; HANDLE hSrcProc; DWORD dwSource; DWORD dwSize; DWORD dwProtect; } CEL_VIRTUAL_COPY_EX, *PCEL_VIRTUAL_COPY_EX, *LPCEL_VIRTUAL_COPY_EX;
typedef struct tagCEL_VIRTUAL_FREE_EX { HANDLE hProcess; DWORD dwAddress; DWORD dwSize; DWORD dwType; } CEL_VIRTUAL_FREE_EX, *PCEL_VIRTUAL_FREE_EX, *LPCEL_VIRTUAL_FREE_EX;
typedef struct tagCEL_MAPFILE_CREATE_EX { HANDLE hMap; DWORD flProtect; DWORD dwMapFlags; DWORD dwMaxSizeHigh; DWORD dwMaxSizeLow; WCHAR szName[0]; } CEL_MAPFILE_CREATE_EX, *PCEL_MAPFILE_CREATE_EX, *LPCEL_MAPFILE_CREATE_EX;
typedef struct tagCEL_MAPFILE_DESTROY { HANDLE hMap; } CEL_MAPFILE_DESTROY, *PCEL_MAPFILE_DESTROY, *LPCEL_MAPFILE_DESTROY;
typedef struct tagCEL_MAPFILE_VIEW_OPEN_EX { HANDLE hMap; HANDLE hProcess; DWORD dwDesiredAccess; DWORD dwFileOffsetHigh; DWORD dwFileOffsetLow; DWORD dwLen; LPVOID lpBaseAddress; } CEL_MAPFILE_VIEW_OPEN_EX, *PCEL_MAPFILE_VIEW_OPEN_EX, *LPCEL_MAPFILE_VIEW_OPEN_EX;
typedef struct tagCEL_MAPFILE_VIEW_CLOSE { HANDLE hProcess; LPVOID lpBaseAddress; } CEL_MAPFILE_VIEW_CLOSE, *PCEL_MAPFILE_VIEW_CLOSE, *LPCEL_MAPFILE_VIEW_CLOSE;
typedef struct tagCEL_MAPFILE_VIEW_FLUSH { HANDLE hProcess; LPVOID lpBaseAddress; DWORD dwLen; DWORD dwNumPages; WORD wFlushFlags; } CEL_MAPFILE_VIEW_FLUSH, *PCEL_MAPFILE_VIEW_FLUSH, *LPCEL_MAPFILE_VIEW_FLUSH;
typedef struct tagCEL_THREAD_RUNNABLE { HANDLE hThread; } CEL_THREAD_RUNNABLE, *PCEL_THREAD_RUNNABLE, *LPCEL_THREAD_RUNNABLE;
typedef struct tagCEL_THREAD_SWITCH { HANDLE hThread; } CEL_THREAD_SWITCH, *PCEL_THREAD_SWITCH, *LPCEL_THREAD_SWITCH;
typedef struct tagCEL_THREAD_MIGRATE { HANDLE hProcess; DWORD dwReserved; } CEL_THREAD_MIGRATE, *PCEL_THREAD_MIGRATE, *LPCEL_THREAD_MIGRATE;
typedef struct tagCEL_THREAD_CREATE { HANDLE hThread; HANDLE hProcess; HANDLE hModule; DWORD dwStartAddr; int nPriority; WCHAR szName[0]; } CEL_THREAD_CREATE, *PCEL_THREAD_CREATE, *LPCEL_THREAD_CREATE;
typedef struct tagCEL_THREAD_TERMINATE { HANDLE hThread; } CEL_THREAD_TERMINATE, *PCEL_THREAD_TERMINATE, *LPCEL_THREAD_TERMINATE;
typedef struct tagCEL_THREAD_DELETE { HANDLE hThread; } CEL_THREAD_DELETE, *PCEL_THREAD_DELETE, *LPCEL_THREAD_DELETE;
typedef struct tagCEL_PROCESS_CREATE { HANDLE hProcess; DWORD dwVMBase; WCHAR szName[0]; } CEL_PROCESS_CREATE, *PCEL_PROCESS_CREATE, *LPCEL_PROCESS_CREATE;
typedef struct tagCEL_PROCESS_TERMINATE { HANDLE hProcess; } CEL_PROCESS_TERMINATE, *PCEL_PROCESS_TERMINATE, *LPCEL_PROCESS_TERMINATE;
typedef struct tagCEL_PROCESS_DELETE { HANDLE hProcess; } CEL_PROCESS_DELETE, *PCEL_PROCESS_DELETE, *LPCEL_PROCESS_DELETE;
typedef struct tagCEL_THREAD_SUSPEND { HANDLE hThread; } CEL_THREAD_SUSPEND, *PCEL_THREAD_SUSPEND, *LPCEL_THREAD_SUSPEND;
typedef struct tagCEL_THREAD_RESUME { HANDLE hThread; } CEL_THREAD_RESUME, *PCEL_THREAD_RESUME, *LPCEL_THREAD_RESUME;
typedef struct tagCEL_EXTRA_PROCESS_INFO { HANDLE hProcess; DWORD dwCodeBase; DWORD dwVMLen; DWORD dwOID; WCHAR szFullPath[0]; } CEL_EXTRA_PROCESS_INFO, *PCEL_EXTRA_PROCESS_INFO, *LPCEL_EXTRA_PROCESS_INFO;
typedef struct tagCEL_SYSTEM_INVERT { HANDLE hThread; int nPriority; } CEL_SYSTEM_INVERT, *PCEL_SYSTEM_INVERT, *LPCEL_SYSTEM_INVERT;
typedef struct tagCEL_THREAD_PRIORITY { HANDLE hThread; int nPriority; } CEL_THREAD_PRIORITY, *PCEL_THREAD_PRIORITY, *LPCEL_THREAD_PRIORITY;
typedef struct tagCEL_THREAD_QUANTUM { HANDLE hThread; DWORD dwQuantum; } CEL_THREAD_QUANTUM, *PCEL_THREAD_QUANTUM, *LPCEL_THREAD_QUANTUM;
typedef struct tagCEL_MODULE_LOAD { HANDLE hProcess; HANDLE hModule; DWORD dwBase; WCHAR szName[0]; } CEL_MODULE_LOAD, *PCEL_MODULE_LOAD, *LPCEL_MODULE_LOAD;
typedef struct tagCEL_MODULE_FREE { HANDLE hProcess; HANDLE hModule; } CEL_MODULE_FREE, *PCEL_MODULE_FREE, *LPCEL_MODULE_FREE;
typedef struct tagCEL_EXTRA_MODULE_INFO { HANDLE hModule; DWORD dwVMLen; DWORD dwModuleFlags; DWORD dwOID; WCHAR szFullPath[0]; } CEL_EXTRA_MODULE_INFO, *PCEL_EXTRA_MODULE_INFO, *LPCEL_EXTRA_MODULE_INFO;
typedef struct tagCEL_PROCESS_REFCOUNT { HANDLE hProcess; DWORD dwRefCount; } CEL_PROCESS_REFCOUNT, *PCEL_PROCESS_REFCOUNT, *LPCEL_PROCESS_REFCOUNT;
typedef struct tagCEL_MODULE_REFERENCES { HANDLE hModule; CEL_PROCESS_REFCOUNT ref[1]; } CEL_MODULE_REFERENCES, *PCEL_MODULE_REFERENCES, *LPCEL_MODULE_REFERENCES;
typedef struct tagCEL_MUTEX_CREATE { HANDLE hMutex; WCHAR szName[0]; } CEL_MUTEX_CREATE, *PCEL_MUTEX_CREATE, *LPCEL_MUTEX_CREATE;
typedef struct tagCEL_MUTEX_RELEASE { HANDLE hMutex; } CEL_MUTEX_RELEASE, *PCEL_MUTEX_RELEASE, *LPCEL_MUTEX_RELEASE;
typedef struct tagCEL_MUTEX_DELETE { HANDLE hMutex; } CEL_MUTEX_DELETE, *PCEL_MUTEX_DELETE, *LPCEL_MUTEX_DELETE;
typedef struct tagCEL_SYSTEM_TLB { DWORD dwCount; } CEL_SYSTEM_TLB, *PCEL_SYSTEM_TLB, *LPCEL_SYSTEM_TLB;
typedef struct tagCEL_INT_DATA { DWORD dwTimeStamp; WORD wSysIntr; WORD wNestingLevel; } CEL_INT_DATA, *PCEL_INT_DATA, *LPCEL_INT_DATA;
typedef struct tagCEL_INTERRUPTS { DWORD dwDiscarded; CEL_INT_DATA IntData[0]; } CEL_INTERRUPTS, *PCEL_INTERRUPTS, *LPCEL_INTERRUPTS;
typedef struct tagCEL_MEMTRACK_BASELINE { DWORD dwReserved; } CEL_MEMTRACK_BASELINE, *PCEL_MEMTRACK_BASELINE, *LPCEL_MEMTRACK_BASELINE;
typedef struct tagCEL_RDP_INFO { BYTE bOrderType; BYTE bOrder; DWORD dwTimeSpent; } CEL_RDP_INFO, *PCEL_RDP_INFO, *LPCEL_RDP_INFO;
typedef struct tagCEL_DEBUG_MSG { DWORD pid; DWORD tid; WCHAR szMessage[0]; } CEL_DEBUG_MSG, *PCEL_DEBUG_MSG, *LPCEL_DEBUG_MSG;
typedef struct tagCEL_DATA_LOSS { DWORD dwBytes; } CEL_DATA_LOSS, *PCEL_DATA_LOSS, *LPCEL_DATA_LOSS;
typedef struct tagCEL_LOG_MARKER { DWORD dwFrequency; DWORD dwDefaultQuantum; DWORD dwVersion; } CEL_LOG_MARKER, *PCEL_LOG_MARKER, *LPCEL_LOG_MARKER;
typedef struct tagCEL_EVENT_CLOSE { HANDLE hEvent; } CEL_EVENT_CLOSE, *PCEL_EVENT_CLOSE, *LPCEL_EVENT_CLOSE;
typedef struct tagCEL_SEM_CLOSE { HANDLE hSem; } CEL_SEM_CLOSE, *PCEL_SEM_CLOSE, *LPCEL_SEM_CLOSE;
typedef struct tagCEL_THREAD_CLOSE { HANDLE hThread; } CEL_THREAD_CLOSE, *PCEL_THREAD_CLOSE, *LPCEL_THREAD_CLOSE;
typedef struct tagCEL_PROCESS_CLOSE { HANDLE hProcess; } CEL_PROCESS_CLOSE, *PCEL_PROCESS_CLOSE, *LPCEL_PROCESS_CLOSE;
typedef struct tagCEL_MUTEX_CLOSE { HANDLE hMutex; } CEL_MUTEX_CLOSE, *PCEL_MUTEX_CLOSE, *LPCEL_MUTEX_CLOSE;
typedef struct tagCEL_VIRTUAL_ALLOC { DWORD dwResult; DWORD dwAddress; DWORD dwSize; DWORD dwType; DWORD dwProtect; BYTE bReserved[0]; } CEL_VIRTUAL_ALLOC, *PCEL_VIRTUAL_ALLOC, *LPCEL_VIRTUAL_ALLOC;
typedef struct tagCEL_VIRTUAL_COPY { DWORD dwDest; DWORD dwSource; DWORD dwSize; DWORD dwProtect; } CEL_VIRTUAL_COPY, *PCEL_VIRTUAL_COPY, *LPCEL_VIRTUAL_COPY;
typedef struct tagCEL_VIRTUAL_FREE { DWORD dwAddress; DWORD dwSize; DWORD dwType; BYTE bReserved[0]; } CEL_VIRTUAL_FREE, *PCEL_VIRTUAL_FREE, *LPCEL_VIRTUAL_FREE;
typedef struct tagCEL_MAPFILE_CREATE { HANDLE hMap; DWORD flProtect; DWORD dwMapFlags; DWORD dwMaxSize; WCHAR szName[0]; } CEL_MAPFILE_CREATE, *PCEL_MAPFILE_CREATE, *LPCEL_MAPFILE_CREATE;
typedef struct tagCEL_MAPFILE_VIEW_OPEN { HANDLE hMap; HANDLE hProcess; DWORD dwDesiredAccess; DWORD dwFileOffset; DWORD dwLen; LPVOID lpBaseAddress; } CEL_MAPFILE_VIEW_OPEN, *PCEL_MAPFILE_VIEW_OPEN, *LPCEL_MAPFILE_VIEW_OPEN;
typedef struct tagCEL_MAPFILE_FLUSH { LPVOID lpBaseAddress; DWORD dwLen; WORD wFlushFlags; WORD wNumPages; } CEL_MAPFILE_FLUSH, *PCEL_MAPFILE_FLUSH, *LPCEL_MAPFILE_FLUSH;
typedef struct tagMAPHEADER { DWORD dwBufSize; LPBYTE pWrite; LPBYTE pRead; BOOL fSetEvent; BYTE bReserved; DWORD dwLostBytes; DWORD dwVersion; DWORD dwBufferStart; DWORD dwWriteOffset; DWORD dwReadOffset; } MAPHEADER, *PMAPHEADER, *LPMAPHEADER;

WCE_IMPORT void WINAPI CeLogData(BOOL fTimeStamp, WORD wID, PVOID pData, WORD wLen, DWORD dwZoneUser, DWORD dwZoneCE, WORD wFlag, BOOL fFlagged) WCE_LINK(CeLogData);
WCE_IMPORT void WINAPI CeLogSetZones(DWORD dwZoneUser, DWORD dwZoneCE, DWORD dwZoneProcess) WCE_LINK(CeLogSetZones);
WCE_IMPORT BOOL WINAPI CeLogGetZones(LPDWORD lpdwZoneUser, LPDWORD lpdwZoneCE, LPDWORD lpdwZoneProcess, LPDWORD lpdwAvailableZones) WCE_LINK(CeLogGetZones);
WCE_IMPORT BOOL WINAPI CeLogReSync() WCE_LINK(CeLogReSync);

#ifdef __cplusplus
}
#endif
#endif

