/*
 * Ceutil.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CEUTIL_H
#define AKARI_CEUTIL_H

#include <Windows.h>

/* --- Handle types no CE page typedefs. ------------------------------
 * HCESVC: 33 corpus pages mention it and none prints a typedef, but
 * aa513819 "CeSvcClose" prints `HRESULT CeSvcClose( HCESVC hSvc);`
 * (Header: Ceutil.h, Link Library: Coredll.lib, Windows CE 3.0 and
 * later), paired with the CeSvcOpen page that fills it.  See Windef.h:236
 * for the in-tree precedent for a handle no page typedefs. */
typedef HANDLE HCESVC, *PHCESVC;  /* aa513836 CeSvcOpenEx and
                                    * ee484797 CeSvcOpen both take
                                    * PHCESVC phSvc */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms861107 CeGetDeviceId: print `DEVICEID CeGetDeviceId();` */
/* (record-only: parameter or return type unpublished) */
/* aa513363 CeGetSelectedDeviceId: print `DEVICEID CeGetSelectedDeviceId();` */
/* (record-only: parameter or return type unpublished) */
/* aa513818 CeSvcAdd: print `HRESULT CeSvcAdd( LPTSTR pszSvcName,LPTSTR pszSvcClass,LPVOID pSvcInfo);` */
AKARI_CE_IMPORT HRESULT CeSvcAdd(LPTSTR pszSvcName, LPTSTR pszSvcClass, LPVOID pSvcInfo)
    AKARI_CE_NAME(CeSvcAdd);
/* aa513837 CeSvcQueryInfo: print `HRESULT CeSvcQueryInfo( LPTSTR pszSvcName,LPTSTR pszSvcClass,LPVOID pszSvcInfo,DWORD cbBuffer);` */
AKARI_CE_IMPORT HRESULT CeSvcQueryInfo(LPTSTR pszSvcName, LPTSTR pszSvcClass, LPVOID pszSvcInfo, DWORD cbBuffer)
    AKARI_CE_NAME(CeSvcQueryInfo);
/* aa513840 CeSvcRemove: print `HRESULT CeSvcRemove( LPTSTR pszSvcName,LPTSTR pszSvcClass,DWORD dwSvcFlags);` */
AKARI_CE_IMPORT HRESULT CeSvcRemove(LPTSTR pszSvcName, LPTSTR pszSvcClass, DWORD dwSvcFlags)
    AKARI_CE_NAME(CeSvcRemove);
/* ms860950 CeSvcOpen Constant Enumeration (Header: Ceutil.h.) */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms860950 CeSvcOpen Constant Enumeration (Header: Ceutil.h.) */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa514415 ObjectNotify: documented name-only (no value published; held) */
/* ms860950 CeSvcOpen Constant Enumeration (Header: Ceutil.h.) */

#ifdef __cplusplus
}
#endif


/* ee483497 CeSvcGetDword: print `HRESULT CeSvcGetDword(
HCESVC hSvc,
LPCTSTR pszValName,
LPDWORD pdwVal
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcGetDword(HCESVC hSvc, LPCTSTR pszValName, LPDWORD pdwVal) AKARI_CE_NAME(CeSvcGetDword);

/* ee483915 CeSvcGetString: print `HRESULT CeSvcGetString(
HCESVC hSvc,
LPCTSTR pszValName,
LPTSTR pszVal,
DWORD cbVal
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcGetString(HCESVC hSvc, LPCTSTR pszValName, LPTSTR pszVal, DWORD cbVal) AKARI_CE_NAME(CeSvcGetString);

/* ee484174 CeSvcSetDword: print `HRESULT CeSvcSetDword(
HCESVC hSvc,
LPCTSTR pszValName,
DWORD dwVal
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcSetDword(HCESVC hSvc, LPCTSTR pszValName, DWORD dwVal) AKARI_CE_NAME(CeSvcSetDword);

/* ee484373 CeSvcDeleteVal: print `HRESULT CeSvcDeleteVal(
HCESVC hSvc,
LPCTSTR pszValName
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcDeleteVal(HCESVC hSvc, LPCTSTR pszValName) AKARI_CE_NAME(CeSvcDeleteVal);

/* ee484759 CeSvcClose: print `HRESULT CeSvcClose(
HCESVC hSvc
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcClose(HCESVC hSvc) AKARI_CE_NAME(CeSvcClose);

/* ee484787 CeSvcDelete: print `HRESULT CeSvcDelete(
HCESVC hSvc
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcDelete(HCESVC hSvc) AKARI_CE_NAME(CeSvcDelete);

/* ee484957 CeSvcGetBinary: print `HRESULT CeSvcGetBinary(
HCESVC hSvc,
LPCTSTR pszValName,
LPBYTE pszVal,
LPDWORD pcbVal
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcGetBinary(HCESVC hSvc, LPCTSTR pszValName, LPBYTE pszVal, LPDWORD pcbVal) AKARI_CE_NAME(CeSvcGetBinary);

/* ee486216 CeSvcSetString: print `HRESULT CeSvcSetString(
HCESVC hSvc,
LPCTSTR pszValName,
LPCTSTR pszVal
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcSetString(HCESVC hSvc, LPCTSTR pszValName, LPCTSTR pszVal) AKARI_CE_NAME(CeSvcSetString);

/* ee486614 CeSvcSetBinary: print `HRESULT CeSvcSetBinary(
HCESVC hSvc,
LPCTSTR pszValName,
LPBYTE pszVal,
DWORD cbVal
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcSetBinary(HCESVC hSvc, LPCTSTR pszValName, LPBYTE pszVal, DWORD cbVal) AKARI_CE_NAME(CeSvcSetBinary);


/* ee483537 CeSvcOpenEx: print `HRESULT CeSvcOpenEx(
HCESVC hSvcRoot,
LPTSTR pszPath,
BOOL fCreate,
PHCESVC phSvc
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcOpenEx(HCESVC hSvcRoot, LPTSTR pszPath, BOOL fCreate, PHCESVC phSvc) AKARI_CE_NAME(CeSvcOpenEx);

/* ee484797 CeSvcOpen: print `HRESULT CeSvcOpen(
UINT uSvc,
LPTSTR pszPath,
BOOL fCreate,
PHCESVC phSvc
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcOpen(UINT uSvc, LPTSTR pszPath, BOOL fCreate, PHCESVC phSvc) AKARI_CE_NAME(CeSvcOpen);

/* ee486329 CeSvcEnumProfiles: print `HRESULT CeSvcEnumProfiles(
PHCESVC phSvc,
DWORD lProfileIndex,
PDWORD plProfile
);`
 * (generation not stated; Link Library: coredll.lib) */
AKARI_CE_IMPORT HRESULT CeSvcEnumProfiles(PHCESVC phSvc, DWORD lProfileIndex, PDWORD plProfile) AKARI_CE_NAME(CeSvcEnumProfiles);

#endif /* AKARI_CEUTIL_H */
