/*
 * Comboboxview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_COMBOBOXVIEW_HPP
#define AKARI_COMBOBOXVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class ComboBoxView_t {
public:
    /* ms905423 ComboBoxView_t::DrawFocus: print `static void DrawFocus(HDC hdc, RECT* prc);` */
    static void DrawFocus(HDC hdc, RECT* prc);
    /* ms905424 ComboBoxView_t::TopCoordinate: print `static int TopCoordinate(HDC hdc, RECT* lprc);` */
    static int TopCoordinate(HDC hdc, RECT* lprc);
    /* ms905425 ComboBoxView_t::WindowStyleCustomization: print `static void WindowStyleCustomization(HWND hwnd, DWORD Style, DWORD ExStyle, DWORD* pStyle, DWORD* pExStyle);` */
    static void WindowStyleCustomization(HWND hwnd, DWORD Style, DWORD ExStyle, DWORD* pStyle, DWORD* pExStyle);
};

#endif /* __cplusplus */

#endif /* AKARI_COMBOBOXVIEW_HPP */
