/*
 * Comcat.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-comcat.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_COMCAT_H
#define AKARI_COMCAT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-comcat (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms879987 ICatInformation::EnumCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887022 ICatInformation::EnumCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880012 ICatInformation::EnumClassesOfCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887023 ICatInformation::EnumClassesOfCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880020 ICatInformation::EnumImplCategoriesOfClass (Header: Comcat.h, Comcat.idl.) */
/* ms887024 ICatInformation::EnumImplCategoriesOfClass (Header: Comcat.h, Comcat.idl.) */
/* ms880024 ICatInformation::EnumReqCategoriesOfClass (Header: Comcat.h, Comcat.idl.) */
/* ms887025 ICatInformation::EnumReqCategoriesOfClass (Header: Comcat.h, Comcat.idl.) */
/* ms880029 ICatInformation::GetCategoryDesc (Header: Comcat.h, Comcat.idl.) */
/* ms887026 ICatInformation::GetCategoryDesc (Header: Comcat.h, Comcat.idl.) */
/* ms880032 ICatInformation::IsClassOfCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887027 ICatInformation::IsClassOfCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880045 ICatRegister::RegisterCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887139 ICatRegister::RegisterCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880052 ICatRegister::RegisterClassImplCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887248 ICatRegister::RegisterClassImplCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880057 ICatRegister::RegisterClassReqCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887259 ICatRegister::RegisterClassReqCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880063 ICatRegister::UnRegisterCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887265 ICatRegister::UnRegisterCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880068 ICatRegister::UnRegisterClassImplCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887266 ICatRegister::UnRegisterClassImplCategories (Header: Comcat.h, Comcat.idl.) */
/* ms880073 ICatRegister::UnRegisterClassReqCategories (Header: Comcat.h, Comcat.idl.) */
/* ms887267 ICatRegister::UnRegisterClassReqCategories (Header: Comcat.h, Comcat.idl.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_COMCAT_H */
