/*
 * Commctrlview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_COMMCTRLVIEW_HPP
#define AKARI_COMMCTRLVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class CommCtrlView_t {
public:
    /* ms905505 CommCtrlView_t::Init: print `static void Init(HANDLE hinstDLL);` */
    static void Init(HANDLE hinstDLL);
};

#endif /* __cplusplus */

#endif /* AKARI_COMMCTRLVIEW_HPP */
