/*
 * Dsound.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-dsound.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DSOUND_H
#define AKARI_DSOUND_H

#include <Windows.h>
#include "Mmsystem.h"   /* LPWAVEFORMATEX (DSBUFFERDESC / DSCBUFFERDESC members) */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-dsound (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct LPDIRECTSOUND LPDIRECTSOUND;   /* opaque carrier (layout unpublished) */
typedef struct LPDIRECTSOUNDCAPTURE LPDIRECTSOUNDCAPTURE;   /* opaque carrier (layout unpublished) */
/* ------------------------------------------------------------------
 * DirectSound structures -- page prints (Windows CE SDK reference
 * pages of the dsound.h book; the CE 5.0 twins ms897756-ms897788 print
 * the same layouts).
 * ------------------------------------------------------------------ */

/* wcesdkrDSBCAPS_dsound DSBCAPS:
 *   typedef struct { DWORD dwSize ; DWORD dwFlags ; DWORD dwBufferBytes ;
 *     DWORD dwUnlockTransferRate ; DWORD dwPlayCpuOverhead ; } DSBCAPS,
 *     *LPDSBCAPS; typedef const DSBCAPS *LPCDSBCAPS; */
typedef struct {
    DWORD dwSize;
    DWORD dwFlags;
    DWORD dwBufferBytes;
    DWORD dwUnlockTransferRate;
    DWORD dwPlayCpuOverhead;
} DSBCAPS, *LPDSBCAPS;
typedef const DSBCAPS *LPCDSBCAPS;

/* wcesdkrDSBPOSITIONNOTIFY_dsound DSBPOSITIONNOTIFY:
 *   typedef struct { DWORD dwOffset ; HANDLE hEventNotify ; }
 *     DSBPOSITIONNOTIFY, *LPDSBPOSITIONNOTIFY;
 *   typedef const DSBPOSITIONNOTIFY *LPCDSBPOSITIONNOTIFY; */
typedef struct {
    DWORD  dwOffset;
    HANDLE hEventNotify;
} DSBPOSITIONNOTIFY, *LPDSBPOSITIONNOTIFY;
typedef const DSBPOSITIONNOTIFY *LPCDSBPOSITIONNOTIFY;

/* wcesdkrDSBUFFERDESC_dsound DSBUFFERDESC:
 *   typedef struct { DWORD dwSize ; DWORD dwFlags ; DWORD dwBufferBytes ;
 *     DWORD dwReserved ; LPWAVEFORMATEX lpwfxFormat ; } DSBUFFERDESC,
 *     *LPDSBUFFERDESC; typedef const DSBUFFERDESC *LPCDSBUFFERDESC; */
typedef struct {
    DWORD           dwSize;
    DWORD           dwFlags;
    DWORD           dwBufferBytes;
    DWORD           dwReserved;
    LPWAVEFORMATEX  lpwfxFormat;
} DSBUFFERDESC, *LPDSBUFFERDESC;
typedef const DSBUFFERDESC *LPCDSBUFFERDESC;

/* wcesdkrDSCAPS_dsound DSCAPS: the page's own print reads
 * `typedef { DWORD dwSize ; ... } DSCAPS, *LPDSCAPS;` -- a print typo
 * (a typedef with no type name; every sibling page of the book prints
 * `typedef struct {...}`).  Spelled as the book's other pages: */
typedef struct {
    DWORD dwSize;
    DWORD dwFlags;
    DWORD dwMinSecondarySampleRate;
    DWORD dwMaxSecondarySampleRate;
    DWORD dwPrimaryBuffers;
    DWORD dwMaxHwMixingAllBuffers;
    DWORD dwMaxHwMixingStaticBuffers;
    DWORD dwMaxHwMixingStreamingBuffers;
    DWORD dwFreeHwMixingAllBuffers;
    DWORD dwFreeHwMixingStaticBuffers;
    DWORD dwFreeHwMixingStreamingBuffers;
    DWORD dwMaxHw3DAllBuffers;
    DWORD dwMaxHw3DStaticBuffers;
    DWORD dwMaxHw3DStreamingBuffers;
    DWORD dwFreeHw3DAllBuffers;
    DWORD dwFreeHw3DStaticBuffers;
    DWORD dwFreeHw3DStreamingBuffers;
    DWORD dwTotalHwMemBytes;
    DWORD dwFreeHwMemBytes;
    DWORD dwMaxContigFreeHwMemBytes;
    DWORD dwUnlockTransferRateHwBuffers;
    DWORD dwPlayCpuOverheadSwBuffers;
    DWORD dwReserved1;
    DWORD dwReserved2;
} DSCAPS, *LPDSCAPS;
typedef const DSCAPS *LPCDSCAPS;

/* wcesdkrDSCBCAPS_dsound DSCBCAPS:
 *   typedef struct { DWORD dwSize ; DWORD dwFlags ; DWORD dwBufferBytes ;
 *     DWORD dwReserved ; } DSCBCAPS, *LPDSCBCAPS;
 *   typedef const DSCBCAPS *LPCDSCBCAPS; */
typedef struct {
    DWORD dwSize;
    DWORD dwFlags;
    DWORD dwBufferBytes;
    DWORD dwReserved;
} DSCBCAPS, *LPDSCBCAPS;
typedef const DSCBCAPS *LPCDSCBCAPS;

/* wcesdkrDSCBUFFERDESC_dsound DSCBUFFERDESC:
 *   typedef struct { DWORD dwSize ; DWORD dwFlags ; DWORD dwBufferBytes ;
 *     DWORD dwReserved ; LPWAVEFORMATEX lpwfxFormat ; } DSCBUFFERDESC,
 *     *LPDSCBUFFERDESC; typedef const DSCBUFFERDESC *LPCDSCBUFFERDESC; */
typedef struct {
    DWORD           dwSize;
    DWORD           dwFlags;
    DWORD           dwBufferBytes;
    DWORD           dwReserved;
    LPWAVEFORMATEX  lpwfxFormat;
} DSCBUFFERDESC, *LPDSCBUFFERDESC;
typedef const DSCBUFFERDESC *LPCDSCBUFFERDESC;

/* wcesdkrDSCCAPS_dsound DSCCAPS:
 *   typedef struct { DWORD dwSize ; DWORD dwFlags ; DWORD dwFormats ;
 *     DWORD dwChannels ; } DSCCAPS, *LPDSCCAPS;
 *   typedef const DSCCAPS *LPCDSCCAPS; */
typedef struct {
    DWORD dwSize;
    DWORD dwFlags;
    DWORD dwFormats;
    DWORD dwChannels;
} DSCCAPS, *LPDSCCAPS;
typedef const DSCCAPS *LPCDSCCAPS;

/* ms897742 DirectSoundCaptureCreate: print `HRESULT WINAPI DirectSoundCaptureCreate( LPGUID lpGUID, LPDIRECTSOUNDCAPTURE* lplpDSC, LPUNKNOWN pUnkOuter );`  [twin page(s): wcesdkrDirectSoundCaptureCreate_dsound] */
AKARI_CE_IMPORT HRESULT WINAPI DirectSoundCaptureCreate(LPGUID lpGUID, LPDIRECTSOUNDCAPTURE* lplpDSC, LPUNKNOWN pUnkOuter)
    AKARI_CE_NAME(DirectSoundCaptureCreate);
/* ms897746 DirectSoundCaptureEnumerate: print `HRESULT WINAPI DirectSoundCaptureEnumerate( LPDSENUMCALLBACK lpDSEnumCallback, LPVOID lpContext );`  [twin page(s): wcesdkrDirectSoundCaptureEnumerate_dsound] */
/* (record-only: parameter or return type unpublished) */
/* ms897750 DirectSoundCreate: print `HRESULT WINAPI DirectSoundCreate( LPGUID lpGuid, LPDIRECTSOUND* ppDS, LPUNKNOWN pUnkOuter );`  [twin page(s): wcesdkrDirectSoundCreate_dsound] */
AKARI_CE_IMPORT HRESULT WINAPI DirectSoundCreate(LPGUID lpGuid, LPDIRECTSOUND* ppDS, LPUNKNOWN pUnkOuter)
    AKARI_CE_NAME(DirectSoundCreate);
/* ms897753 DirectSoundEnumerate: print `HRESULT WINAPI DirectSoundEnumerate( LPDSENUMCALLBACK lpDSEnumCallback, LPVOID lpContext );`  [twin page(s): wcesdkrDirectSoundEnumerate_dsound] */
/* (record-only: parameter or return type unpublished) */
/* ms897792 DSEnumCallback: print `BOOL CALLBACK DSEnumCallback( LPGUID lpGuid, LPCSTR lpcstrDescription, LPCSTR lpcstrModule, LPVOID lpContext );`  [twin page(s): wcesdkrDSEnumCallback_dsound] */
AKARI_CE_IMPORT BOOL CALLBACK DSEnumCallback(LPGUID lpGuid, LPCSTR lpcstrDescription, LPCSTR lpcstrModule, LPVOID lpContext)
    AKARI_CE_NAME(DSEnumCallback);
/* wcesdkrIDirectSound_dsound IDirectSound: print `typedef struct IDirectSound *LPDIRECTSOUND;` -- recorded verbatim (no compiled prototype) */
/* wcesdkrIDirectSoundBuffer_dsound IDirectSoundBuffer: print `typedef struct IDirectSoundBuffer *LPDIRECTSOUNDBUFFER;` -- recorded verbatim (no compiled prototype) */
/* wcesdkrIDirectSoundCapture_dsound IDirectSoundCapture: print `typedef struct IDirectSoundCapture *LPDIRECTSOUNDCAPTURE;` -- recorded verbatim (no compiled prototype) */
/* wcesdkrIDirectSoundCaptureBuffer_dsound IDirectSoundCaptureBuffer: print `typedef struct IDirectSoundCaptureBuffer *LPDIRECTSOUNDCAPTUREBUFFER;` -- recorded verbatim (no compiled prototype) */
/* wcesdkrIDirectSoundNotify_dsound IDirectSoundNotify: print `typedef struct IDirectSoundNotify *LPDIRECTSOUNDNOTIFY;` -- recorded verbatim (no compiled prototype) */
/* ms898025 IDirectSound::Compact (Header: Dsound.h.) */
/* wcesdkrIDirectSound_Compact_dsound IDirectSound::Compact (Header: dsound.h) */
/* ms898123 IDirectSound::CreateSoundBuffer (Header: Dsound.h.) */
/* wcesdkrIDirectSound_CreateSoundBuffer_dsound IDirectSound::CreateSoundBuffer (Header: dsound.h) */
/* ms898132 IDirectSound::DuplicateSoundBuffer (Header: Dsound.h.) */
/* wcesdkrIDirectSound_DuplicateSoundBuffer_dsound IDirectSound::DuplicateSoundBuffer (Header: dsound.h) */
/* ms898133 IDirectSound::GetCaps (Header: Dsound.h.) */
/* wcesdkrIDirectSound_GetCaps_dsound IDirectSound::GetCaps (Header: dsound.h) */
/* ms898134 IDirectSound::Initialize (Header: Dsound.h.) */
/* wcesdkrIDirectSound_Initialize_dsound IDirectSound::Initialize (Header: dsound.h) */
/* ms898135 IDirectSound::SetCooperativeLevel (Header: Dsound.h.) */
/* wcesdkrIDirectSound_SetCooperativeLevel_dsound IDirectSound::SetCooperativeLevel (Header: dsound.h) */
/* ms897798 IDirectSoundBuffer::GetCaps (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetCaps_dsound IDirectSoundBuffer::GetCaps (Header: dsound.h) */
/* ms897801 IDirectSoundBuffer::GetCurrentPosition (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetCurrentPosition_dsound IDirectSoundBuffer::GetCurrentPosition (Header: dsound.h) */
/* ms897806 IDirectSoundBuffer::GetFormat (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetFormat_dsound IDirectSoundBuffer::GetFormat (Header: dsound.h) */
/* ms897810 IDirectSoundBuffer::GetFrequency (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetFrequency_dsound IDirectSoundBuffer::GetFrequency (Header: dsound.h) */
/* ms897813 IDirectSoundBuffer::GetPan (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetPan_dsound IDirectSoundBuffer::GetPan (Header: dsound.h) */
/* ms897816 IDirectSoundBuffer::GetStatus (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetStatus_dsound IDirectSoundBuffer::GetStatus (Header: dsound.h) */
/* ms897820 IDirectSoundBuffer::GetVolume (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_GetVolume_dsound IDirectSoundBuffer::GetVolume (Header: dsound.h) */
/* ms897823 IDirectSoundBuffer::Initialize (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_Initialize_dsound IDirectSoundBuffer::Initialize (Header: dsound.h) */
/* ms897826 IDirectSoundBuffer::Lock (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_Lock_dsound IDirectSoundBuffer::Lock (Header: dsound.h) */
/* ms897830 IDirectSoundBuffer::Play (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_Play_dsound IDirectSoundBuffer::Play (Header: dsound.h) */
/* ms897833 IDirectSoundBuffer::Restore (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_Restore_dsound IDirectSoundBuffer::Restore (Header: dsound.h) */
/* ms897837 IDirectSoundBuffer::SetCurrentPosition (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_SetCurrentPosition_dsound IDirectSoundBuffer::SetCurrentPosition (Header: dsound.h) */
/* ms897842 IDirectSoundBuffer::SetFormat (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_SetFormat_dsound IDirectSoundBuffer::SetFormat (Header: dsound.h) */
/* ms897844 IDirectSoundBuffer::SetFrequency (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_SetFrequency_dsound IDirectSoundBuffer::SetFrequency (Header: dsound.h) */
/* ms897848 IDirectSoundBuffer::SetPan (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_SetPan_dsound IDirectSoundBuffer::SetPan (Header: dsound.h) */
/* ms897852 IDirectSoundBuffer::SetVolume (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_SetVolume_dsound IDirectSoundBuffer::SetVolume (Header: dsound.h) */
/* ms897856 IDirectSoundBuffer::Stop (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_Stop_dsound IDirectSoundBuffer::Stop (Header: dsound.h) */
/* ms897857 IDirectSoundBuffer::Unlock (Header: Dsound.h.) */
/* wcesdkrIDirectSoundBuffer_Unlock_dsound IDirectSoundBuffer::Unlock (Header: dsound.h) */
/* ms897895 IDirectSoundCapture::CreateCaptureBuffer (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCapture_CreateCaptureBuffer_dsound IDirectSoundCapture::CreateCaptureBuffer (Header: dsound.h) */
/* ms897930 IDirectSoundCapture::GetCaps (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCapture_GetCaps_dsound IDirectSoundCapture::GetCaps (Header: dsound.h) */
/* ms897938 IDirectSoundCapture::Initialize (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCapture_Initialize_dsound IDirectSoundCapture::Initialize (Header: dsound.h) */
/* ms897865 IDirectSoundCaptureBuffer::GetCaps (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_GetCaps_dsound IDirectSoundCaptureBuffer::GetCaps (Header: dsound.h) */
/* ms897868 IDirectSoundCaptureBuffer::GetCurrentPosition (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_GetCurrentPosition_dsound IDirectSoundCaptureBuffer::GetCurrentPosition (Header: dsound.h) */
/* ms897871 IDirectSoundCaptureBuffer::GetFormat (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_GetFormat_dsound IDirectSoundCaptureBuffer::GetFormat (Header: dsound.h) */
/* ms897873 IDirectSoundCaptureBuffer::GetStatus (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_GetStatus_dsound IDirectSoundCaptureBuffer::GetStatus (Header: dsound.h) */
/* ms897878 IDirectSoundCaptureBuffer::Initialize (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_Initialize_dsound IDirectSoundCaptureBuffer::Initialize (Header: dsound.h) */
/* ms897882 IDirectSoundCaptureBuffer::Lock (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_Lock_dsound IDirectSoundCaptureBuffer::Lock (Header: dsound.h) */
/* ms897884 IDirectSoundCaptureBuffer::Start (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_Start_dsound IDirectSoundCaptureBuffer::Start (Header: dsound.h) */
/* ms897889 IDirectSoundCaptureBuffer::Stop (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_Stop_dsound IDirectSoundCaptureBuffer::Stop (Header: dsound.h) */
/* ms897893 IDirectSoundCaptureBuffer::Unlock (Header: Dsound.h.) */
/* wcesdkrIDirectSoundCaptureBuffer_Unlock_dsound IDirectSoundCaptureBuffer::Unlock (Header: dsound.h) */
/* ms897941 IDirectSoundNotify::SetNotificationPositions (Header: Dsound.h.) */
/* wcesdkrIDirectSoundNotify_SetNotificationPositions_dsound IDirectSoundNotify::SetNotificationPositions (Header: dsound.h) */
/* ms897541 IKsPropertySet::Get (Header: Dsound.h.) */
/* ms897549 IKsPropertySet::QuerySupport (Header: Dsound.h.) */
/* ms897554 IKsPropertySet::Set (Header: Dsound.h.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DSOUND_H */
