/*
 * Gcacheview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_GCACHEVIEW_HPP
#define AKARI_GCACHEVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class CacheView_t {
public:
    /* ms905246 CacheView_t::ComputeMinWindowSize: print `static void ComputeMinWindowSize(LONG* pcxMinWinSize, LONG* pcyMinWinSize);` */
    static void ComputeMinWindowSize(LONG* pcxMinWinSize, LONG* pcyMinWinSize);
    /* ms905251 CacheView_t::GWECacheSetSysColors: print `static void GWECacheSetSysColors(int cElements, CONST INT* rgcolor, CONST COLORREF* rgrgb);` */
    static void GWECacheSetSysColors(int cElements, INT* rgcolor, COLORREF* rgrgb);
    /* ms905258 CacheView_t::Init: print `static void Init(HINSTANCE hInstance, bool bLargeUi);` */
    static void Init(HINSTANCE hInstance, bool bLargeUi);
    /* ms905266 CacheView_t::SystemMetrics: print `static int SystemMetrics(int nIndex);` */
    static int SystemMetrics(int nIndex);
};

#endif /* __cplusplus */

#endif /* AKARI_GCACHEVIEW_HPP */
