/*
 * Gdi.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_GDI_HPP
#define AKARI_GDI_HPP

#include <Windows.h>
#include "Windbase.h"   /* CEOID (CeRemoveFontResource_I's parameter type) */

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class Gdi {
public:
    /* ms905537 Gdi::AbortDoc_I: print `static int AbortDoc_I(HDC hdc);` */
    static int AbortDoc_I(HDC hdc);
    /* ms905538 Gdi::AddFontResourceW_I: print `static int AddFontResourceW_I(const WCHAR* lpszFilename);` */
    static int AddFontResourceW_I(const WCHAR* lpszFilename);
    /* ms905539 Gdi::BitBlt_I: print `static BOOL BitBlt_I(HDC hdcDest, int nXDest, int nYDest, int nWidth, int nHeight, HDC hdcSrc, int nXSrc, int nYSrc, DWORD dwRop);` */
    static BOOL BitBlt_I(HDC hdcDest, int nXDest, int nYDest, int nWidth, int nHeight, HDC hdcSrc, int nXSrc, int nYSrc, DWORD dwRop);
    /* ms905540 Gdi::CeRemoveFontResource_I: print `static BOOL CeRemoveFontResource_I(CEOID oid);` */
    static BOOL CeRemoveFontResource_I(CEOID oid);
    /* ms905541 Gdi::CombineRgn_I: print `static int CombineRgn_I(HRGN hrgnDest, HRGN hrgnSrc1, HRGN hrgnSrc2, int fnCombineMode);` */
    static int CombineRgn_I(HRGN hrgnDest, HRGN hrgnSrc1, HRGN hrgnSrc2, int fnCombineMode);
    /* ms905542 Gdi::CreateBitmap_I: print `static HBITMAP CreateBitmap_I(int nWidth, int nHeight, UINT cPlanes, UINT cBitsPerPel, CONST VOID* lpvBits);` */
    static HBITMAP CreateBitmap_I(int nWidth, int nHeight, UINT cPlanes, UINT cBitsPerPel, VOID* lpvBits);
    /* ms905543 Gdi::CreateCompatibleBitmap_I: print `static HBITMAP CreateCompatibleBitmap_I(HDC hdc, int nWidth, int nHeight);` */
    static HBITMAP CreateCompatibleBitmap_I(HDC hdc, int nWidth, int nHeight);
    /* ms905544 Gdi::CreateCompatibleDC_I: print `static HDC CreateCompatibleDC_I(HDC hdcIn);` */
    static HDC CreateCompatibleDC_I(HDC hdcIn);
    /* ms905545 Gdi::CreateDCW_I: print `static HDC CreateDCW_I(const WCHAR* lpszDriver, const WCHAR* lpszDevice, const WCHAR* lpszOutput, const DEVMODEW* lpInitData);` */
    static HDC CreateDCW_I(const WCHAR* lpszDriver, const WCHAR* lpszDevice, const WCHAR* lpszOutput, const DEVMODEW* lpInitData);
    /* ms905546 Gdi::CreateDIBPatternBrushPt_I: print `static HBRUSH CreateDIBPatternBrushPt_I(const void* lpPackedDIB, unsigned int iUsage);` */
    static HBRUSH CreateDIBPatternBrushPt_I(const void* lpPackedDIB, unsigned int iUsage);
    /* ms905547 Gdi::CreateFontIndirectW_I: print `static HFONT CreateFontIndirectW_I(const LOGFONT* lplf);` */
    static HFONT CreateFontIndirectW_I(const LOGFONT* lplf);
    /* ms905548 Gdi::CreatePalette_I: print `static HPALETTE CreatePalette_I(CONST LOGPALETTE* lplgpl);` */
    static HPALETTE CreatePalette_I(LOGPALETTE* lplgpl);
    /* ms905549 Gdi::CreatePatternBrush_I: print `static HBRUSH CreatePatternBrush_I(HBITMAP hbmp);` */
    static HBRUSH CreatePatternBrush_I(HBITMAP hbmp);
    /* ms905560 Gdi::CreatePenIndirect_I: print `static HPEN CreatePenIndirect_I(const LOGPEN* lplgpn);` */
    static HPEN CreatePenIndirect_I(const LOGPEN* lplgpn);
    /* ms905561 Gdi::CreatePen_I: print `static HPEN CreatePen_I(int fnPenStyle, int nWidth, COLORREF crColor);` */
    static HPEN CreatePen_I(int fnPenStyle, int nWidth, COLORREF crColor);
    /* ms905562 Gdi::CreatePermanentDIBSection: print `static HBITMAP CreatePermanentDIBSection(HDC hdc, CONST BITMAPINFO* pbmi, UINT iUsage, void** ppvBits, HANDLE hSection, DWORD dwOffset);` */
    static HBITMAP CreatePermanentDIBSection(HDC hdc, BITMAPINFO* pbmi, UINT iUsage, void** ppvBits, HANDLE hSection, DWORD dwOffset);
    /* ms905563 Gdi::CreateRectRgnIndirect_I: print `static HRGN CreateRectRgnIndirect_I(const RECT* lprc);` */
    static HRGN CreateRectRgnIndirect_I(const RECT* lprc);
    /* ms905564 Gdi::CreateRectRgn_I: print `static HRGN CreateRectRgn_I(int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);` */
    static HRGN CreateRectRgn_I(int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);
    /* ms905565 Gdi::CreateSolidBrush_I: print `static HBRUSH CreateSolidBrush_I(COLORREF crColor);` */
    static HBRUSH CreateSolidBrush_I(COLORREF crColor);
    /* ms905566 Gdi::DeleteDC_I: print `static BOOL DeleteDC_I(HDC hdc);` */
    static BOOL DeleteDC_I(HDC hdc);
    /* ms905567 Gdi::DeleteObject_I: print `static BOOL DeleteObject_I(HGDIOBJ hgdiobj);` */
    static BOOL DeleteObject_I(HGDIOBJ hgdiobj);
    /* ms905568 Gdi::DibByteWidth: print `static unsigned int DibByteWidth(unsigned int N, unsigned int W);` */
    static unsigned int DibByteWidth(unsigned int N, unsigned int W);
    /* ms905569 Gdi::DibSize: print `static unsigned int DibSize(unsigned int N, unsigned int W, int H);` */
    static unsigned int DibSize(unsigned int N, unsigned int W, int H);
    /* ms905570 Gdi::DrawEdge_I: print `static BOOL DrawEdge_I(HDC hdc, RECT* qrc, unsigned int edge, unsigned int grfFlags);` */
    static BOOL DrawEdge_I(HDC hdc, RECT* qrc, unsigned int edge, unsigned int grfFlags);
    /* ms905571 Gdi::DrawFocusRect_I: print `static BOOL DrawFocusRect_I(HDC hDC, const RECT* lprc);` */
    static BOOL DrawFocusRect_I(HDC hDC, const RECT* lprc);
    /* ms905572 Gdi::DrawTextW_I: print `static int DrawTextW_I(HDC hDC, const WCHAR* lpString, int nCount, RECT* lpRect, unsigned int uFormat);` */
    static int DrawTextW_I(HDC hDC, const WCHAR* lpString, int nCount, RECT* lpRect, unsigned int uFormat);
    /* ms905573 Gdi::Ellipse_I: print `static BOOL Ellipse_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);` */
    static BOOL Ellipse_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);
    /* ms905574 Gdi::EnableEUDC_I: print `static BOOL EnableEUDC_I(BOOL fEnableEUDC);` */
    static BOOL EnableEUDC_I(BOOL fEnableEUDC);
    /* ms905575 Gdi::EndDoc_I: print `static int EndDoc_I(HDC hdc);` */
    static int EndDoc_I(HDC hdc);
    /* ms905576 Gdi::EndPage_I: print `static int EndPage_I(HDC hdc);` */
    static int EndPage_I(HDC hdc);
    /* ms905577 Gdi::EnumDisplayMonitors_I: print `static BOOL EnumDisplayMonitors_I(HDC hdcPaint, LPCRECT lprcPaint, MONITORENUMPROC lpfnEnum, LPARAM lData HPROCESS hProcCallingContext);`
     *   -- HELD: parameter type `LPARAM lData HPROCESS hProcCallingContext` has no defining
     *   page in the harvested official corpus */
    /* ms905578 Gdi::EnumFontFamiliesW_I: print `static int EnumFontFamiliesW_I(HDC hdc, const WCHAR* lpszFamily, FONTENUMPROC lpEnumFontFamProc, LPARAM lParam);` */
    static int EnumFontFamiliesW_I(HDC hdc, const WCHAR* lpszFamily, FONTENUMPROC lpEnumFontFamProc, LPARAM lParam);
    /* ms905579 Gdi::EnumFontsW_I: print `static int EnumFontsW_I(HDC hdc, const WCHAR* lpFaceName, FONTENUMPROC lpFontFunc, LPARAM lParam);` */
    static int EnumFontsW_I(HDC hdc, const WCHAR* lpFaceName, FONTENUMPROC lpFontFunc, LPARAM lParam);
    /* ms905580 Gdi::ExcludeClipRect_I: print `static int ExcludeClipRect_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);` */
    static int ExcludeClipRect_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);
    /* ms905581 Gdi::ExtEscape_I: print `static int ExtEscape_I(HDC hdc, int nEscape, int cbInput, const char* lpszInData, int cbOutput, char* lpszOutData);` */
    static int ExtEscape_I(HDC hdc, int nEscape, int cbInput, const char* lpszInData, int cbOutput, char* lpszOutData);
    /* ms905582 Gdi::ExtTextOutW_I: print `static BOOL ExtTextOutW_I(HDC hdc, int X, int Y, unsigned int fuOptions, const RECT* lprc, const WCHAR* lpszString, unsigned int cbCount, const int* lpDx);` */
    static BOOL ExtTextOutW_I(HDC hdc, int X, int Y, unsigned int fuOptions, const RECT* lprc, const WCHAR* lpszString, unsigned int cbCount, const int* lpDx);
    /* ms905583 Gdi::FillRect_I: print `static int FillRect_I(HDC hDC, CONST RECT* lprc, HBRUSH hbr);` */
    static int FillRect_I(HDC hDC, RECT* lprc, HBRUSH hbr);
    /* ms905584 Gdi::FillRgn_I: print `static BOOL FillRgn_I(HDC hdc, HRGN hrgn, HBRUSH hbr);` */
    static BOOL FillRgn_I(HDC hdc, HRGN hrgn, HBRUSH hbr);
    /* ms905585 Gdi::GdiSetObjectOwner_I: print `static BOOL GdiSetObjectOwner_I(HGDIOBJ hgdiobj, HPROCESS hprc);`
     *   -- HELD: parameter type `HPROCESS hprc` has no defining
     *   page in the harvested official corpus */
    /* ms905586 Gdi::GetBkColor_I: print `static COLORREF GetBkColor_I(HDC hdc);` */
    static COLORREF GetBkColor_I(HDC hdc);
    /* ms905587 Gdi::GetBkMode_I: print `static int GetBkMode_I(HDC hdc);` */
    static int GetBkMode_I(HDC hdc);
    /* ms905588 Gdi::GetClipBox_I: print `static int GetClipBox_I(HDC hdc, RECT* lprc);` */
    static int GetClipBox_I(HDC hdc, RECT* lprc);
    /* ms905589 Gdi::GetClipRgn_I: print `static int GetClipRgn_I(HDC hdc, HRGN hrgn);` */
    static int GetClipRgn_I(HDC hdc, HRGN hrgn);
    /* ms905590 Gdi::GetCurrentObject_I: print `static HGDIOBJ GetCurrentObject_I(HDC hdc, unsigned int uObjectType);` */
    static HGDIOBJ GetCurrentObject_I(HDC hdc, unsigned int uObjectType);
    /* ms905591 Gdi::GetDeviceCaps_I: print `static int GetDeviceCaps_I(HDC hdc, int nIndex);` */
    static int GetDeviceCaps_I(HDC hdc, int nIndex);
    /* ms905592 Gdi::GetMonitorInfo_I: print `static BOOL GetMonitorInfo_I(HMONITOR hMonitor, LPMONITORINFO lpmi);` */
    static BOOL GetMonitorInfo_I(HMONITOR hMonitor, LPMONITORINFO lpmi);
    /* ms905593 Gdi::GetNearestColor_I: print `static COLORREF GetNearestColor_I(HDC hdc, COLORREF crColor);` */
    static COLORREF GetNearestColor_I(HDC hdc, COLORREF crColor);
    /* ms905594 Gdi::GetNearestPaletteIndex_I: print `static unsigned int GetNearestPaletteIndex_I(HPALETTE hpal, COLORREF crColor);` */
    static unsigned int GetNearestPaletteIndex_I(HPALETTE hpal, COLORREF crColor);
    /* ms905595 Gdi::GetObjectType_I: print `static DWORD GetObjectType_I(HGDIOBJ hgdiobj);` */
    static DWORD GetObjectType_I(HGDIOBJ hgdiobj);
    /* ms905596 Gdi::GetObjectW_I: print `static int GetObjectW_I(HGDIOBJ hgdiobj, int cbBuffer, void* lpvObject);` */
    static int GetObjectW_I(HGDIOBJ hgdiobj, int cbBuffer, void* lpvObject);
    /* ms905597 Gdi::GetPaletteEntries_I: print `static unsigned int GetPaletteEntries_I(HPALETTE hpal, unsigned int iStartIndex, unsigned int nEntries, PALETTEENTRY* lppe);` */
    static unsigned int GetPaletteEntries_I(HPALETTE hpal, unsigned int iStartIndex, unsigned int nEntries, PALETTEENTRY* lppe);
    /* ms905598 Gdi::GetPixel_I: print `static COLORREF GetPixel_I(HDC hdc, int nXPos, int nYPos);` */
    static COLORREF GetPixel_I(HDC hdc, int nXPos, int nYPos);
    /* ms905599 Gdi::GetRegionData_I: print `static DWORD GetRegionData_I(HRGN hRgn, DWORD dwCount, RGNDATA* lpRgnData);` */
    static DWORD GetRegionData_I(HRGN hRgn, DWORD dwCount, RGNDATA* lpRgnData);
    /* ms905600 Gdi::GetRgnBox_I: print `static int GetRgnBox_I(HRGN hrgn, RECT* lprc);` */
    static int GetRgnBox_I(HRGN hrgn, RECT* lprc);
    /* ms905601 Gdi::GetSysColorBrush_I: print `static HBRUSH GetSysColorBrush_I(int nIndex);` */
    static HBRUSH GetSysColorBrush_I(int nIndex);
    /* ms905602 Gdi::GetSystemPaletteEntries_I: print `static unsigned int GetSystemPaletteEntries_I(HDC hdc, unsigned int iStartIndex, unsigned int nEntries, PALETTEENTRY* lppe);` */
    static unsigned int GetSystemPaletteEntries_I(HDC hdc, unsigned int iStartIndex, unsigned int nEntries, PALETTEENTRY* lppe);
    /* ms905603 Gdi::GetTextColor_I: print `static COLORREF GetTextColor_I(HDC hdc);` */
    static COLORREF GetTextColor_I(HDC hdc);
    /* ms905604 Gdi::GetTextExtentExPointW_I: print `static BOOL GetTextExtentExPointW_I(HDC hdc, const WCHAR* lpszStr, int cchString, int nMaxExtent, int* lpnFit, int* alpDx, SIZE* lpSize);` */
    static BOOL GetTextExtentExPointW_I(HDC hdc, const WCHAR* lpszStr, int cchString, int nMaxExtent, int* lpnFit, int* alpDx, SIZE* lpSize);
    /* ms905605 Gdi::GetTextFaceW_I: print `static int GetTextFaceW_I(HDC hdc, int nCount, WCHAR* lpFaceName);` */
    static int GetTextFaceW_I(HDC hdc, int nCount, WCHAR* lpFaceName);
    /* ms905607 Gdi::IntersectClipRect_I: print `static int IntersectClipRect_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);` */
    static int IntersectClipRect_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);
    /* ms905608 Gdi::InvertRect_I: print `static BOOL InvertRect_I(HDC hdc, const RECT* lprc);` */
    static BOOL InvertRect_I(HDC hdc, const RECT* lprc);
    /* ms905609 Gdi::MaskBlt_I: print `static BOOL MaskBlt_I(HDC hdcDest, int nXDest, int nYDest, int nWidth, int nHeight, HDC hdcSrc, int nXSrc, int nYSrc, HBITMAP hbmMask, int xMask, int yMask, DWORD dwRop);` */
    static BOOL MaskBlt_I(HDC hdcDest, int nXDest, int nYDest, int nWidth, int nHeight, HDC hdcSrc, int nXSrc, int nYSrc, HBITMAP hbmMask, int xMask, int yMask, DWORD dwRop);
    /* ms905610 Gdi::MonitorFromPoint_I: print `static HMONITOR MonitorFromPoint_I(POINT pt, DWORD dwFlag);` */
    static HMONITOR MonitorFromPoint_I(POINT pt, DWORD dwFlag);
    /* ms905611 Gdi::MonitorFromRect_I: print `static HMONITOR MonitorFromRect_I(LPCRECT lprc, DWORD dwFlag);` */
    static HMONITOR MonitorFromRect_I(LPCRECT lprc, DWORD dwFlag);
    /* ms905612 Gdi::MonitorFromWindow_I: print `static HMONITOR MonitorFromWindow_I(HWND hwnd, DWORD dwFlag);` */
    static HMONITOR MonitorFromWindow_I(HWND hwnd, DWORD dwFlag);
    /* ms905613 Gdi::OffsetRgn_I: print `static int OffsetRgn_I(HRGN hrgn, int nXOffset, int nYOffset);` */
    static int OffsetRgn_I(HRGN hrgn, int nXOffset, int nYOffset);
    /* ms905614 Gdi::PatBlt_I: print `static BOOL PatBlt_I(HDC hdc, int nXLeft, int nYLeft, int nWidth, int nHeight, DWORD dwRop);` */
    static BOOL PatBlt_I(HDC hdc, int nXLeft, int nYLeft, int nWidth, int nHeight, DWORD dwRop);
    /* ms905615 Gdi::Polygon_I: print `static BOOL Polygon_I(HDC hdc, const POINT* lpPoints, int nCount);` */
    static BOOL Polygon_I(HDC hdc, const POINT* lpPoints, int nCount);
    /* ms905616 Gdi::Polyline_I: print `static BOOL Polyline_I(HDC hdc, const POINT* lppt, int cPoints);` */
    static BOOL Polyline_I(HDC hdc, const POINT* lppt, int cPoints);
    /* ms905617 Gdi::PtInRegion_I: print `static BOOL PtInRegion_I(HRGN hrgn, int X, int Y);` */
    static BOOL PtInRegion_I(HRGN hrgn, int X, int Y);
    /* ms905618 Gdi::RealizePalette_I: print `static unsigned int RealizePalette_I(HDC hdc);` */
    static unsigned int RealizePalette_I(HDC hdc);
    /* ms905619 Gdi::Rectangle_I: print `static BOOL Rectangle_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);` */
    static BOOL Rectangle_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);
    /* ms905620 Gdi::RectInRegion_I: print `static BOOL RectInRegion_I(HRGN hrgn, const RECT* lprc);` */
    static BOOL RectInRegion_I(HRGN hrgn, const RECT* lprc);
    /* ms905621 Gdi::RectVisible_I: print `static BOOL RectVisible_I(HDC hdc, CONST RECT* lprc);` */
    static BOOL RectVisible_I(HDC hdc, RECT* lprc);
    /* ms905975 Gdi::RemoveFontResourceW_I: print `static BOOL RemoveFontResourceW_I(const WCHAR* lpFileName);` */
    static BOOL RemoveFontResourceW_I(const WCHAR* lpFileName);
    /* ms906057 Gdi::RestoreDC_I: print `static BOOL RestoreDC_I(HDC hdc, int nSavedDC);` */
    static BOOL RestoreDC_I(HDC hdc, int nSavedDC);
    /* ms906065 Gdi::RoundRect_I: print `static BOOL RoundRect_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nWidth, int nHeight);` */
    static BOOL RoundRect_I(HDC hdc, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect, int nWidth, int nHeight);
    /* ms906066 Gdi::SaveDC_I: print `static int SaveDC_I(HDC hdc);` */
    static int SaveDC_I(HDC hdc);
    /* ms906067 Gdi::ScrollDC_I: print `static BOOL ScrollDC_I(HDC hdc, int dx, int dy, const RECT* lprcScroll, const RECT* lprcClip, HRGN hrgnUpdate, RECT* lprcUpdate);` */
    static BOOL ScrollDC_I(HDC hdc, int dx, int dy, const RECT* lprcScroll, const RECT* lprcClip, HRGN hrgnUpdate, RECT* lprcUpdate);
    /* ms906068 Gdi::SelectClipRgn_I: print `static int SelectClipRgn_I(HDC hdc, HRGN hrgn);` */
    static int SelectClipRgn_I(HDC hdc, HRGN hrgn);
    /* ms906069 Gdi::SelectObject_I: print `static HGDIOBJ SelectObject_I(HDC hdc, HGDIOBJ hgdiobj);` */
    static HGDIOBJ SelectObject_I(HDC hdc, HGDIOBJ hgdiobj);
    /* ms906070 Gdi::SelectPalette_I: print `static HPALETTE SelectPalette_I(HDC hdc, HPALETTE hpal, BOOL bForceBackground);` */
    static HPALETTE SelectPalette_I(HDC hdc, HPALETTE hpal, BOOL bForceBackground);
    /* ms906071 Gdi::SetAbortProc_I: print `static int SetAbortProc_I(HDC hdc, ABORTPROC lpAbortProc);` */
    static int SetAbortProc_I(HDC hdc, ABORTPROC lpAbortProc);
    /* ms906072 Gdi::SetBkColor_I: print `static COLORREF SetBkColor_I(HDC hdc, COLORREF crColor);` */
    static COLORREF SetBkColor_I(HDC hdc, COLORREF crColor);
    /* ms906073 Gdi::SetBkMode_I: print `static int SetBkMode_I(HDC hdc, int iBkMode);` */
    static int SetBkMode_I(HDC hdc, int iBkMode);
    /* ms906074 Gdi::SetBrushOrgEx_I: print `static BOOL SetBrushOrgEx_I(HDC hdc, int nXOrg, int nYOrg, POINT* lppt);` */
    static BOOL SetBrushOrgEx_I(HDC hdc, int nXOrg, int nYOrg, POINT* lppt);
    /* ms906075 Gdi::SetPaletteEntries_I: print `static unsigned int SetPaletteEntries_I(HPALETTE hpal, unsigned int iStart, unsigned int cEntries, CONST PALETTEENTRY* lppe);` */
    static unsigned int SetPaletteEntries_I(HPALETTE hpal, unsigned int iStart, unsigned int cEntries, PALETTEENTRY* lppe);
    /* ms906076 Gdi::SetPixel_I: print `static COLORREF SetPixel_I(HDC hdc, int X, int Y, COLORREF crColor);` */
    static COLORREF SetPixel_I(HDC hdc, int X, int Y, COLORREF crColor);
    /* ms906077 Gdi::SetRectRgn_I: print `static BOOL SetRectRgn_I(HRGN hrgn, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);` */
    static BOOL SetRectRgn_I(HRGN hrgn, int nLeftRect, int nTopRect, int nRightRect, int nBottomRect);
    /* ms906078 Gdi::SetROP2_I: print `static int SetROP2_I(HDC hdc, int fnDrawMode);` */
    static int SetROP2_I(HDC hdc, int fnDrawMode);
    /* ms906079 Gdi::SetTextColor_I: print `static COLORREF SetTextColor_I(HDC hdc, COLORREF crColor);` */
    static COLORREF SetTextColor_I(HDC hdc, COLORREF crColor);
    /* ms906080 Gdi::SetViewportOrgEx_I: print `static BOOL SetViewportOrgEx_I(HDC hdc, int nXOrg, int nYOrg, POINT* lppt);` */
    static BOOL SetViewportOrgEx_I(HDC hdc, int nXOrg, int nYOrg, POINT* lppt);
    /* ms906081 Gdi::StartDocW_I: print `static int StartDocW_I(HDC hdc, CONST DOCINFO* lpdi);` */
    static int StartDocW_I(HDC hdc, DOCINFO* lpdi);
    /* ms906082 Gdi::StartPage_I: print `static int StartPage_I(HDC hDC);` */
    static int StartPage_I(HDC hDC);
    /* ms906083 Gdi::StretchBlt_I: print `static BOOL StretchBlt_I(HDC hdcDest, int nXOriginDest, int nYOriginDest, int nWidthDest, int nHeightDest, HDC hdcSrc, int nXOriginSrc, int nYOriginSrc, int nWidthSrc, int nHeightSrc, DWORD dwRop);` */
    static BOOL StretchBlt_I(HDC hdcDest, int nXOriginDest, int nYOriginDest, int nWidthDest, int nHeightDest, HDC hdcSrc, int nXOriginSrc, int nYOriginSrc, int nWidthSrc, int nHeightSrc, DWORD dwRop);
    /* ms906084 Gdi::TranslateCharsetInfo_I: print `static BOOL TranslateCharsetInfo_I(DWORD* lpSrc, CHARSETINFO* lpCs, DWORD dwFlags);` */
    static BOOL TranslateCharsetInfo_I(DWORD* lpSrc, CHARSETINFO* lpCs, DWORD dwFlags);
    /* ms906085 Gdi::TransparentImage_I: print `static BOOL TransparentImage_I(HDC hdcDest, int DstX, int DstY, int DstCx, int DstCy, HANDLE hSrc, int SrcX, int SrcY, int SrcCx, int SrcCy, COLORREF TransparentColor);` */
    static BOOL TransparentImage_I(HDC hdcDest, int DstX, int DstY, int DstCx, int DstCy, HANDLE hSrc, int SrcX, int SrcY, int SrcCx, int SrcCy, COLORREF TransparentColor);
};

/* ms905606 Gdi::GetTextMetricsW_I (Header: Gdi.hpp.): no class-member
 * print on the page (record only) */
#endif /* __cplusplus */

#endif /* AKARI_GDI_HPP */
