/*
 * Headerview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_HEADERVIEW_HPP
#define AKARI_HEADERVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class HeaderView_t {
public:
    /* ms906151 HeaderView_t::CalcOffset: print `static void CalcOffset(int cxBorder, int cyBorder, int* pxOffset, int* pyOffset);` */
    static void CalcOffset(int cxBorder, int cyBorder, int* pxOffset, int* pyOffset);
    /* ms906152 HeaderView_t::DrawButtonBorder: print `static void DrawButtonBorder(HDC hdc, DWORD style, LPRECT prc, BOOL fItemSunken);` */
    static void DrawButtonBorder(HDC hdc, DWORD style, LPRECT prc, BOOL fItemSunken);
    /* ms906153 HeaderView_t::Height: print `static int Height(int cyChar, int cyEdge);` */
    static int Height(int cyChar, int cyEdge);
};

#endif /* __cplusplus */

#endif /* AKARI_HEADERVIEW_HPP */
