/*
 * IAccess.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-iaccess.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_IACCESS_H
#define AKARI_IACCESS_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-iaccess (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa515095 IAccessControl::GetAllAccessRights (Header: IAccess.h.) */
/* ms886995 IAccessControl::GetAllAccessRights (Header: IAccess.h.) */
/* aa515097 IAccessControl::GrantAccessRights (Header: IAccess.h.) */
/* ms886996 IAccessControl::GrantAccessRights (Header: IAccess.h.) */
/* aa515099 IAccessControl::IsAccessAllowed (Header: IAccess.h.) */
/* ms886997 IAccessControl::IsAccessAllowed (Header: IAccess.h.) */
/* aa515102 IAccessControl::RevokeAccessRights (Header: IAccess.h.) */
/* ms887001 IAccessControl::RevokeAccessRights (Header: IAccess.h.) */
/* aa515103 IAccessControl::SetAccessRights (Header: IAccess.h.) */
/* ms887002 IAccessControl::SetAccessRights (Header: IAccess.h.) */
/* aa515104 IAccessControl::SetOwner (Header: IAccess.h.) */
/* ms887003 IAccessControl::SetOwner (Header: IAccess.h.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_IACCESS_H */
