/*
 * Iltiming.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-iltiming.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_ILTIMING_H
#define AKARI_ILTIMING_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-iltiming (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* _wcepb_ILTIMING_MESSAGE ILTIMING_MESSAGE (page print, compiled)  [twin page(s): ms906156] */
typedef struct tILTIMING_MESSAGE {
    WORD wMsg;
    WORD wNumInterrupts;
    DWORD dwIsrTime1;
    DWORD dwIsrTime2;
    DWORD dwSPC;
    DWORD dwFrequency;
    PVOID pfnPerfCountSinceTick;
} ILTIMING_MESSAGE, *PILTIMING_MESSAGE;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_ILTIMING_H */
