/*
 * Loadauth.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-loadauth.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_LOADAUTH_H
#define AKARI_LOADAUTH_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-loadauth (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* _wcepb_WIN_CERTIFICATE WIN_CERTIFICATE (page print, compiled)  [twin page(s): ms920091] */
typedef struct WIN_CERTIFICATE {
    DWORD dwLength;
    WORD wRevision;
    WORD wCertificateType;
    BYTE bCertificate[];
} WIN_CERTIFICATE, *LPWIN_CERTIFICATE;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_LOADAUTH_H */
