/* WinCE development API surface.
 * Original declarations written from a survey of CE 4.2, 5.0, and 6.0
 * public interface facts (names, types, layouts, constants, exports).
 * Not an OS, BSP, OAK, or Platform Builder component, and not a copy
 * of upstream source.
 */

#ifndef WCE_MMREG_H
#define WCE_MMREG_H
#include "windef.h"
#include "winnt.h"
#include "wceunk.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tagWAVEFORMAT { WORD wFormatTag; WORD nChannels; DWORD nSamplesPerSec; DWORD nAvgBytesPerSec; WORD nBlockAlign; } WAVEFORMAT, *PWAVEFORMAT, *LPWAVEFORMAT;
typedef struct tagPCMWAVEFORMAT { WAVEFORMAT wf; WORD wBitsPerSample; } PCMWAVEFORMAT, *PPCMWAVEFORMAT, *LPPCMWAVEFORMAT;
typedef struct tagWAVEFORMATEX { WORD wFormatTag; WORD nChannels; DWORD nSamplesPerSec; DWORD nAvgBytesPerSec; WORD nBlockAlign; WORD wBitsPerSample; WORD cbSize; } WAVEFORMATEX, *PWAVEFORMATEX, *LPWAVEFORMATEX;
typedef struct tagADPCMCOEFSET { short iCoef1; short iCoef2; } ADPCMCOEFSET, *PADPCMCOEFSET, *LPADPCMCOEFSET;
typedef struct tagDRMWAVEFORMAT { WAVEFORMATEX wfx; WORD wReserved; ULONG ulContentId; WAVEFORMATEX wfxSecure; } DRMWAVEFORMAT, *PDRMWAVEFORMAT, *LPDRMWAVEFORMAT;
typedef struct tagDVIADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } DVIADPCMWAVEFORMAT, *PDVIADPCMWAVEFORMAT, *LPDVIADPCMWAVEFORMAT;
typedef struct tagIMAADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } IMAADPCMWAVEFORMAT, *PIMAADPCMWAVEFORMAT, *LPIMAADPCMWAVEFORMAT;
typedef struct tagMEDIASPACEADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; } MEDIASPACEADPCMWAVEFORMAT, *PMEDIASPACEADPCMWAVEFORMAT, *LPMEDIASPACEADPCMWAVEFORMAT;
typedef struct tagSIERRAADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; } SIERRAADPCMWAVEFORMAT, *PSIERRAADPCMWAVEFORMAT, *LPSIERRAADPCMWAVEFORMAT;
typedef struct tagG723_ADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD cbExtraSize; WORD nAuxBlockSize; } G723_ADPCMWAVEFORMAT, *PG723_ADPCMWAVEFORMAT, *LPG723_ADPCMWAVEFORMAT;
typedef struct tagDIGISTDWAVEFORMAT { WAVEFORMATEX wfx; } DIGISTDWAVEFORMAT, *PDIGISTDWAVEFORMAT, *LPDIGISTDWAVEFORMAT;
typedef struct tagDIGIFIXWAVEFORMAT { WAVEFORMATEX wfx; } DIGIFIXWAVEFORMAT, *PDIGIFIXWAVEFORMAT, *LPDIGIFIXWAVEFORMAT;
typedef struct tagDIALOGICOKIADPCMWAVEFORMAT { WAVEFORMATEX ewf; } DIALOGICOKIADPCMWAVEFORMAT, *PDIALOGICOKIADPCMWAVEFORMAT, *LPDIALOGICOKIADPCMWAVEFORMAT;
typedef struct tagYAMAHA_ADPCMWAVEFORMAT { WAVEFORMATEX wfx; } YAMAHA_ADPCMWAVEFORMAT, *PYAMAHA_ADPCMWAVEFORMAT, *LPYAMAHA_ADPCMWAVEFORMAT;
typedef struct tagSONARCWAVEFORMAT { WAVEFORMATEX wfx; WORD wCompType; } SONARCWAVEFORMAT, *PSONARCWAVEFORMAT, *LPSONARCWAVEFORMAT;
typedef struct tagTRUESPEECHWAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; WORD nSamplesPerBlock; BYTE abReserved[28]; } TRUESPEECHWAVEFORMAT, *PTRUESPEECHWAVEFORMAT, *LPTRUESPEECHWAVEFORMAT;
typedef struct tagECHOSC1WAVEFORMAT { WAVEFORMATEX wfx; } ECHOSC1WAVEFORMAT, *PECHOSC1WAVEFORMAT, *LPECHOSC1WAVEFORMAT;
typedef struct tagAUDIOFILE_AF36WAVEFORMAT { WAVEFORMATEX wfx; } AUDIOFILE_AF36WAVEFORMAT, *PAUDIOFILE_AF36WAVEFORMAT, *LPAUDIOFILE_AF36WAVEFORMAT;
typedef struct tagAPTXWAVEFORMAT { WAVEFORMATEX wfx; } APTXWAVEFORMAT, *PAPTXWAVEFORMAT, *LPAPTXWAVEFORMAT;
typedef struct tagAUDIOFILE_AF10WAVEFORMAT { WAVEFORMATEX wfx; } AUDIOFILE_AF10WAVEFORMAT, *PAUDIOFILE_AF10WAVEFORMAT, *LPAUDIOFILE_AF10WAVEFORMAT;
typedef struct tagDOLBYAC2WAVEFORMAT { WAVEFORMATEX wfx; WORD nAuxBitsCode; } DOLBYAC2WAVEFORMAT, *PDOLBYAC2WAVEFORMAT, *LPDOLBYAC2WAVEFORMAT;
typedef struct tagGSM610WAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } GSM610WAVEFORMAT, *PGSM610WAVEFORMAT, *LPGSM610WAVEFORMAT;
typedef struct tagADPCMEWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } ADPCMEWAVEFORMAT, *PADPCMEWAVEFORMAT, *LPADPCMEWAVEFORMAT;
typedef struct tagCONTRESVQLPCWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } CONTRESVQLPCWAVEFORMAT, *PCONTRESVQLPCWAVEFORMAT, *LPCONTRESVQLPCWAVEFORMAT;
typedef struct tagDIGIREALWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } DIGIREALWAVEFORMAT, *PDIGIREALWAVEFORMAT, *LPDIGIREALWAVEFORMAT;
typedef struct tagDIGIADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } DIGIADPCMWAVEFORMAT, *PDIGIADPCMWAVEFORMAT, *LPDIGIADPCMWAVEFORMAT;
typedef struct tagCONTRESCR10WAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } CONTRESCR10WAVEFORMAT, *PCONTRESCR10WAVEFORMAT, *LPCONTRESCR10WAVEFORMAT;
typedef struct tagNMS_VBXADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; } NMS_VBXADPCMWAVEFORMAT, *PNMS_VBXADPCMWAVEFORMAT, *LPNMS_VBXADPCMWAVEFORMAT;
typedef struct tagG721_ADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD nAuxBlockSize; } G721_ADPCMWAVEFORMAT, *PG721_ADPCMWAVEFORMAT, *LPG721_ADPCMWAVEFORMAT;
typedef struct tagMPEG1WAVEFORMAT { WAVEFORMATEX wfx; WORD fwHeadLayer; DWORD dwHeadBitrate; WORD fwHeadMode; WORD fwHeadModeExt; WORD wHeadEmphasis; WORD fwHeadFlags; DWORD dwPTSLow; DWORD dwPTSHigh; } MPEG1WAVEFORMAT, *PMPEG1WAVEFORMAT, *LPMPEG1WAVEFORMAT;
typedef struct tagMPEGLAYER3WAVEFORMAT { WAVEFORMATEX wfx; WORD wID; DWORD fdwFlags; WORD nBlockSize; WORD nFramesPerBlock; WORD nCodecDelay; } MPEGLAYER3WAVEFORMAT, *PMPEGLAYER3WAVEFORMAT, *LPMPEGLAYER3WAVEFORMAT;
typedef struct tagMSAUDIO1WAVEFORMAT { WAVEFORMATEX wfx; WORD wSamplesPerBlock; WORD wEncodeOptions; } MSAUDIO1WAVEFORMAT, *PMSAUDIO1WAVEFORMAT, *LPMSAUDIO1WAVEFORMAT;
typedef struct tagWMAUDIO2WAVEFORMAT { WAVEFORMATEX wfx; DWORD dwSamplesPerBlock; WORD wEncodeOptions; DWORD dwSuperBlockAlign; } WMAUDIO2WAVEFORMAT, *PWMAUDIO2WAVEFORMAT, *LPWMAUDIO2WAVEFORMAT;
typedef struct tagWMAUDIO3WAVEFORMAT { WAVEFORMATEX wfx; WORD wValidBitsPerSample; DWORD dwChannelMask; DWORD dwReserved1; DWORD dwReserved2; WORD wEncodeOptions; WORD wReserved3; } WMAUDIO3WAVEFORMAT, *PWMAUDIO3WAVEFORMAT, *LPWMAUDIO3WAVEFORMAT;
typedef struct tagCREATIVEADPCMWAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; } CREATIVEADPCMWAVEFORMAT, *PCREATIVEADPCMWAVEFORMAT, *LPCREATIVEADPCMWAVEFORMAT;
typedef struct tagCREATIVEFASTSPEECH8WAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; } CREATIVEFASTSPEECH8WAVEFORMAT, *PCREATIVEFASTSPEECH8WAVEFORMAT, *LPCREATIVEFASTSPEECH8WAVEFORMAT;
typedef struct tagCREATIVEFASTSPEECH10WAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; } CREATIVEFASTSPEECH10WAVEFORMAT, *PCREATIVEFASTSPEECH10WAVEFORMAT, *LPCREATIVEFASTSPEECH10WAVEFORMAT;
typedef struct tagFMTOWNS_SND_WAVEFORMAT { WAVEFORMATEX wfx; WORD wRevision; } FMTOWNS_SND_WAVEFORMAT, *PFMTOWNS_SND_WAVEFORMAT, *LPFMTOWNS_SND_WAVEFORMAT;
typedef struct tagOLIGSMWAVEFORMAT { WAVEFORMATEX wfx; } OLIGSMWAVEFORMAT, *POLIGSMWAVEFORMAT, *LPOLIGSMWAVEFORMAT;
typedef struct tagOLIADPCMWAVEFORMAT { WAVEFORMATEX wfx; } OLIADPCMWAVEFORMAT, *POLIADPCMWAVEFORMAT, *LPOLIADPCMWAVEFORMAT;
typedef struct tagOLICELPWAVEFORMAT { WAVEFORMATEX wfx; } OLICELPWAVEFORMAT, *POLICELPWAVEFORMAT, *LPOLICELPWAVEFORMAT;
typedef struct tagOLISBCWAVEFORMAT { WAVEFORMATEX wfx; } OLISBCWAVEFORMAT, *POLISBCWAVEFORMAT, *LPOLISBCWAVEFORMAT;
typedef struct tagOLIOPRWAVEFORMAT { WAVEFORMATEX wfx; } OLIOPRWAVEFORMAT, *POLIOPRWAVEFORMAT, *LPOLIOPRWAVEFORMAT;
typedef struct tagCSIMAADPCMWAVEFORMAT { WAVEFORMATEX wfx; } CSIMAADPCMWAVEFORMAT, *PCSIMAADPCMWAVEFORMAT, *LPCSIMAADPCMWAVEFORMAT;
typedef struct tagWAVEFILTER { DWORD cbStruct; DWORD dwFilterTag; DWORD fdwFilter; DWORD dwReserved[5]; } WAVEFILTER, *PWAVEFILTER, *LPWAVEFILTER;
typedef struct tagVOLUMEWAVEFILTER { WAVEFILTER wfltr; DWORD dwVolume; } VOLUMEWAVEFILTER, *PVOLUMEWAVEFILTER, *LPVOLUMEWAVEFILTER;
typedef struct tagECHOWAVEFILTER { WAVEFILTER wfltr; DWORD dwVolume; DWORD dwDelay; } ECHOWAVEFILTER, *PECHOWAVEFILTER, *LPECHOWAVEFILTER;
typedef struct tagEXBMINFOHEADER { BITMAPINFOHEADER bmi; DWORD biExtDataOffset; } EXBMINFOHEADER, *PEXBMINFOHEADER, *LPEXBMINFOHEADER;
typedef struct tagJPEGINFOHEADER { DWORD JPEGSize; DWORD JPEGProcess; DWORD JPEGColorSpaceID; DWORD JPEGBitsPerSample; DWORD JPEGHSubSampling; DWORD JPEGVSubSampling; } JPEGINFOHEADER, *PJPEGINFOHEADER, *LPJPEGINFOHEADER;
typedef struct tagWAVEFORMATEXTENSIBLE { WORD wFormatTag; WORD nChannels; DWORD nSamplesPerSec; DWORD nAvgBytesPerSec; WORD nBlockAlign; WORD wBitsPerSample; WORD cbSize; WORD wValidBitsPerSample; DWORD dwChannelMask; GUID SubFormat; } WAVEFORMATEXTENSIBLE, *PWAVEFORMATEXTENSIBLE, *LPWAVEFORMATEXTENSIBLE;


#ifdef __cplusplus
}
#endif
#endif

