/*
 * Mqoai.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-mqoai.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_MQOAI_H
#define AKARI_MQOAI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: m107-mqoai (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895153 MSMQEvent.Arrived (Header: Mqoai.h.): print `void Arrived(IDispatch* Queue,longCursor);` */
/* ms895154 MSMQEvent.ArrivedError (Header: Mqoai.h.): print `void ArrivedError(Idispatch* Queue,longErrorCode,longCursor);` */
/* ms895158 MSMQMessage.Ack (Header: Mqoai.h.): page record, no signature printed */
/* ms895160 MSMQMessage.AdminQueueInfo (Header: Mqoai.h.): page record, no signature printed */
/* ms895163 MSMQMessage.AppSpecific (Header: Mqoai.h.): page record, no signature printed */
/* ms895164 MSMQMessage.ArrivedTime (Header: Mqoai.h.): page record, no signature printed */
/* ms895166 MSMQMessage.AuthLevel (Header: Mqoai.h.): page record, no signature printed */
/* ms895169 MSMQMessage.Body (Header: Mqoai.h.): page record, no signature printed */
/* ms895170 MSMQMessage.BodyLength (Header: Mqoai.h.): page record, no signature printed */
/* ms895173 MSMQMessage.Class (Header: Mqoai.h.): page record, no signature printed */
/* ms895174 MSMQMessage.CorrelationId (Header: Mqoai.h.): page record, no signature printed */
/* ms895176 MSMQMessage.Delivery (Header: Mqoai.h.): page record, no signature printed */
/* ms895178 MSMQMessage.DestinationQueueInfo (Header: Mqoai.h.): page record, no signature printed */
/* ms895181 MSMQMessage.EncryptAlgorithm (Header: Mqoai.h.): page record, no signature printed */
/* ms895182 MSMQMessage.Extension (Header: Mqoai.h.): page record, no signature printed */
/* ms895185 MSMQMessage.HashAlgorithm (Header: Mqoai.h.): page record, no signature printed */
/* ms895186 MSMQMessage.Id (Header: Mqoai.h.): page record, no signature printed */
/* ms895189 MSMQMessage.IsAuthenticated (Header: Mqoai.h.): page record, no signature printed */
/* ms895190 MSMQMessage.Journal (Header: Mqoai.h.): page record, no signature printed */
/* ms895193 MSMQMessage.Label (Header: Mqoai.h.): page record, no signature printed */
/* ms895194 MSMQMessage.MaxTimeToReachQueue (Header: Mqoai.h.): print `HRESULT get_ MaxTimeToReachQueue(long* plMaxTimeToReachQueue);` */
/* ms895196 MSMQMessage.MaxTimeToReceive (Header: Mqoai.h.): page record, no signature printed */
/* ms895199 MSMQMessage.Priority (Header: Mqoai.h.): page record, no signature printed */
/* ms895200 MSMQMessage.PrivLevel (Header: Mqoai.h.): page record, no signature printed */
/* ms895203 MSMQMessage.ResponseQueueInfo (Header: Mqoai.h.): page record, no signature printed */
/* ms895204 MSMQMessage.Send (Header: Mqoai.h.): page record, no signature printed */
/* ms895207 MSMQMessage.SenderCertificate (Header: Mqoai.h.): page record, no signature printed */
/* ms895208 MSMQMessage.SenderId (Header: Mqoai.h.): page record, no signature printed */
/* ms895211 MSMQMessage.SenderIdType (Header: Mqoai.h.): page record, no signature printed */
/* ms895212 MSMQMessage.SentTime (Header: Mqoai.h.): page record, no signature printed */
/* ms895215 MSMQMessage.SourceMachineGuid (Header: Mqoai.h.): page record, no signature printed */
/* ms895217 MSMQMessage.Trace (Header: Mqoai.h.): page record, no signature printed */
/* ms895224 MSMQQueue.Access (Header: Mqoai.h.): page record, no signature printed */
/* ms895225 MSMQQueue.Close (Header: Mqoai.h.): print `HRESULT Close(void);` */
/* ms895228 MSMQQueue.EnableNotification (Header: Mqoai.h.): print `HRESULT EnableNotification(MSMQEvent* Event,VARIANT* Cursor,VARIANT* ReceiveTimeout);` */
/* ms895231 MSMQQueue.Handle (Header: Mqoai.h.): page record, no signature printed */
/* ms895276 MSMQQueue.IsOpen (Header: Mqoai.h.): page record, no signature printed */
/* ms895279 MSMQQueue.Peek (Header: Mqoai.h.): print `HRESULT Peek(VARIANT* WantDestinationQueue,VARIANT* WantBody,VARIANT* ReceiveTimeout,MSMQMessage** ppmsg);` */
/* ms895281 MSMQQueue.PeekCurrent (Header: Mqoai.h.): print `HRESULT PeekCurrent(VARIANT* WantDestinationQueue,VARIANT* WantBody,VARIANT* ReceiveTimeout,MSMQMessage** ppmsg);` */
/* ms895284 MSMQQueue.PeekNext (Header: Mqoai.h.): print `HRESULT PeekNext(VARIANT* WantDestinationQueue,VARIANT* WantBody,VARIANT* ReceiveTimeout,MSMQMessage** ppmsg);` */
/* ms895286 MSMQQueue.QueueInfo (Header: Mqoai.h.): page record, no signature printed */
/* ms895287 MSMQQueue.Receive (Header: Mqoai.h.): print `HRESULT Receive(VARIANT* Transaction,VARIANT* WantDestinationQueue,VARIANT* WantBody,VARIANT* ReceiveTimeout,MSMQMessage** ppmsg);` */
/* ms895289 MSMQQueue.ReceiveCurrent (Header: Mqoai.h.): print `HRESULT ReceiveCurrent(VARIANT* Transaction,VARIANT* WantDestinationQueue,VARIANT* WantBody,VARIANT* ReceiveTimeout,MSMQMessage** ppmsg);` */
/* ms895614 MSMQQueue.Reset (Header: Mqoai.h.): print `HRESULT Reset(void);` */
/* ms895653 MSMQQueue.ShareMode (Header: Mqoai.h.): page record, no signature printed */
/* ms895234 MSMQQueueInfo.Authenticate (Header: Mqoai.h.): page record, no signature printed */
/* ms895236 MSMQQueueInfo.BasePriority (Header: Mqoai.h.): page record, no signature printed */
/* ms895238 MSMQQueueInfo.Create (Header: Mqoai.h.): print `HRESULT Create(VARIANT* IsTransactional,VARIANT* IsWorldReadable);` */
/* ms895240 MSMQQueueInfo.CreateTime (Header: Mqoai.h.): page record, no signature printed */
/* ms895241 MSMQQueueInfo.Delete (Header: Mqoai.h.): page record, no signature printed */
/* ms895244 MSMQQueueInfo.FormatName (Header: Mqoai.h.): page record, no signature printed */
/* ms895245 MSMQQueueInfo.IsTransactional (Header: Mqoai.h.): page record, no signature printed */
/* ms895248 MSMQQueueInfo.IsWorldReadable (Header: Mqoai.h.): page record, no signature printed */
/* ms895249 MSMQQueueInfo.Journal (Header: Mqoai.h.): page record, no signature printed */
/* ms895252 MSMQQueueInfo.JournalQuota (Header: Mqoai.h.): page record, no signature printed */
/* ms895253 MSMQQueueInfo.Label (Header: Mqoai.h.): page record, no signature printed */
/* ms895256 MSMQQueueInfo.ModifyTime (Header: Mqoai.h.): page record, no signature printed */
/* ms895257 MSMQQueueInfo.Open (Header: Mqoai.h.): print `HRESULT Open(longAccess,longShareMode,MSMQQueue** ppq);` */
/* ms895260 MSMQQueueInfo.PathName (Header: Mqoai.h.): page record, no signature printed */
/* ms895261 MSMQQueueInfo.PrivLevel (Header: Mqoai.h.): page record, no signature printed */
/* ms895264 MSMQQueueInfo.QueueGuid (Header: Mqoai.h.): page record, no signature printed */
/* ms895266 MSMQQueueInfo.Quota (Header: Mqoai.h.): page record, no signature printed */
/* ms895268 MSMQQueueInfo.Refresh (Header: Mqoai.h.): print `HRESULT Refresh(void);` */
/* ms895272 MSMQQueueInfo.ServiceTypeGuid (Header: Mqoai.h.): page record, no signature printed */
/* ms895275 MSMQQueueInfo.Update (Header: Mqoai.h.): print `HRESULT Update(void);` */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_MQOAI_H */
