/*
 * Nclientview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_NCLIENTVIEW_HPP
#define AKARI_NCLIENTVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

/* ms920086 WidgetId (page print, compiled):
 *   enum WidgetId { widInvalid = -1, widClose, widMaxRestore, widMin, widOk, widHelp }; */
enum WidgetId {
    widInvalid = -1,
    widClose,
    widMaxRestore,
    widMin,
    widOk,
    widHelp
};

#endif /* __cplusplus */

#endif /* AKARI_NCLIENTVIEW_HPP */
