/* WinCE development API surface.
 * Original declarations written from a survey of CE 4.2, 5.0, and 6.0
 * public interface facts (names, types, layouts, constants, exports).
 * Not an OS, BSP, OAK, or Platform Builder component, and not a copy
 * of upstream source.
 */

#ifndef WCE_OLEAUTO_H
#define WCE_OLEAUTO_H
#include "windef.h"
#include "winnt.h"
#include "wtypes.h"
#include "wceunk.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tagNUMPARSE { INT cDig; ULONG dwInFlags; ULONG dwOutFlags; INT cchUsed; INT nBaseShift; INT nPwr10; } NUMPARSE, *PNUMPARSE, *LPNUMPARSE;
typedef struct tagUDATE { SYSTEMTIME st; USHORT wDayOfYear; } UDATE, *PUDATE, *LPUDATE;

WCE_IMPORT HRESULT WINAPI VarUI1FromI2(SHORT sIn, BYTE * pbOut) WCE_LINK(VarUI1FromI2);
WCE_IMPORT HRESULT WINAPI VarUI1FromI4(LONG lIn, BYTE * pbOut) WCE_LINK(VarUI1FromI4);
WCE_IMPORT HRESULT WINAPI VarUI1FromR4(FLOAT fltIn, BYTE * pbOut) WCE_LINK(VarUI1FromR4);
WCE_IMPORT HRESULT WINAPI VarUI1FromR8(DOUBLE dblIn, BYTE * pbOut) WCE_LINK(VarUI1FromR8);
WCE_IMPORT HRESULT WINAPI VarUI1FromCy(CY cyIn, BYTE * pbOut) WCE_LINK(VarUI1FromCy);
WCE_IMPORT HRESULT WINAPI VarUI1FromI1(CHAR cIn, BYTE *pbOut) WCE_LINK(VarUI1FromI1);
WCE_IMPORT HRESULT WINAPI VarUI1FromUI2(USHORT uiIn, BYTE *pbOut) WCE_LINK(VarUI1FromUI2);
WCE_IMPORT HRESULT WINAPI VarUI1FromUI4(ULONG ulIn, BYTE *pbOut) WCE_LINK(VarUI1FromUI4);
WCE_IMPORT HRESULT WINAPI VarUI1FromDec(DECIMAL *pdecIn, BYTE *pbOut) WCE_LINK(VarUI1FromDec);
WCE_IMPORT HRESULT WINAPI VarI2FromUI1(BYTE bIn, SHORT * psOut) WCE_LINK(VarI2FromUI1);
WCE_IMPORT HRESULT WINAPI VarI2FromI4(LONG lIn, SHORT * psOut) WCE_LINK(VarI2FromI4);
WCE_IMPORT HRESULT WINAPI VarI2FromR4(FLOAT fltIn, SHORT * psOut) WCE_LINK(VarI2FromR4);
WCE_IMPORT HRESULT WINAPI VarI2FromR8(DOUBLE dblIn, SHORT * psOut) WCE_LINK(VarI2FromR8);
WCE_IMPORT HRESULT WINAPI VarI2FromCy(CY cyIn, SHORT * psOut) WCE_LINK(VarI2FromCy);
WCE_IMPORT HRESULT WINAPI VarI2FromI1(CHAR cIn, SHORT *psOut) WCE_LINK(VarI2FromI1);
WCE_IMPORT HRESULT WINAPI VarI2FromUI2(USHORT uiIn, SHORT *psOut) WCE_LINK(VarI2FromUI2);
WCE_IMPORT HRESULT WINAPI VarI2FromUI4(ULONG ulIn, SHORT *psOut) WCE_LINK(VarI2FromUI4);
WCE_IMPORT HRESULT WINAPI VarI2FromDec(DECIMAL *pdecIn, SHORT *psOut) WCE_LINK(VarI2FromDec);
WCE_IMPORT HRESULT WINAPI VarI4FromUI1(BYTE bIn, LONG * plOut) WCE_LINK(VarI4FromUI1);
WCE_IMPORT HRESULT WINAPI VarI4FromI2(SHORT sIn, LONG * plOut) WCE_LINK(VarI4FromI2);
WCE_IMPORT HRESULT WINAPI VarI4FromR4(FLOAT fltIn, LONG * plOut) WCE_LINK(VarI4FromR4);
WCE_IMPORT HRESULT WINAPI VarI4FromR8(DOUBLE dblIn, LONG * plOut) WCE_LINK(VarI4FromR8);
WCE_IMPORT HRESULT WINAPI VarI4FromCy(CY cyIn, LONG * plOut) WCE_LINK(VarI4FromCy);
WCE_IMPORT HRESULT WINAPI VarI4FromI1(CHAR cIn, LONG *plOut) WCE_LINK(VarI4FromI1);
WCE_IMPORT HRESULT WINAPI VarI4FromUI2(USHORT uiIn, LONG *plOut) WCE_LINK(VarI4FromUI2);
WCE_IMPORT HRESULT WINAPI VarI4FromUI4(ULONG ulIn, LONG *plOut) WCE_LINK(VarI4FromUI4);
WCE_IMPORT HRESULT WINAPI VarI4FromDec(DECIMAL *pdecIn, LONG *plOut) WCE_LINK(VarI4FromDec);
WCE_IMPORT HRESULT WINAPI VarI4FromInt(INT intIn, LONG *plOut) WCE_LINK(VarI4FromInt);
WCE_IMPORT HRESULT WINAPI VarR4FromUI1(BYTE bIn, FLOAT * pfltOut) WCE_LINK(VarR4FromUI1);
WCE_IMPORT HRESULT WINAPI VarR4FromI2(SHORT sIn, FLOAT * pfltOut) WCE_LINK(VarR4FromI2);
WCE_IMPORT HRESULT WINAPI VarR4FromI4(LONG lIn, FLOAT * pfltOut) WCE_LINK(VarR4FromI4);
WCE_IMPORT HRESULT WINAPI VarR4FromR8(DOUBLE dblIn, FLOAT * pfltOut) WCE_LINK(VarR4FromR8);
WCE_IMPORT HRESULT WINAPI VarR4FromCy(CY cyIn, FLOAT * pfltOut) WCE_LINK(VarR4FromCy);
WCE_IMPORT HRESULT WINAPI VarR4FromI1(CHAR cIn, FLOAT *pfltOut) WCE_LINK(VarR4FromI1);
WCE_IMPORT HRESULT WINAPI VarR4FromUI2(USHORT uiIn, FLOAT *pfltOut) WCE_LINK(VarR4FromUI2);
WCE_IMPORT HRESULT WINAPI VarR4FromUI4(ULONG ulIn, FLOAT *pfltOut) WCE_LINK(VarR4FromUI4);
WCE_IMPORT HRESULT WINAPI VarR4FromDec(DECIMAL *pdecIn, FLOAT *pfltOut) WCE_LINK(VarR4FromDec);
WCE_IMPORT HRESULT WINAPI VarR8FromUI1(BYTE bIn, DOUBLE * pdblOut) WCE_LINK(VarR8FromUI1);
WCE_IMPORT HRESULT WINAPI VarR8FromI2(SHORT sIn, DOUBLE * pdblOut) WCE_LINK(VarR8FromI2);
WCE_IMPORT HRESULT WINAPI VarR8FromI4(LONG lIn, DOUBLE * pdblOut) WCE_LINK(VarR8FromI4);
WCE_IMPORT HRESULT WINAPI VarR8FromR4(FLOAT fltIn, DOUBLE * pdblOut) WCE_LINK(VarR8FromR4);
WCE_IMPORT HRESULT WINAPI VarR8FromCy(CY cyIn, DOUBLE * pdblOut) WCE_LINK(VarR8FromCy);
WCE_IMPORT HRESULT WINAPI VarR8FromI1(CHAR cIn, DOUBLE *pdblOut) WCE_LINK(VarR8FromI1);
WCE_IMPORT HRESULT WINAPI VarR8FromUI2(USHORT uiIn, DOUBLE *pdblOut) WCE_LINK(VarR8FromUI2);
WCE_IMPORT HRESULT WINAPI VarR8FromUI4(ULONG ulIn, DOUBLE *pdblOut) WCE_LINK(VarR8FromUI4);
WCE_IMPORT HRESULT WINAPI VarR8FromDec(DECIMAL *pdecIn, DOUBLE *pdblOut) WCE_LINK(VarR8FromDec);
WCE_IMPORT HRESULT WINAPI VarCyFromUI1(BYTE bIn, CY * pcyOut) WCE_LINK(VarCyFromUI1);
WCE_IMPORT HRESULT WINAPI VarCyFromI2(SHORT sIn, CY * pcyOut) WCE_LINK(VarCyFromI2);
WCE_IMPORT HRESULT WINAPI VarCyFromI4(LONG lIn, CY * pcyOut) WCE_LINK(VarCyFromI4);
WCE_IMPORT HRESULT WINAPI VarCyFromR4(FLOAT fltIn, CY * pcyOut) WCE_LINK(VarCyFromR4);
WCE_IMPORT HRESULT WINAPI VarCyFromR8(DOUBLE dblIn, CY * pcyOut) WCE_LINK(VarCyFromR8);
WCE_IMPORT HRESULT WINAPI VarCyFromI1(CHAR cIn, CY *pcyOut) WCE_LINK(VarCyFromI1);
WCE_IMPORT HRESULT WINAPI VarCyFromUI2(USHORT uiIn, CY *pcyOut) WCE_LINK(VarCyFromUI2);
WCE_IMPORT HRESULT WINAPI VarCyFromUI4(ULONG ulIn, CY *pcyOut) WCE_LINK(VarCyFromUI4);
WCE_IMPORT HRESULT WINAPI VarCyFromDec(DECIMAL *pdecIn, CY *pcyOut) WCE_LINK(VarCyFromDec);
WCE_IMPORT HRESULT WINAPI VarI1FromUI1(BYTE bIn, CHAR *pcOut) WCE_LINK(VarI1FromUI1);
WCE_IMPORT HRESULT WINAPI VarI1FromI2(SHORT uiIn, CHAR *pcOut) WCE_LINK(VarI1FromI2);
WCE_IMPORT HRESULT WINAPI VarI1FromI4(LONG lIn, CHAR *pcOut) WCE_LINK(VarI1FromI4);
WCE_IMPORT HRESULT WINAPI VarI1FromR4(FLOAT fltIn, CHAR *pcOut) WCE_LINK(VarI1FromR4);
WCE_IMPORT HRESULT WINAPI VarI1FromR8(DOUBLE dblIn, CHAR *pcOut) WCE_LINK(VarI1FromR8);
WCE_IMPORT HRESULT WINAPI VarI1FromCy(CY cyIn, CHAR *pcOut) WCE_LINK(VarI1FromCy);
WCE_IMPORT HRESULT WINAPI VarI1FromUI2(USHORT uiIn, CHAR *pcOut) WCE_LINK(VarI1FromUI2);
WCE_IMPORT HRESULT WINAPI VarI1FromUI4(ULONG ulIn, CHAR *pcOut) WCE_LINK(VarI1FromUI4);
WCE_IMPORT HRESULT WINAPI VarI1FromDec(DECIMAL *pdecIn, CHAR *pcOut) WCE_LINK(VarI1FromDec);
WCE_IMPORT HRESULT WINAPI VarUI2FromUI1(BYTE bIn, USHORT *puiOut) WCE_LINK(VarUI2FromUI1);
WCE_IMPORT HRESULT WINAPI VarUI2FromI2(SHORT uiIn, USHORT *puiOut) WCE_LINK(VarUI2FromI2);
WCE_IMPORT HRESULT WINAPI VarUI2FromI4(LONG lIn, USHORT *puiOut) WCE_LINK(VarUI2FromI4);
WCE_IMPORT HRESULT WINAPI VarUI2FromR4(FLOAT fltIn, USHORT *puiOut) WCE_LINK(VarUI2FromR4);
WCE_IMPORT HRESULT WINAPI VarUI2FromR8(DOUBLE dblIn, USHORT *puiOut) WCE_LINK(VarUI2FromR8);
WCE_IMPORT HRESULT WINAPI VarUI2FromCy(CY cyIn, USHORT *puiOut) WCE_LINK(VarUI2FromCy);
WCE_IMPORT HRESULT WINAPI VarUI2FromI1(CHAR cIn, USHORT *puiOut) WCE_LINK(VarUI2FromI1);
WCE_IMPORT HRESULT WINAPI VarUI2FromUI4(ULONG ulIn, USHORT *puiOut) WCE_LINK(VarUI2FromUI4);
WCE_IMPORT HRESULT WINAPI VarUI2FromDec(DECIMAL *pdecIn, USHORT *puiOut) WCE_LINK(VarUI2FromDec);
WCE_IMPORT HRESULT WINAPI VarUI4FromUI1(BYTE bIn, ULONG *pulOut) WCE_LINK(VarUI4FromUI1);
WCE_IMPORT HRESULT WINAPI VarUI4FromI2(SHORT uiIn, ULONG *pulOut) WCE_LINK(VarUI4FromI2);
WCE_IMPORT HRESULT WINAPI VarUI4FromI4(LONG lIn, ULONG *pulOut) WCE_LINK(VarUI4FromI4);
WCE_IMPORT HRESULT WINAPI VarUI4FromR4(FLOAT fltIn, ULONG *pulOut) WCE_LINK(VarUI4FromR4);
WCE_IMPORT HRESULT WINAPI VarUI4FromR8(DOUBLE dblIn, ULONG *pulOut) WCE_LINK(VarUI4FromR8);
WCE_IMPORT HRESULT WINAPI VarUI4FromCy(CY cyIn, ULONG *pulOut) WCE_LINK(VarUI4FromCy);
WCE_IMPORT HRESULT WINAPI VarUI4FromI1(CHAR cIn, ULONG *pulOut) WCE_LINK(VarUI4FromI1);
WCE_IMPORT HRESULT WINAPI VarUI4FromUI2(USHORT uiIn, ULONG *pulOut) WCE_LINK(VarUI4FromUI2);
WCE_IMPORT HRESULT WINAPI VarUI4FromDec(DECIMAL *pdecIn, ULONG *pulOut) WCE_LINK(VarUI4FromDec);
WCE_IMPORT HRESULT WINAPI VarDecFromUI1(BYTE bIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromUI1);
WCE_IMPORT HRESULT WINAPI VarDecFromI2(SHORT uiIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromI2);
WCE_IMPORT HRESULT WINAPI VarDecFromI4(LONG lIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromI4);
WCE_IMPORT HRESULT WINAPI VarDecFromR4(FLOAT fltIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromR4);
WCE_IMPORT HRESULT WINAPI VarDecFromR8(DOUBLE dblIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromR8);
WCE_IMPORT HRESULT WINAPI VarDecFromCy(CY cyIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromCy);
WCE_IMPORT HRESULT WINAPI VarDecFromI1(CHAR cIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromI1);
WCE_IMPORT HRESULT WINAPI VarDecFromUI2(USHORT uiIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromUI2);
WCE_IMPORT HRESULT WINAPI VarDecFromUI4(ULONG ulIn, DECIMAL *pdecOut) WCE_LINK(VarDecFromUI4);
WCE_IMPORT HRESULT WINAPI GetAltMonthNames(LCID lcid, LPOLESTR * * prgp) WCE_LINK(GetAltMonthNames);
WCE_IMPORT HRESULT WINAPI QueryPathOfRegTypeLib(REFGUID guid, USHORT wMaj, USHORT wMin, LCID lcid, LPBSTR lpbstrPathName) WCE_LINK(QueryPathOfRegTypeLib);
WCE_IMPORT HRESULT WINAPI RevokeActiveObject(DWORD dwRegister, void * pvReserved) WCE_LINK(RevokeActiveObject);

#ifdef __cplusplus
}
#endif
#endif

