/*
 * Olectl.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-olectl.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_OLECTL_H
#define AKARI_OLECTL_H

#include <Windows.h>
#include "Objbase.h"   /* STDAPI, LPCOLESTR, LPCLSID, LPUNKNOWN, LCID (the
                         * types the OLE control entry points are printed with) */

#ifdef __cplusplus
extern "C" {
#endif

/*  *
 * HELD in part: OleCreateFontIndirect takes an LPFONTDESC, and neither
 * LPFONTDESC nor FONTDESC has a defining page anywhere in the
 * harvested official corpus (48,849-page scan negative), so that
 * prototype stays a record.  OleCreatePropertyFrame's parameter types
 * are all carried, so it is declared. */

/* ------------------------------------------------------------------
 * Book surface: m107-olectl (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* _wcesdk_oa96_OleCreateFontIndirect OleCreateFontIndirect: print `STDAPI OleCreateFontIndirect( LPFONTDESC lpFontDesc , REFIID riid , LPVOID FAR * lplpvObj );` */
/* (record-only: parameter or return type unpublished) */
/* _wcesdk_oa96_OleCreatePropertyFrame OleCreatePropertyFrame: print `STDAPI OleCreatePropertyFrame( HWND hwndOwner , UINT x , UINT y , LPCOLESTR lpszCaption , ULONG cObjects , LPUNKNOWN FAR * ppUnk , ULONG cPages , LPCLSID pPageClsID , LCID lcid , DWORD dwReserved , LPVOID pvReserved );` */
AKARI_CE_IMPORT HRESULT OleCreatePropertyFrame   /* STDAPI -> HRESULT (Objbase.h STDAPI policy) */(HWND hwndOwner, UINT x, UINT y, LPCOLESTR lpszCaption, ULONG cObjects, LPUNKNOWN FAR* ppUnk, ULONG cPages, LPCLSID pPageClsID, LCID lcid, DWORD dwReserved, LPVOID pvReserved)
    AKARI_CE_NAME(OleCreatePropertyFrame);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_OLECTL_H */
