/*
 * Pcommctr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): m107-pcommctr.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PCOMMCTR_H
#define AKARI_PCOMMCTR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/*  *
 * Two spellings are documented for this surface: DPA_FastGetPtr and
 * DPA_GetPtr name `Pcommctr.h.` in their Requirements rows, while the
 * DPA structure itself names `Pcommctrl.h.` (see include/Pcommctrl.h,
 * where it is compiled).  This file is the record for the Pcommctr.h
 * spelling.
 * HELD (nothing compiled): DPA_GetPtr takes an HDPA and
 * DPA_FastGetPtr expands through DPA_GetPtrPtr; neither identifier
 * has a defining page anywhere in the harvested official corpus, so
 * both prints stay records. */

/* ------------------------------------------------------------------
 * Book surface: m107-pcommctr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms902692 DPA_FastGetPtr: print `#define DPA_FastGetPtr(hdpa, i) (DPA_GetPtrPtr(hdpa)[i])` -- recorded verbatim (no compiled prototype) */
/* ms902800 DPA_GetPtr: print `WINCOMMCTRLAPI LPVOID WINAPI DPA_GetPtr( HDPA hdpa, int i );` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PCOMMCTR_H */
