/*
 * Progressview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_PROGRESSVIEW_HPP
#define AKARI_PROGRESSVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class ProgressBarView_t {
public:
    /* ms919346 ProgressBarView_t::Draw: print `static void Draw(HWND hwnd, HDC hdcIn, DWORD dwStyle, int iLow, int iHigh, int iPos, COLORREF clrHighlight);` */
    static void Draw(HWND hwnd, HDC hdcIn, DWORD dwStyle, int iLow, int iHigh, int iPos, COLORREF clrHighlight);
};

#endif /* __cplusplus */

#endif /* AKARI_PROGRESSVIEW_HPP */
