/*
 * Rebarview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_REBARVIEW_HPP
#define AKARI_REBARVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class RebarView_t {
public:
    /* ms919541 RebarView_t::DrawGripper: print `static BOOL DrawGripper(HDC hdc, LPRECT lprc);` */
    static BOOL DrawGripper(HDC hdc, LPRECT lprc);
    /* ms919545 RebarView_t::InitSpacingValues: print `static void InitSpacingValues(int* pstartspace, int* pgripperwidth, int* pinterspace);` */
    static void InitSpacingValues(int* pstartspace, int* pgripperwidth, int* pinterspace);
};

#endif /* __cplusplus */

#endif /* AKARI_REBARVIEW_HPP */
