/*
 * Scrollview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_SCROLLVIEW_HPP
#define AKARI_SCROLLVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

/* ms919595 SCROLL_STATE (page print, compiled):
 *   enum SCROLL_STATE { SCROLL_NO_PRESS, SCROLL_UP_PRESS, SCROLL_DN_PRESS, SCROLL_PGUP_PRESS, SCROLL_PGDN_PRESS, SCROLL_SLIDE_PRESS, SCROLL_UNAVAIL, SCROLL_NEXT_FREE }; */
enum SCROLL_STATE {
    SCROLL_NO_PRESS,
    SCROLL_UP_PRESS,
    SCROLL_DN_PRESS,
    SCROLL_PGUP_PRESS,
    SCROLL_PGDN_PRESS,
    SCROLL_SLIDE_PRESS,
    SCROLL_UNAVAIL,
    SCROLL_NEXT_FREE
};

class ScrollBarView_t {
public:
    /* ms919574 ScrollBarView_t::DrawScrollBar: print `static void DrawScrollBar(HDC hdc, HWND hwnd, BOOL fVert, SCROLL_STATE State, UINT32 WindowState, UINT32 WindowStyle, ScrollBarInfoInternal* psbii);`
     *   -- HELD: parameter type `SCROLL_STATE State` has no defining
     *   page in the harvested official corpus */
    /* ms919579 ScrollBarView_t::GetScrollRects: print `static int GetScrollRects(HWND hwnd, RECT* prcBounds, RECT* prcUp, RECT* prcDn, RECT* prcThumb, BOOL fVert, ScrollBarInfoInternal* psbii);`
     *   -- HELD: parameter type `ScrollBarInfoInternal* psbii` has no defining
     *   page in the harvested official corpus */
    /* ms919582 ScrollBarView_t::GetThumbPixel: print `static LONG GetThumbPixel(HWND hwnd, BOOL fVert, ScrollBarInfoInternal* psbii);`
     *   -- HELD: parameter type `ScrollBarInfoInternal* psbii` has no defining
     *   page in the harvested official corpus */
    /* ms919587 ScrollBarView_t::ScrollHitTest: print `static SCROLL_STATE ScrollHitTest(HWND hwnd, POINT pt, BOOL fVert, ScrollBarInfoInternal* psbii);`
     *   -- HELD: parameter type `ScrollBarInfoInternal* psbii` has no defining
     *   page in the harvested official corpus */
    /* ms919591 ScrollBarView_t::TrackThumb: print `static void TrackThumb(HWND hwnd, HDC hdc, POINT pt, BOOL fVert, ScrollBarInfoInternal* psbii);`
     *   -- HELD: parameter type `ScrollBarInfoInternal* psbii` has no defining
     *   page in the harvested official corpus */
};

/* ms919566 ScrollBarInfoInternal (Header: Scrollview.hpp.): no class-member
 * print on the page (record only) */

/* ms932603 ScrollBarInfoInternal: page print
 * struct ScrollBarInfoInternal {SCROLLINFO si;BOOL bInSetSBInfo;int nThumbPos;SCROLL_STATEdwState;UINT nTrackStart;UINT fnBar;UINT idTimer;};
 * (Windows CE .NET 4.0 and later.) */
struct ScrollBarInfoInternal {
    SCROLLINFO si;
    BOOL bInSetSBInfo;
    int nThumbPos;
    SCROLL_STATE dwState;
    UINT nTrackStart;
    UINT fnBar;
    UINT idTimer;
};

#endif /* __cplusplus */

#endif /* AKARI_SCROLLVIEW_HPP */
