/*
 * Statctlview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_STATCTLVIEW_HPP
#define AKARI_STATCTLVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

/* ms919644 StaticControlType (page print, compiled):
 *   enum StaticControlType { sctLeft = SS_LEFT, sctCenter = SS_CENTER, sctRight = SS_RIGHT, sctIcon = SS_ICON, sctLeftNoWordWrap = SS_LEFTNOWORDWRAP, sctBitmap = SS_BITMAP, sctIconCenter = SS_ICON, sctBitmapCenter = SS_BITMAP }; */
enum StaticControlType {
    sctLeft = SS_LEFT,
    sctCenter = SS_CENTER,
    sctRight = SS_RIGHT,
    sctIcon = SS_ICON,
    sctLeftNoWordWrap = SS_LEFTNOWORDWRAP,
    sctBitmap = SS_BITMAP,
    sctIconCenter = SS_ICON,
    sctBitmapCenter = SS_BITMAP
};

class StaticControlView_t {
public:
    /* ms919648 StaticControlView_t::DrawStaticImage: print `static void DrawStaticImage(HWND hwnd, enum StaticControlType sct, HDC hdc, HBRUSH hbrBk, HANDLE hImage);`
     *   -- HELD: parameter type `enum StaticControlType sct` has no defining
     *   page in the harvested official corpus */
    /* ms919651 StaticControlView_t::DrawStaticText: print `static void DrawStaticText(HWND hwnd, unsigned int Style, enum StaticControlType sct, HDC hdc, HBRUSH hbrBk);`
     *   -- HELD: parameter type `enum StaticControlType sct` has no defining
     *   page in the harvested official corpus */
    /* ms919652 StaticControlView_t::ResizeRectToImage: print `static bool ResizeRectToImage(HWND hwnd, unsigned int Style, enum StaticControlType sct, HANDLE hImage, RECT* prc);`
     *   -- HELD: parameter type `enum StaticControlType sct` has no defining
     *   page in the harvested official corpus */
};

#endif /* __cplusplus */

#endif /* AKARI_STATCTLVIEW_HPP */
