/*
 * Tabview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_TABVIEW_HPP
#define AKARI_TABVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class TabView_t {
public:
    /* ms919662 TabView_t::Draw: print `static void Draw(HWND hwnd, HWND hwndParent, HDC hdc, RECT* prcClient, DWORD style, DWORD dwStyleEx, UINT flags, int tmHeight, int cItems, HIMAGELIST himl, HDPA hdpa, int cbExtra, int iSel, int iNewSel, int cxTabs, int iFirstVisible, int iLastVisible, int iLastTopRow);`
     *   -- HELD: parameter type `HDPA hdpa` has no defining
     *   page in the harvested official corpus */
};

#endif /* __cplusplus */

#endif /* AKARI_TABVIEW_HPP */
