/*
 * Toolbarview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_TOOLBARVIEW_HPP
#define AKARI_TOOLBARVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

/* ms905061 BitmapType (page print, compiled):
 *   enum BitmapType { btStdSmallColor, btStdSmallMono, btViewSmallColor, btViewSmallMono, btClose, btOk }; */
enum BitmapType {
    btStdSmallColor,
    btStdSmallMono,
    btViewSmallColor,
    btViewSmallMono,
    btClose,
    btOk
};

class ToolBarView_t {
public:
    /* ms919671 ToolBarView_t::CalcOffset: print `static void CalcOffset(int* pxOffset, int* pyOffset);` */
    static void CalcOffset(int* pxOffset, int* pyOffset);
    /* ms919676 ToolBarView_t::DrawButtonBorder: print `static void DrawButtonBorder(HDC hdc, RECT* prc, bool bPushed, DWORD style);` */
    static void DrawButtonBorder(HDC hdc, RECT* prc, bool bPushed, DWORD style);
    /* ms919678 ToolBarView_t::DrawDropdownArrow: print `static void DrawDropdownArrow(HDC hdc, int x, int y, int dx, int dy, int cxEdge, int cyEdge, int cyBorder, COLORREF clrBtnFace, int cxDropdownArrow, int yOffset);` */
    static void DrawDropdownArrow(HDC hdc, int x, int y, int dx, int dy, int cxEdge, int cyEdge, int cyBorder, COLORREF clrBtnFace, int cxDropdownArrow, int yOffset);
    /* ms919682 ToolBarView_t::FaceRect: print `static void FaceRect(RECT* prcButton, int cxEdge, int cyEdge);` */
    static void FaceRect(RECT* prcButton, int cxEdge, int cyEdge);
    /* ms919685 ToolBarView_t::InitializeButtonSlopValue: print `static void InitializeButtonSlopValue(int* pxSlop, int* pySlop);` */
    static void InitializeButtonSlopValue(int* pxSlop, int* pySlop);
    /* ms920018 ToolBarView_t::LoadSystemBitmap: print `static HBITMAP LoadSystemBitmap(enum BitmapType bt);`
     *   -- HELD: parameter type `enum BitmapType bt` has no defining
     *   page in the harvested official corpus */
};

#endif /* __cplusplus */

#endif /* AKARI_TOOLBARVIEW_HPP */
