/*
 * Trackbarview.hpp -- Windows CE C++ class surface (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per member).  Every member below is the page's own
 * print; the verbatim print is kept in the member's comment.
 * Generated by tools/gen-class-hpp.py.
 */

#ifndef AKARI_TRACKBARVIEW_HPP
#define AKARI_TRACKBARVIEW_HPP

#include <Windows.h>

#ifdef __cplusplus
#ifndef _INC_WINDOWS_CE_SDK_DECOR_EMPTY
#define _INC_WINDOWS_CE_SDK_DECOR_EMPTY  1
#ifndef WINGDIAPI
#define WINGDIAPI
#endif
#ifndef INGDIAPI
#define INGDIAPI
#endif
#ifndef WINUSERAPI
#define WINUSERAPI
#endif
#endif

class TrackBarView_t {
public:
    /* ms920038 TrackBarView_t::DrawChannel: print `static void DrawChannel(HDC hdc, DWORD style, BOOL bSelection, LONG lSelStart, LONG lSelEnd, LONG lLogMin, LONG lLogMax, LONG iSizePhys, int left, LPRECT lprc);` */
    static void DrawChannel(HDC hdc, DWORD style, BOOL bSelection, LONG lSelStart, LONG lSelEnd, LONG lLogMin, LONG lLogMax, LONG iSizePhys, int left, LPRECT lprc);
    /* ms920042 TrackBarView_t::DrawFocus: print `static void DrawFocus(HWND hwnd, HDC hdc);` */
    static void DrawFocus(HWND hwnd, HDC hdc);
    /* ms920044 TrackBarView_t::DrawThumb: print `static void DrawThumb(HWND hwnd, HDC hdc, DWORD style, int iThumbHeight, int iThumbWidth, LPRECT lprc, BOOL fSelected);` */
    static void DrawThumb(HWND hwnd, HDC hdc, DWORD style, int iThumbHeight, int iThumbWidth, LPRECT lprc, BOOL fSelected);
    /* ms920046 TrackBarView_t::DrawTics: print `static void DrawTics(HDC hdc, DWORD style, RECT* prc, PDWORD pTics, int nTics, int ticFreq, LONG lSelStart, LONG lSelEnd, LONG lLogMin, LONG lLogMax, LONG iSizePhys, bool bDrawSelectionTriangles);` */
    static void DrawTics(HDC hdc, DWORD style, RECT* prc, PDWORD pTics, int nTics, int ticFreq, LONG lSelStart, LONG lSelEnd, LONG lLogMin, LONG lLogMax, LONG iSizePhys, bool bDrawSelectionTriangles);
};

#endif /* __cplusplus */

#endif /* AKARI_TRACKBARVIEW_HPP */
