/* Akari WinCE Development API Surface
 * Independently authored declarations for linking Windows CE 6.0 programs.
 * This is an API surface only: not an OS, BSP, OAK, SDK component, or
 * Platform Builder redistribution, and not a copy of upstream source.
 * CE calling convention: stdcall is cdecl, and DLL export names are
 * undecorated. TCHAR is a 16-bit WCHAR. Layouts that differ from desktop
 * Win32 (CRITICAL_SECTION, WIN32_FIND_DATAW, BY_HANDLE_FILE_INFORMATION,
 * OVERLAPPED) follow the CE 6.0 ABI.
 */

#ifndef AKARI_WINBASE_H
#define AKARI_WINBASE_H
#include "windef.h"
#include "winnt.h"

#ifdef __cplusplus
extern "C" {
#endif

#define INVALID_HANDLE_VALUE ((HANDLE)(LONG_PTR)-1)
#define INVALID_FILE_SIZE ((DWORD)0xFFFFFFFF)
#define INVALID_SET_FILE_POINTER ((DWORD)-1)
#define TLS_OUT_OF_INDEXES ((DWORD)0xFFFFFFFF)
#define STILL_ACTIVE 259

typedef struct _FILETIME {
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
} FILETIME, *PFILETIME, *LPFILETIME;

typedef struct _SYSTEMTIME {
    WORD wYear;
    WORD wMonth;
    WORD wDayOfWeek;
    WORD wDay;
    WORD wHour;
    WORD wMinute;
    WORD wSecond;
    WORD wMilliseconds;
} SYSTEMTIME, *PSYSTEMTIME, *LPSYSTEMTIME;

typedef struct _OVERLAPPED {
    DWORD Internal;
    DWORD InternalHigh;
    DWORD Offset;
    DWORD OffsetHigh;
    HANDLE hEvent;
} OVERLAPPED, *LPOVERLAPPED;

typedef struct _SECURITY_ATTRIBUTES {
    DWORD nLength;
    LPVOID lpSecurityDescriptor;
    BOOL bInheritHandle;
} SECURITY_ATTRIBUTES, *PSECURITY_ATTRIBUTES, *LPSECURITY_ATTRIBUTES;

typedef struct _PROCESS_INFORMATION {
    HANDLE hProcess;
    HANDLE hThread;
    DWORD dwProcessId;
    DWORD dwThreadId;
} PROCESS_INFORMATION, *PPROCESS_INFORMATION, *LPPROCESS_INFORMATION;

typedef struct _STARTUPINFOW {
    DWORD cb;
    LPWSTR lpReserved;
    LPWSTR lpDesktop;
    LPWSTR lpTitle;
    DWORD dwX;
    DWORD dwY;
    DWORD dwXSize;
    DWORD dwYSize;
    DWORD dwXCountChars;
    DWORD dwYCountChars;
    DWORD dwFillAttribute;
    DWORD dwFlags;
    WORD wShowWindow;
    WORD cbReserved2;
    LPBYTE lpReserved2;
    HANDLE hStdInput;
    HANDLE hStdOutput;
    HANDLE hStdError;
} STARTUPINFOW, *LPSTARTUPINFOW;
typedef STARTUPINFOW STARTUPINFO;
typedef LPSTARTUPINFOW LPSTARTUPINFO;

typedef struct _SYSTEM_INFO {
    union {
        DWORD dwOemId;
        struct {
            WORD wProcessorArchitecture;
            WORD wReserved;
        };
    };
    DWORD dwPageSize;
    LPVOID lpMinimumApplicationAddress;
    LPVOID lpMaximumApplicationAddress;
    DWORD dwActiveProcessorMask;
    DWORD dwNumberOfProcessors;
    DWORD dwProcessorType;
    DWORD dwAllocationGranularity;
    WORD wProcessorLevel;
    WORD wProcessorRevision;
} SYSTEM_INFO, *LPSYSTEM_INFO;

typedef struct _MEMORYSTATUS {
    DWORD dwLength;
    DWORD dwMemoryLoad;
    DWORD dwTotalPhys;
    DWORD dwAvailPhys;
    DWORD dwTotalPageFile;
    DWORD dwAvailPageFile;
    DWORD dwTotalVirtual;
    DWORD dwAvailVirtual;
} MEMORYSTATUS, *LPMEMORYSTATUS;

/* CE 6.0 find-data: dwOID replaces the desktop reserved/short-name tail. */
typedef struct _WIN32_FIND_DATAW {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime;
    FILETIME ftLastAccessTime;
    FILETIME ftLastWriteTime;
    DWORD nFileSizeHigh;
    DWORD nFileSizeLow;
    DWORD dwOID;
    WCHAR cFileName[MAX_PATH];
} WIN32_FIND_DATAW, *PWIN32_FIND_DATAW, *LPWIN32_FIND_DATAW;
typedef WIN32_FIND_DATAW WIN32_FIND_DATA;
typedef LPWIN32_FIND_DATAW LPWIN32_FIND_DATA;

/* CE critical section is not the desktop RTL_CRITICAL_SECTION. */
typedef struct CRITICAL_SECTION {
    unsigned int LockCount;
    HANDLE OwnerThread;
    HANDLE hCrit;
    DWORD needtrap;
    DWORD dwContentions;
} CRITICAL_SECTION, *LPCRITICAL_SECTION;

typedef struct _OSVERSIONINFOW {
    DWORD dwOSVersionInfoSize;
    DWORD dwMajorVersion;
    DWORD dwMinorVersion;
    DWORD dwBuildNumber;
    DWORD dwPlatformId;
    WCHAR szCSDVersion[128];
} OSVERSIONINFOW, *POSVERSIONINFOW, *LPOSVERSIONINFOW;
typedef OSVERSIONINFOW OSVERSIONINFO;
typedef LPOSVERSIONINFOW LPOSVERSIONINFO;

typedef struct _BY_HANDLE_FILE_INFORMATION {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime;
    FILETIME ftLastAccessTime;
    FILETIME ftLastWriteTime;
    DWORD dwVolumeSerialNumber;
    DWORD nFileSizeHigh;
    DWORD nFileSizeLow;
    DWORD nNumberOfLinks;
    DWORD nFileIndexHigh;
    DWORD nFileIndexLow;
    DWORD dwOID;
} BY_HANDLE_FILE_INFORMATION, *PBY_HANDLE_FILE_INFORMATION, *LPBY_HANDLE_FILE_INFORMATION;

typedef struct _WIN32_FILE_ATTRIBUTE_DATA {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime;
    FILETIME ftLastAccessTime;
    FILETIME ftLastWriteTime;
    DWORD nFileSizeHigh;
    DWORD nFileSizeLow;
} WIN32_FILE_ATTRIBUTE_DATA, *LPWIN32_FILE_ATTRIBUTE_DATA;

typedef DWORD (WINAPI *LPTHREAD_START_ROUTINE)(LPVOID lpThreadParameter);
typedef DWORD REGSAM;

#define VER_SUITE_ENTERPRISE 0x00000002
#define VER_SUITE_COMMUNICATIONS 0x00000008
#define MEM_RESET 0x80000
#define SECTION_EXTEND_SIZE 0x0010
#define PROCESSOR_ARCHITECTURE_UNKNOWN 0xFFFF
#define CREATE_NEW 1
#define PROCESSOR_PPC_601 601
#define PROCESSOR_PPC_603 603
#define PROCESSOR_PPC_620 620
#define HEAP_FREE_CHECKING_ENABLED 0x00000040
#define PAGE_NOCACHE 0x200
#define PAGE_EXECUTE 0x10
#define MEM_4MB_PAGES 0x80000000
#define LMEM_MODIFY 0x0080
#define THREAD_PRIORITY_ABOVE_IDLE 6
#define EXCEPTION_FLAG_UNHANDLED 0x80000000
#define EVENT_E_QUERYFIELD ((HRESULT)0x80040204L)
#define PROCESSOR_MIPS16_CORE 1
#define PROCESSOR_ARM_7TDMI 70001
#define THREAD_PRIORITY_LOWEST 5
#define SEMAPHORE_MODIFY_STATE 0x0002
#define STATUS_SEVERITY_ERROR 0x3
#define PROCESSOR_MIPSIV_CORE 3
#define EVENT_E_MISSING_EVENTCLASS ((HRESULT)0x8004020AL)
#define FILE_CREATE_PIPE_INSTANCE ( 0x0004 )
#define WRITE_OWNER (0x00080000L)
#define FILE_UNICODE_ON_DISK 0x00000004
#define PROCESSOR_HITACHI_SH3 10003
#define PROCESSOR_HITACHI_SH4 10005
#define FILE_ATTRIBUTE_HIDDEN 0x00000002
#define EVENT_E_NOT_ALL_REMOVED ((HRESULT)0x8004020BL)
#define PROCESSOR_ARCHITECTURE_ALPHA 2
#define LMEM_SHARE 0x0000
#define MEM_E_INVALID_ROOT ((HRESULT)0x80080009L)
#define STANDARD_RIGHTS_REQUIRED (0x000F0000L)
#define FILE_ATTRIBUTE_OFFLINE 0x00001000
#define SECTION_MAP_EXECUTE 0x0008
#define FILE_LIST_DIRECTORY ( 0x0001 )
#define EVENT_S_NOSUBSCRIBERS ((HRESULT)0x00040202L)
#define PROCESSOR_ALPHA_21064 21064
#define HEAP_MAXIMUM_TAG 0x0FFF
#define WAIT_FAILED 0xffffffffL
#define GENERIC_ALL (0x10000000L)
#define FILE_CASE_SENSITIVE_SEARCH 0x00000001
#define FILE_NOTIFY_CHANGE_SECURITY 0x00000100
#define MEM_DECOMMIT 0x4000
#define PROCESSOR_INTEL_PENTIUM 586
#define SECTION_MAP_WRITE 0x0002
#define PROCESSOR_INTEL_386 386
#define PAGE_WRITECOMBINE 0x400
#define READ_CONTROL (0x00020000L)
#define GENERIC_EXECUTE (0x20000000L)
#define PROCESS_TERMINATE (0x0001)
#define FILE_FLAG_SEQUENTIAL_SCAN 0x08000000
#define FORMAT_MESSAGE_MAX_WIDTH_MASK 0x000000FF
#define FILE_SHARE_READ 0x00000001
#define HEAP_GROWABLE 0x00000002
#define FILE_FLAG_WRITE_THROUGH 0x80000000
#define EVENT_E_COMPLUS_NOT_INSTALLED ((HRESULT)0x8004020CL)
#define HEAP_NO_SERIALIZE 0x00000001
#define FILE_ATTRIBUTE_ROMMODULE 0x00002000
#define DELETE (0x00010000L)
#define LMEM_VALID_FLAGS 0x0F72
#define MEM_MAPPED 0x40000
#define MAX_COMPUTERNAME_LENGTH 15
#define MEM_E_INVALID_LINK ((HRESULT)0x80080010L)
#define PROCESS_CREATE_PROCESS (0x0080)
#define PAGE_EXECUTE_READ 0x20
#define LMEM_INVALID_HANDLE 0x8000
#define OPEN_FOR_LOADER 6
#define GENERIC_READ (0x80000000L)
#define THREAD_PRIORITY_ABOVE_NORMAL 2
#define PAGE_GUARD 0x100
#define FILE_ACTION_MODIFIED 0x00000003
#define LMEM_NOT_BANKED 0x0000
#define FILE_NOTIFY_CHANGE_FILE_NAME 0x00000001
#define FILE_ATTRIBUTE_REPARSE_POINT 0x00000400
#define FORMAT_MESSAGE_IGNORE_INSERTS 0x00000200
#define SPECIFIC_RIGHTS_ALL (0x0000FFFFL)
#define EXCEPTION_FLAG_IN_CALLBACK 0x40000000
#define PAGE_READONLY 0x02
#define FILE_FLAG_OVERLAPPED 0x40000000
#define TLS_FUNCALLOC 0
#define MEM_TOP_DOWN 0x100000
#define HEAP_CREATE_ENABLE_TRACING 0x00020000
#define FILE_EXECUTE ( 0x0020 )
#define HEAP_TAG_SHIFT 18
#define THREAD_IMPERSONATE (0x0100)
#define MEM_AUTO_COMMIT 0x200000
#define PROCESSOR_INTEL_PENTIUMII 686
#define FILE_ADD_SUBDIRECTORY ( 0x0004 )
#define EVENT_E_CANT_MODIFY_OR_DELETE_UNCONFIGURED_OBJECT ((HRESULT)0x8004020DL)
#define EXCEPTION_UNWINDING 0x2
#define PROCESSOR_HITACHI_SH4_CORE 2
#define PROCESSOR_X86_32BIT_CORE 1
#define EVENT_S_SOME_SUBSCRIBERS_FAILED ((HRESULT)0x00040200L)
#define HEAP_ZERO_MEMORY 0x00000008
#define FILE_ATTRIBUTE_TEMPORARY 0x00000100
#define THREAD_BASE_PRIORITY_IDLE -15
#define PROCESSOR_MOTOROLA_821 821
#define FILE_VOLUME_IS_COMPRESSED 0x00008000
#define STATUS_SEVERITY_WARNING 0x2
#define PROCESSOR_ARCHITECTURE_SHX 4
#define LMEM_DISCARDABLE 0x0F00
#define PAGE_EXECUTE_READWRITE 0x40
#define EVENT_MODIFY_STATE 0x0002
#define PROCESSOR_INTEL_486 486
#define THREAD_PRIORITY_NORMAL 3
#define FILE_NOTIFY_CHANGE_SIZE 0x00000008
#define FORMAT_MESSAGE_ARGUMENT_ARRAY 0x00002000
#define FILE_BEGIN 0
#define STATUS_SEVERITY_SUCCESS 0x0
#define EVENT_S_LAST 0x0004021FL
#define THREAD_PRIORITY_TIME_CRITICAL 0
#define PROCESSOR_ARM_V4I_CORE 2
#define STANDARD_RIGHTS_EXECUTE (READ_CONTROL)
#define WAIT_ABANDONED_0 0x00000080L
#define PROCESS_VM_WRITE (0x0020)
#define EXCEPTION_COLLIDED_UNWIND 0x40
#define FORMAT_MESSAGE_ALLOCATE_BUFFER 0x00000100
#define FILE_ATTRIBUTE_NORMAL 0x00000080
#define PROCESS_SET_QUOTA (0x0100)
#define THREAD_QUERY_INFORMATION (0x0040)
#define FILE_ATTRIBUTE_DIRECTORY 0x00000010
#define PROCESSOR_ARM_V4T_CORE 3
#define FILE_SUPPORTS_SPARSE_FILES 0x00000040
#define OPEN_EXISTING 3
#define FILE_WRITE_ATTRIBUTES ( 0x0100 )
#define FILE_ACTION_CHANGE_COMPLETED 0x00010000
#define GENERIC_WRITE (0x40000000L)
#define MEM_FREE 0x10000
#define SECTION_MAP_READ 0x0004
#define PROCESSOR_HITACHI_SH3E 10004
#define VER_SUITE_SMALLBUSINESS_RESTRICTED 0x00000020
#define CREATE_NEW_CONSOLE 0x00000010
#define FILE_ATTRIBUTE_SYSTEM 0x00000004
#define HEAP_TAIL_CHECKING_ENABLED 0x00000020
#define EVENT_E_INTERNALEXCEPTION ((HRESULT)0x80040205L)
#define SYNCHRONIZE (0x00100000L)
#define MAXIMUM_ALLOWED (0x02000000L)
#define PROCESS_CREATE_THREAD (0x0002)
#define PROCESSOR_FEATURE_FP 1
#define THREAD_PRIORITY_IDLE 7
#define THREAD_SET_THREAD_TOKEN (0x0080)
#define HEAP_GENERATE_EXCEPTIONS 0x00000004
#define PROCESS_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0xFFF)
#define LMEM_NOTIFY 0x0000
#define PROCESSOR_PPC_604 604
#define THREAD_PRIORITY_BELOW_NORMAL 4
#define FILE_WRITE_DATA ( 0x0002 )
#define TLS_MINIMUM_AVAILABLE 64
#define THREAD_BASE_PRIORITY_LOWRT 15
#define THREAD_SET_CONTEXT (0x0010)
#define VER_PLATFORM_WIN32_NT 2
#define EXCEPTION_DEBUG_EVENT 1
#define LMEM_NODISCARD 0x0020
#define FILE_ATTRIBUTE_INROM 0x00000040
#define EXCEPTION_MAXIMUM_PARAMETERS 15
#define PROCESSOR_ARM720 1824
#define FILE_NOTIFY_CHANGE_LAST_ACCESS 0x00000020
#define VER_WORKSTATION_NT 0x40000000
#define WAIT_ABANDONED 0x00000080L
#define CREATE_SUSPENDED 0x00000004
#define EXCEPTION_EXIT_UNWIND 0x4
#define MEM_E_INVALID_SIZE ((HRESULT)0x80080011L)
#define FILE_NOTIFY_CHANGE_CREATION 0x00000040
#define FILE_END 2
#define FILE_ATTRIBUTE_ROMSTATICREF 0x00001000
#define THREAD_GET_CONTEXT (0x0008)
#define FILE_PERSISTENT_ACLS 0x00000008
#define LMEM_NOCOMPACT 0x0010
#define MEM_RESERVE 0x2000
#define EVENT_E_CANT_MODIFY_OR_DELETE_CONFIGURED_OBJECT ((HRESULT)0x8004020EL)
#define FILE_CASE_PRESERVED_NAMES 0x00000002
#define FILE_VOLUME_QUOTAS 0x00000020
#define PAGE_WRITECOPY 0x08
#define EVENT_E_FIRST 0x80040200L
#define VER_SUITE_SMALLBUSINESS 0x00000001
#define HEAP_REALLOC_IN_PLACE_ONLY 0x00000010
#define PROCESSOR_PPC_403 403
#define FILE_ACTION_RENAMED_OLD_NAME 0x00000004
#define WAIT_OBJECT_0 0x00000000L
#define MEM_COMMIT 0x1000
#define FILE_ATTRIBUTE_READONLY 0x00000001
#define FILE_NOTIFY_CHANGE_CEGETINFO 0x80000000
#define FILE_NOTIFY_CHANGE_DIR_NAME 0x00000002
#define FILE_ACTION_RENAMED_NEW_NAME 0x00000005
#define FILE_FLAG_POSIX_SEMANTICS 0x01000000
#define FILE_FLAG_RANDOM_ACCESS 0x10000000
#define FILE_SUPPORTS_ENCRYPTION 0x00020000
#define WRITE_DAC (0x00040000L)
#define FILE_SUPPORTS_REPARSE_POINTS 0x00000080
#define FILE_FILE_COMPRESSION 0x00000010
#define EXCEPTION_NESTED_CALL 0x10
#define EVENT_E_INTERNALERROR ((HRESULT)0x80040206L)
#define PROCESS_VM_READ (0x0010)
#define PROCESS_SET_SESSIONID (0x0004)
#define PAGE_EXECUTE_WRITECOPY 0x80
#define IGNORE 0
#define LMEM_LOWER 0x0000
#define PROCESSOR_ARM820 2080
#define STATUS_SEVERITY_INFORMATIONAL 0x1
#define EXCEPTION_NONCONTINUABLE 0x1
#define LMEM_ZEROINIT 0x0040
#define STANDARD_RIGHTS_READ (READ_CONTROL)
#define VER_PLATFORM_WIN32_CE 3
#define HEAP_PSEUDO_TAG_FLAG 0x8000
#define INFINITE 0xffffffffL
#define EVENT_E_LAST 0x8004021FL
#define PROCESSOR_ARCHITECTURE_MIPS 1
#define EVENT_E_INVALID_PER_USER_SID ((HRESULT)0x80040207L)
#define FILE_ATTRIBUTE_COMPRESSED 0x00000800
#define OPEN_ALWAYS 4
#define VER_SERVER_NT 0x80000000
#define FORMAT_MESSAGE_FROM_HMODULE 0x00000800
#define LMEM_DDESHARE 0x0000
#define FILE_APPEND_DATA ( 0x0004 )
#define PAGE_PHYSICAL 0x400
#define FILE_ATTRIBUTE_ARCHIVE 0x00000020
#define VER_SUITE_TERMINAL 0x00000010
#define FILE_MAP_WRITE SECTION_MAP_WRITE
#define HEAP_SHARED_READONLY 0x00001000
#define GMEM_NOT_BANKED LMEM_NOT_BANKED
#define PROCESSOR_ARCHITECTURE_INTEL 0
#define MEM_PRIVATE 0x20000
#define EXCEPTION_STACK_INVALID 0x8
#define FILE_SUPPORTS_REMOTE_STORAGE 0x00000100
#define PROCESSOR_HITACHI_SH3_CORE 1
#define VER_PLATFORM_WIN32_WINDOWS 1
#define PAGE_NOACCESS 0x01
#define EVENT_SET 3
#define SECTION_QUERY 0x0001
#define PROCESSOR_ARM920 2336
#define FILE_FLAG_BACKUP_SEMANTICS 0x02000000
#define FILE_DELETE_CHILD ( 0x0040 )
#define PROCESSOR_ARCHITECTURE_ALPHA64 7
#define THREAD_PRIORITY_HIGHEST 1
#define STANDARD_RIGHTS_ALL (0x001F0000L)
#define LMEM_MOVEABLE 0x0002
#define FILE_ADD_FILE ( 0x0002 )
#define PROCESS_QUERY_INFORMATION (0x0400)
#define PROCESS_SET_INFORMATION (0x0200)
#define DUPLICATE_SAME_ACCESS 0x00000002
#define PROCESSOR_MIPS_R4000 4000
#define WAIT_TIMEOUT 258L
#define VER_PLATFORM_WIN32_HH 3
#define FILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)
#define PROCESSOR_ARCHITECTURE_IA64 6
#define THREAD_BASE_PRIORITY_MAX 2
#define FILE_ACTION_ADDED 0x00000001
#define PROCESS_VM_OPERATION (0x0008)
#define FILE_CURRENT 1
#define FILE_SUPPORTS_OBJECT_IDS 0x00010000
#define TRUNCATE_EXISTING 5
#define THREAD_BASE_PRIORITY_MIN -2
#define FORMAT_MESSAGE_FROM_SYSTEM 0x00001000
#define THREAD_DIRECT_IMPERSONATION (0x0200)
#define FILE_READ_DATA ( 0x0001 )
#define EVENT_E_ALL_SUBSCRIBERS_FAILED ((HRESULT)0x80040201L)
#define HEAP_CREATE_ALIGN_16 0x00010000
#define GMEM_NODISCARD LMEM_NODISCARD
#define PAGE_READWRITE 0x04
#define INVALID_ATOM ((ATOM)0)
#define THREAD_SUSPEND_RESUME (0x0002)
#define FILE_ATTRIBUTE_SPARSE_FILE 0x00000200
#define CREATE_THREAD_DEBUG_EVENT 2
#define FILE_FLAG_DELETE_ON_CLOSE 0x04000000
#define CREATE_ALWAYS 2
#define FILE_FLAG_NO_BUFFERING 0x20000000
#define PROCESSOR_ARCHITECTURE_ARM 5
#define DEBUG_ONLY_THIS_PROCESS 0x00000002
#define DUPLICATE_CLOSE_SOURCE 0x00000001
#define TLS_FUNCFREE 1
#define INVALID_FILE_ATTRIBUTES ((DWORD)-1)
#define LMEM_LOCKCOUNT 0x00FF
#define EVENT_E_USER_EXCEPTION ((HRESULT)0x80040208L)
#define FORMAT_MESSAGE_FROM_STRING 0x00000400
#define GMEM_ZEROINIT LMEM_ZEROINIT
#define FILE_ATTRIBUTE_ENCRYPTED 0x00004000
#define THREAD_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x3FF)
#define PROCESSOR_FEATURE_NOFP 0
#define LMEM_DISCARDED 0x4000
#define LMEM_FIXED 0x0000
#define GMEM_NOCOMPACT LMEM_NOCOMPACT
#define THREAD_SET_INFORMATION (0x0020)
#define FILE_WRITE_EA ( 0x0010 )
#define PROCESSOR_ARCHITECTURE_PPC 3
#define FILE_READ_ATTRIBUTES ( 0x0080 )
#define EVENT_PULSE 1
#define EVENT_RESET 2
#define FILE_SHARE_DELETE 0x00000004
#define FILE_NOTIFY_CHANGE_ATTRIBUTES 0x00000004
#define DEBUG_PROCESS 0x00000001
#define VER_SUITE_BACKOFFICE 0x00000004
#define EVENT_E_PER_USER_SID_NOT_LOGGED_ON ((HRESULT)0x80040210L)
#define THREAD_TERMINATE (0x0001)
#define MEM_RELEASE 0x8000
#define GMEM_DDESHARE LMEM_DDESHARE
#define CREATE_PROCESS_DEBUG_EVENT 3
#define EVENT_E_QUERYSYNTAX ((HRESULT)0x80040203L)
#define PROCESSOR_SHx_SH3 103
#define PROCESSOR_SHx_SH4 104
#define PROCESS_DUP_HANDLE (0x0040)
#define PROCESSOR_SHx_SH3DSP 105
#define PROCESSOR_MIPSII_CORE 2
#define PROCESSOR_ARM_V4_CORE 1
#define FILE_NOTIFY_CHANGE_LAST_WRITE 0x00000010
#define EVENT_E_INVALID_EVENT_CLASS_PARTITION ((HRESULT)0x8004020FL)
#define FILE_ACTION_REMOVED 0x00000002
#define STANDARD_RIGHTS_WRITE (READ_CONTROL)
#define EVENT_E_TOO_MANY_METHODS ((HRESULT)0x80040209L)
#define FILE_READ_EA ( 0x0008 )
#define PROCESSOR_STRONGARM 2577
#define GMEM_SHARE LMEM_SHARE
#define HEAP_DISABLE_COALESCE_ON_FREE 0x00000080
#define PROCESSOR_MIPS_R5000 5000
#define FILE_TRAVERSE ( 0x0020 )
#define FILE_SHARE_WRITE 0x00000002
#define VER_PLATFORM_WIN32s 0
#define FILE_ATTRIBUTE_NOT_CONTENT_INDEXED 0x00002000
#define EVENT_S_FIRST 0x00040200L
#define EXCEPTION_TARGET_UNWIND 0x20
#define GMEM_MOVEABLE LMEM_MOVEABLE
#define SEMAPHORE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define GMEM_NOTIFY LMEM_NOTIFY
#define GMEM_DISCARDABLE LMEM_DISCARDABLE
#define EVENT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define FILE_GENERIC_WRITE (STANDARD_RIGHTS_WRITE | FILE_WRITE_DATA | FILE_WRITE_ATTRIBUTES | FILE_WRITE_EA | FILE_APPEND_DATA | SYNCHRONIZE)
#define FILE_MAP_READ SECTION_MAP_READ
#define PROCESSOR_FEATURE_DSP PROCESSOR_FEATURE_FP
#define FILE_GENERIC_EXECUTE (STANDARD_RIGHTS_EXECUTE | FILE_READ_ATTRIBUTES | FILE_EXECUTE | SYNCHRONIZE)
#define GMEM_LOWER LMEM_LOWER
#define FILE_GENERIC_READ (STANDARD_RIGHTS_READ | FILE_READ_DATA | FILE_READ_ATTRIBUTES | FILE_READ_EA | SYNCHRONIZE)
#define LHND (LMEM_MOVEABLE | LMEM_ZEROINIT)
#define SECTION_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SECTION_QUERY| SECTION_MAP_WRITE | SECTION_MAP_READ | SECTION_MAP_EXECUTE | SECTION_EXTEND_SIZE)
#define EXCEPTION_UNWIND (EXCEPTION_UNWINDING | EXCEPTION_EXIT_UNWIND | EXCEPTION_TARGET_UNWIND | EXCEPTION_COLLIDED_UNWIND)
#define GMEM_FIXED LMEM_FIXED
#define GHND LHND
#define LPTR (LMEM_FIXED | LMEM_ZEROINIT)
#define GPTR LPTR
#define FILE_MAP_ALL_ACCESS SECTION_ALL_ACCESS

AKARI_IMPORT LONG WINAPI InterlockedIncrement(LONG volatile *lpAddend) AKARI_NAME(InterlockedIncrement);
AKARI_IMPORT LONG WINAPI InterlockedDecrement(LONG volatile *lpAddend) AKARI_NAME(InterlockedDecrement);
AKARI_IMPORT LONG WINAPI InterlockedExchange(LONG volatile *Target, LONG Value) AKARI_NAME(InterlockedExchange);
AKARI_IMPORT LONG WINAPI InterlockedCompareExchange(LONG volatile *Target, LONG Exchange, LONG Comperand) AKARI_NAME(InterlockedCompareExchange);
AKARI_IMPORT LONG WINAPI InterlockedExchangeAdd(LONG volatile *lpAddend, LONG Value) AKARI_NAME(InterlockedExchangeAdd);
AKARI_IMPORT DWORD WINAPI Random() AKARI_NAME(Random);
AKARI_IMPORT LONG WINAPI CompareFileTime(const FILETIME *lpft1, const FILETIME *lpft2) AKARI_NAME(CompareFileTime);
AKARI_IMPORT BOOL WINAPI FileTimeToSystemTime(const FILETIME *lpft, LPSYSTEMTIME lpst) AKARI_NAME(FileTimeToSystemTime);
AKARI_IMPORT BOOL WINAPI SystemTimeToFileTime(const SYSTEMTIME *lpst, LPFILETIME lpft) AKARI_NAME(SystemTimeToFileTime);
AKARI_IMPORT BOOL WINAPI FileTimeToLocalFileTime(const FILETIME *lpft, LPFILETIME lpftLocal) AKARI_NAME(FileTimeToLocalFileTime);
AKARI_IMPORT BOOL WINAPI LocalFileTimeToFileTime(const FILETIME *lpftLocal, LPFILETIME lpft) AKARI_NAME(LocalFileTimeToFileTime);
AKARI_IMPORT FARPROC WINAPI GetProcAddressW(HMODULE hModule, LPCWSTR lpProcName) AKARI_NAME(GetProcAddressW);
AKARI_IMPORT FARPROC WINAPI GetProcAddressA(HMODULE hModule, LPCSTR lpProcName) AKARI_NAME(GetProcAddressA);
AKARI_IMPORT int WINAPI MulDiv(IN int nNumber, IN int nNumerator, IN int nDenominator) AKARI_NAME(MulDiv);
AKARI_IMPORT VOID WINAPI GetLocalTime(LPSYSTEMTIME lpSystemTime) AKARI_NAME(GetLocalTime);
AKARI_IMPORT VOID WINAPI GetSystemTime(LPSYSTEMTIME lpSystemTime) AKARI_NAME(GetSystemTime);
AKARI_IMPORT VOID WINAPI GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime) AKARI_NAME(GetSystemTimeAsFileTime);
AKARI_IMPORT BOOL WINAPI SetLocalTime(CONST SYSTEMTIME *lpSystemTime) AKARI_NAME(SetLocalTime);
AKARI_IMPORT BOOL WINAPI SetSystemTime(CONST SYSTEMTIME *lpSystemTime) AKARI_NAME(SetSystemTime);
AKARI_IMPORT void WINAPI SetDaylightTime(DWORD dst) AKARI_NAME(SetDaylightTime);
AKARI_IMPORT int WINAPI lstrcmpW(LPCWSTR lpString1, LPCWSTR lpString2) AKARI_NAME(lstrcmpW);
AKARI_IMPORT int WINAPI lstrcmpiW(LPCWSTR lpString1, LPCWSTR lpString2) AKARI_NAME(lstrcmpiW);
AKARI_IMPORT DWORD WINAPI CharLowerBuffW(LPWSTR lpsz, DWORD cchLength) AKARI_NAME(CharLowerBuffW);
AKARI_IMPORT DWORD WINAPI CharUpperBuffW(LPWSTR lpsz, DWORD cchLength) AKARI_NAME(CharUpperBuffW);
AKARI_IMPORT LPWSTR WINAPI CharLowerW(LPWSTR lpsz) AKARI_NAME(CharLowerW);
AKARI_IMPORT LPWSTR WINAPI CharUpperW(LPWSTR lpsz) AKARI_NAME(CharUpperW);
AKARI_IMPORT LPWSTR WINAPI CharPrevW(LPCWSTR lpszStart, LPCWSTR lpszCurrent) AKARI_NAME(CharPrevW);
AKARI_IMPORT LPWSTR WINAPI CharNextW(LPCWSTR lpsz) AKARI_NAME(CharNextW);
AKARI_IMPORT int WINAPIV wsprintfW(LPWSTR, LPCWSTR, ...) AKARI_NAME(wsprintfW);
AKARI_IMPORT VOID WINAPI GlobalMemoryStatus(LPMEMORYSTATUS lpBuffer) AKARI_NAME(GlobalMemoryStatus);
AKARI_IMPORT HLOCAL WINAPI LocalAlloc(UINT fuFlags, UINT cbBytes) AKARI_NAME(LocalAlloc);
AKARI_IMPORT HLOCAL WINAPI LocalAllocTrace(UINT fuFlags, UINT cbBytes, UINT cLineNum, LPCWSTR szFilename) AKARI_NAME(LocalAllocTrace);
AKARI_IMPORT HLOCAL WINAPI LocalFree(HLOCAL hMem) AKARI_NAME(LocalFree);
AKARI_IMPORT HLOCAL WINAPI LocalReAlloc(HLOCAL hMem, UINT cbBytes, UINT fuFlags) AKARI_NAME(LocalReAlloc);
AKARI_IMPORT UINT WINAPI LocalSize(HLOCAL hMem) AKARI_NAME(LocalSize);
AKARI_IMPORT LPVOID WINAPI VirtualAlloc(LPVOID lpAddress, DWORD dwSize, DWORD flAllocationType, DWORD flProtect) AKARI_NAME(VirtualAlloc);
AKARI_IMPORT BOOL WINAPI VirtualFree(LPVOID lpAddress, DWORD dwSize, DWORD dwFreeType) AKARI_NAME(VirtualFree);
AKARI_IMPORT LPVOID WINAPI VirtualAllocEx(HANDLE hProcess, LPVOID lpAddress, DWORD dwSize, DWORD flAllocationType, DWORD flProtect) AKARI_NAME(VirtualAllocEx);
AKARI_IMPORT BOOL WINAPI VirtualFreeEx(HANDLE hProcess, LPVOID lpAddress, DWORD dwSize, DWORD dwFreeType) AKARI_NAME(VirtualFreeEx);
AKARI_IMPORT BOOL WINAPI VirtualProtect(LPVOID lpAddress, DWORD dwSize, DWORD flNewProtect, PDWORD lpflOldProtect) AKARI_NAME(VirtualProtect);
AKARI_IMPORT DWORD WINAPI VirtualQuery(LPCVOID lpAddress, PMEMORY_BASIC_INFORMATION lpBuffer, DWORD dwLength) AKARI_NAME(VirtualQuery);
AKARI_IMPORT BOOL WINAPI VirtualProtectEx(HANDLE hProcess, LPVOID lpAddress, DWORD dwSize, DWORD flNewProtect, PDWORD lpflOldProtect) AKARI_NAME(VirtualProtectEx);
AKARI_IMPORT DWORD WINAPI VirtualQueryEx(HANDLE hProcess, LPCVOID lpAddress, PMEMORY_BASIC_INFORMATION lpBuffer, DWORD dwLength) AKARI_NAME(VirtualQueryEx);
AKARI_IMPORT HANDLE WINAPI GetProcessHeap(VOID) AKARI_NAME(GetProcessHeap);
AKARI_IMPORT HANDLE WINAPI HeapCreate(DWORD flOptions, DWORD dwInitialSize, DWORD dwMaximumSize) AKARI_NAME(HeapCreate);
AKARI_IMPORT BOOL WINAPI HeapDestroy(HANDLE hHeap) AKARI_NAME(HeapDestroy);
AKARI_IMPORT LPVOID WINAPI HeapAlloc(HANDLE hHeap, DWORD dwFlags, DWORD dwBytes) AKARI_NAME(HeapAlloc);
AKARI_IMPORT LPVOID WINAPI HeapReAlloc(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem, DWORD dwBytes) AKARI_NAME(HeapReAlloc);
AKARI_IMPORT BOOL WINAPI HeapFree(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem) AKARI_NAME(HeapFree);
AKARI_IMPORT DWORD WINAPI HeapSize(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem) AKARI_NAME(HeapSize);
AKARI_IMPORT BOOL WINAPI HeapValidate(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem) AKARI_NAME(HeapValidate);
AKARI_IMPORT UINT WINAPI HeapCompact(HANDLE hHeap, DWORD dwFlags) AKARI_NAME(HeapCompact);
AKARI_IMPORT VOID WINAPI OutputDebugStringW(LPCWSTR lpOutputString) AKARI_NAME(OutputDebugStringW);
AKARI_IMPORT BOOL WINAPI QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount) AKARI_NAME(QueryPerformanceCounter);
AKARI_IMPORT BOOL WINAPI QueryPerformanceFrequency(LARGE_INTEGER *lpFrequency) AKARI_NAME(QueryPerformanceFrequency);
AKARI_IMPORT BOOL WINAPI GetVersionExW(LPOSVERSIONINFOW lpVersionInformation) AKARI_NAME(GetVersionExW);
AKARI_IMPORT HINSTANCE WINAPI LoadLibraryW(LPCWSTR lpLibFileName) AKARI_NAME(LoadLibraryW);
AKARI_IMPORT HMODULE WINAPI LoadLibraryExW(IN LPCWSTR lpLibFileName, IN HANDLE hFile, IN DWORD dwFlags) AKARI_NAME(LoadLibraryExW);
AKARI_IMPORT DWORD WINAPI GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize) AKARI_NAME(GetModuleFileNameW);
AKARI_IMPORT HMODULE WINAPI GetModuleHandleW(LPCWSTR lpModuleName) AKARI_NAME(GetModuleHandleW);
AKARI_IMPORT ULONG WINAPI RemoveVectoredExceptionHandler(IN PVOID VectoredHandlerHandle) AKARI_NAME(RemoveVectoredExceptionHandler);
AKARI_IMPORT VOID WINAPI EnterCriticalSection(LPCRITICAL_SECTION pcsCriticalSection) AKARI_NAME(EnterCriticalSection);
AKARI_IMPORT VOID WINAPI LeaveCriticalSection(LPCRITICAL_SECTION pcsCriticalSection) AKARI_NAME(LeaveCriticalSection);
AKARI_IMPORT VOID WINAPI InitializeCriticalSection(LPCRITICAL_SECTION pcsCriticalSection) AKARI_NAME(InitializeCriticalSection);
AKARI_IMPORT BOOL WINAPI TryEnterCriticalSection(IN OUT LPCRITICAL_SECTION lpCriticalSection) AKARI_NAME(TryEnterCriticalSection);
AKARI_IMPORT VOID WINAPI DeleteCriticalSection(LPCRITICAL_SECTION pcsCriticalSection) AKARI_NAME(DeleteCriticalSection);
AKARI_IMPORT BOOL WINAPI ContinueDebugEvent(DWORD dwProcessId, DWORD dwThreadId, DWORD dwContinueStatus) AKARI_NAME(ContinueDebugEvent);
AKARI_IMPORT BOOL WINAPI DebugActiveProcess(DWORD dwProcessId) AKARI_NAME(DebugActiveProcess);
AKARI_IMPORT BOOL WINAPI DebugActiveProcessStop(DWORD dwProcessId) AKARI_NAME(DebugActiveProcessStop);
AKARI_IMPORT BOOL WINAPI DebugSetProcessKillOnExit(BOOL KillOnExit) AKARI_NAME(DebugSetProcessKillOnExit);
AKARI_IMPORT LPVOID WINAPI MapViewOfFile(HANDLE hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, DWORD dwNumberOfBytesToMap) AKARI_NAME(MapViewOfFile);
AKARI_IMPORT BOOL WINAPI UnmapViewOfFile(LPCVOID lpBaseAddress) AKARI_NAME(UnmapViewOfFile);
AKARI_IMPORT BOOL WINAPI FlushViewOfFile(LPCVOID lpBaseAddress, DWORD dwNumberOfBytesToFlush) AKARI_NAME(FlushViewOfFile);
AKARI_IMPORT HANDLE WINAPI CreateFileMappingW(HANDLE hFile, LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCWSTR lpName) AKARI_NAME(CreateFileMappingW);
AKARI_IMPORT HANDLE WINAPI CreateFileForMappingW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile) AKARI_NAME(CreateFileForMappingW);
AKARI_IMPORT DWORD WINAPI GetTempPathW(DWORD nBufferLength, LPWSTR lpBuffer) AKARI_NAME(GetTempPathW);
AKARI_IMPORT HANDLE WINAPI CreateThread(LPSECURITY_ATTRIBUTES lpsa, DWORD cbStack, LPTHREAD_START_ROUTINE lpStartAddr, LPVOID lpvThreadParam, DWORD fdwCreate, LPDWORD lpIDThread) AKARI_NAME(CreateThread);
AKARI_IMPORT VOID WINAPI ExitThread(DWORD dwExitCode) AKARI_NAME(ExitThread);
AKARI_IMPORT BOOL WINAPI TerminateThread(HANDLE hThread, DWORD dwExitCode) AKARI_NAME(TerminateThread);
AKARI_IMPORT LPVOID WINAPI ConvertThreadToFiber(LPVOID lpParameter) AKARI_NAME(ConvertThreadToFiber);
AKARI_IMPORT VOID WINAPI DeleteFiber(LPVOID lpFiber) AKARI_NAME(DeleteFiber);
AKARI_IMPORT LPVOID WINAPI GetFiberData(VOID) AKARI_NAME(GetFiberData);
AKARI_IMPORT VOID WINAPI SwitchToFiber(LPVOID lpFiber) AKARI_NAME(SwitchToFiber);
AKARI_IMPORT LPVOID WINAPI TlsGetValue(DWORD dwTlsIndex) AKARI_NAME(TlsGetValue);
AKARI_IMPORT BOOL WINAPI TlsSetValue(DWORD dwTlsIndex, LPVOID lpvTlsValue) AKARI_NAME(TlsSetValue);
AKARI_IMPORT DWORD WINAPI GetProcessVersion(DWORD ProcessId) AKARI_NAME(GetProcessVersion);
AKARI_IMPORT DWORD WINAPI GetProcessId(HANDLE hProcess) AKARI_NAME(GetProcessId);
AKARI_IMPORT LPWSTR WINAPI GetCommandLineW(VOID) AKARI_NAME(GetCommandLineW);
AKARI_IMPORT DWORD WINAPI GetLastError(VOID) AKARI_NAME(GetLastError);
AKARI_IMPORT DWORD WINAPI GetTickCount(VOID) AKARI_NAME(GetTickCount);
AKARI_IMPORT DWORD WINAPI GetIdleTime(VOID) AKARI_NAME(GetIdleTime);
AKARI_IMPORT BOOL WINAPI CloseHandle(HANDLE hObject) AKARI_NAME(CloseHandle);
AKARI_IMPORT BOOL WINAPI DuplicateHandle(HANDLE hSourceProcessHandle, HANDLE hSourceHandle, HANDLE hTargetProcessHandle, LPHANDLE lpTargetHandle, DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwOptions) AKARI_NAME(DuplicateHandle);
AKARI_IMPORT HGLOBAL WINAPI LoadResource(HMODULE hModule, HRSRC hResInfo) AKARI_NAME(LoadResource);
AKARI_IMPORT DWORD WINAPI SizeofResource(HMODULE hModule, HRSRC hResInfo) AKARI_NAME(SizeofResource);
AKARI_IMPORT HRSRC WINAPI FindResourceW(HMODULE hModule, LPCWSTR lpName, LPCWSTR lpType) AKARI_NAME(FindResourceW);
AKARI_IMPORT int WINAPI LoadStringW(HINSTANCE hInstance, UINT uID, LPWSTR lpBuffer, int nBufferMax) AKARI_NAME(LoadStringW);
AKARI_IMPORT ATOM WINAPI GlobalAddAtomW(LPCWSTR lpString) AKARI_NAME(GlobalAddAtomW);
AKARI_IMPORT ATOM WINAPI GlobalFindAtomW(LPCWSTR lpString) AKARI_NAME(GlobalFindAtomW);
AKARI_IMPORT ATOM WINAPI GlobalDeleteAtom(ATOM nAtom) AKARI_NAME(GlobalDeleteAtom);
AKARI_IMPORT BOOL WINAPI TerminateProcess(HANDLE hProcess, DWORD uExitCode) AKARI_NAME(TerminateProcess);
AKARI_IMPORT BOOL WINAPI FlushInstructionCache(HANDLE hProcess, LPCVOID lpBaseAddress, DWORD dwSize) AKARI_NAME(FlushInstructionCache);
AKARI_IMPORT BOOL WINAPI ReadProcessMemory(HANDLE hProcess, LPCVOID lpBaseAddress, LPVOID lpBuffer, DWORD nSize, LPDWORD lpNumberOfBytesRead) AKARI_NAME(ReadProcessMemory);
AKARI_IMPORT BOOL WINAPI WriteProcessMemory(HANDLE hProcess, LPVOID lpBaseAddress, LPVOID lpBuffer, DWORD nSize, LPDWORD lpNumberOfBytesWritten) AKARI_NAME(WriteProcessMemory);
AKARI_IMPORT HANDLE WINAPI OpenProcess(DWORD fdwAccess, BOOL fInherit, DWORD IDProcess) AKARI_NAME(OpenProcess);
AKARI_IMPORT HANDLE WINAPI OpenThread(DWORD fdwAccess, BOOL fInherit, DWORD IDThread) AKARI_NAME(OpenThread);
AKARI_IMPORT DWORD WINAPI SuspendThread(HANDLE hThread) AKARI_NAME(SuspendThread);
AKARI_IMPORT DWORD WINAPI ResumeThread(HANDLE hThread) AKARI_NAME(ResumeThread);
AKARI_IMPORT BOOL WINAPI GetThreadTimes(HANDLE hThread, LPFILETIME lpCreationTime, LPFILETIME lpExitTime, LPFILETIME lpKernelTime, LPFILETIME lpUserTime) AKARI_NAME(GetThreadTimes);
AKARI_IMPORT int WINAPI GetThreadPriority(HANDLE hThread) AKARI_NAME(GetThreadPriority);
AKARI_IMPORT BOOL WINAPI SetThreadPriority(HANDLE hThread, int nPriority) AKARI_NAME(SetThreadPriority);
AKARI_IMPORT int WINAPI CeGetThreadPriority(HANDLE hThread) AKARI_NAME(CeGetThreadPriority);
AKARI_IMPORT BOOL WINAPI CeSetThreadPriority(HANDLE hThread, int nPriority) AKARI_NAME(CeSetThreadPriority);
AKARI_IMPORT DWORD WINAPI CeGetThreadQuantum(HANDLE hThread) AKARI_NAME(CeGetThreadQuantum);
AKARI_IMPORT BOOL WINAPI CeSetThreadQuantum(HANDLE hThread, DWORD dwTime) AKARI_NAME(CeSetThreadQuantum);
AKARI_IMPORT DWORD WINAPI GetThreadId(HANDLE hThread) AKARI_NAME(GetThreadId);
AKARI_IMPORT DWORD WINAPI GetProcessIdOfThread(HANDLE hThread) AKARI_NAME(GetProcessIdOfThread);
AKARI_IMPORT LPVOID WINAPI CeZeroPointer(LPVOID ptr) AKARI_NAME(CeZeroPointer);
AKARI_IMPORT VOID WINAPI SetLastError(DWORD dwErrCode) AKARI_NAME(SetLastError);
AKARI_IMPORT UINT WINAPI GetTempFileNameW(IN LPCWSTR lpPathName, IN LPCWSTR lpPrefixString, IN UINT uUnique, LPWSTR lpTempFileName) AKARI_NAME(GetTempFileNameW);
AKARI_IMPORT DWORD WINAPI CeGetCanonicalPathNameW(IN LPCWSTR lpPathName, LPWSTR lpCanonicalPathName, IN DWORD cchCanonicalPathName, IN DWORD dwReserved) AKARI_NAME(CeGetCanonicalPathNameW);
AKARI_IMPORT HANDLE WINAPI CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile) AKARI_NAME(CreateFileW);
AKARI_IMPORT BOOL WINAPI DeleteFileW(LPCWSTR lpFileName) AKARI_NAME(DeleteFileW);
AKARI_IMPORT BOOL WINAPI DeleteAndRenameFile(LPCWSTR lpOldFileName, LPCWSTR lpNewFileName) AKARI_NAME(DeleteAndRenameFile);
AKARI_IMPORT HANDLE WINAPI FindFirstFileW(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData) AKARI_NAME(FindFirstFileW);
AKARI_IMPORT BOOL WINAPI FindNextFileW(HANDLE hFindFile, LPWIN32_FIND_DATAW lpFindFileData) AKARI_NAME(FindNextFileW);
AKARI_IMPORT BOOL WINAPI CopyFileW(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, BOOL bFailIfExists) AKARI_NAME(CopyFileW);
AKARI_IMPORT BOOL WINAPI MoveFileW(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName) AKARI_NAME(MoveFileW);
AKARI_IMPORT BOOL WINAPI CreateDirectoryW(LPCWSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes) AKARI_NAME(CreateDirectoryW);
AKARI_IMPORT BOOL WINAPI RemoveDirectoryW(LPCWSTR lpPathName) AKARI_NAME(RemoveDirectoryW);
AKARI_IMPORT BOOL WINAPI WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped) AKARI_NAME(WriteFile);
AKARI_IMPORT BOOL WINAPI ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped) AKARI_NAME(ReadFile);
AKARI_IMPORT BOOL WINAPI LockFileEx(HANDLE hFile, DWORD dwFlags, DWORD dwReserved, DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh, LPOVERLAPPED lpOverlapped) AKARI_NAME(LockFileEx);
AKARI_IMPORT BOOL WINAPI UnlockFileEx(HANDLE hFile, DWORD dwReserved, DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh, LPOVERLAPPED lpOverlapped) AKARI_NAME(UnlockFileEx);
AKARI_IMPORT BOOL WINAPI FlushFileBuffers(HANDLE hFile) AKARI_NAME(FlushFileBuffers);
AKARI_IMPORT BOOL WINAPI GetFileTime(HANDLE hFile, LPFILETIME lpCreation, LPFILETIME lpLastAccess, LPFILETIME lpLastWrite) AKARI_NAME(GetFileTime);
AKARI_IMPORT BOOL WINAPI SetFileTime(HANDLE hFile, CONST FILETIME *lpCreation, CONST FILETIME *lpLastAccess, CONST FILETIME *lpLastWrite) AKARI_NAME(SetFileTime);
AKARI_IMPORT BOOL WINAPI SetEndOfFile(HANDLE hFile) AKARI_NAME(SetEndOfFile);
AKARI_IMPORT BOOL WINAPI DeviceIoControl(HANDLE hDevice, DWORD dwIoControlCode, LPVOID lpInBuf, DWORD nInBufSize, LPVOID lpOutBuf, DWORD nOutBufSize, LPDWORD lpBytesReturned, LPOVERLAPPED lpOverlapped) AKARI_NAME(DeviceIoControl);
AKARI_IMPORT HANDLE WINAPI FindFirstChangeNotificationW(IN LPCWSTR lpPathName, IN BOOL bWatchSubtree, IN DWORD dwNotifyFilter) AKARI_NAME(FindFirstChangeNotificationW);
AKARI_IMPORT BOOL WINAPI FindNextChangeNotification(IN HANDLE hChangeHandle) AKARI_NAME(FindNextChangeNotification);
AKARI_IMPORT BOOL WINAPI CeGetFileNotificationInfo(HANDLE hChangeHandle, DWORD dwFlags, LPVOID lpBuffer, DWORD nBufferLength, LPDWORD lpBytesReturned, LPDWORD lpBytesAvailable) AKARI_NAME(CeGetFileNotificationInfo);
AKARI_IMPORT BOOL WINAPI FindCloseChangeNotification(IN HANDLE hChangeHandle) AKARI_NAME(FindCloseChangeNotification);
AKARI_IMPORT BOOL WINAPI GetOverlappedResult(HANDLE hFile, LPOVERLAPPED lpOverlapped, LPDWORD lpNumberOfBytesTransferred, BOOL bWait) AKARI_NAME(GetOverlappedResult);
AKARI_IMPORT BOOL WINAPI SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes) AKARI_NAME(SetFileAttributesW);
AKARI_IMPORT DWORD WINAPI SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod) AKARI_NAME(SetFilePointer);
AKARI_IMPORT BOOL WINAPI FindClose(HANDLE hFindFile) AKARI_NAME(FindClose);
AKARI_IMPORT DWORD WINAPI GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh) AKARI_NAME(GetFileSize);
AKARI_IMPORT DWORD WINAPI GetFileAttributesW(LPCWSTR lpFileName) AKARI_NAME(GetFileAttributesW);
AKARI_IMPORT VOID WINAPI Sleep(DWORD dwMilliseconds) AKARI_NAME(Sleep);
AKARI_IMPORT HANDLE WINAPI CreateMutexW(LPSECURITY_ATTRIBUTES lpsa, BOOL bInitialOwner, LPCWSTR lpName) AKARI_NAME(CreateMutexW);
AKARI_IMPORT HANDLE WINAPI CreateEventW(LPSECURITY_ATTRIBUTES lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPCWSTR lpName) AKARI_NAME(CreateEventW);
AKARI_IMPORT HANDLE WINAPI OpenEventW(DWORD dwDesiredAccess, BOOL bInheritHandle, LPCWSTR lpName) AKARI_NAME(OpenEventW);
AKARI_IMPORT HANDLE WINAPI CreateSemaphoreW(IN LPSECURITY_ATTRIBUTES lpSemaphoreAttributes, IN LONG lInitialCount, IN LONG lMaximumCount, IN LPCWSTR lpName) AKARI_NAME(CreateSemaphoreW);
AKARI_IMPORT BOOL WINAPI ReleaseSemaphore(IN HANDLE hSemaphore, IN LONG lReleaseCount, OUT LPLONG lpPreviousCount) AKARI_NAME(ReleaseSemaphore);
AKARI_IMPORT BOOL WINAPI ReleaseMutex(HANDLE hMutex) AKARI_NAME(ReleaseMutex);
AKARI_IMPORT DWORD WINAPI WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds) AKARI_NAME(WaitForSingleObject);
AKARI_IMPORT DWORD WINAPI WaitForMultipleObjects(DWORD cObjects, CONST HANDLE *lphObjects, BOOL fWaitAll, DWORD dwTimeout) AKARI_NAME(WaitForMultipleObjects);
AKARI_IMPORT BOOL WINAPI GetExitCodeThread(HANDLE hThread, LPDWORD lpExitCode) AKARI_NAME(GetExitCodeThread);
AKARI_IMPORT BOOL WINAPI GetExitCodeProcess(HANDLE hProcess, LPDWORD lpExitCode) AKARI_NAME(GetExitCodeProcess);
AKARI_IMPORT BOOL WINAPI IsBadCodePtr(FARPROC lpfn) AKARI_NAME(IsBadCodePtr);
AKARI_IMPORT BOOL WINAPI IsBadReadPtr(CONST VOID *lp, UINT ucb) AKARI_NAME(IsBadReadPtr);
AKARI_IMPORT BOOL WINAPI IsBadWritePtr(LPVOID lp, UINT ucb) AKARI_NAME(IsBadWritePtr);
AKARI_IMPORT VOID WINAPI GetSystemInfo(LPSYSTEM_INFO lpSystemInfo) AKARI_NAME(GetSystemInfo);
AKARI_IMPORT BOOL WINAPI QueryInstructionSet(DWORD dwInstructionSet, LPDWORD lpdwCurrentInstructionSet) AKARI_NAME(QueryInstructionSet);
AKARI_IMPORT BOOL WINAPI IsProcessorFeaturePresent(DWORD dwProcessorFeature) AKARI_NAME(IsProcessorFeaturePresent);
AKARI_IMPORT VOID WINAPI RaiseException(DWORD dwExceptionCode, DWORD dwExceptionFlags, DWORD nNumberOfArguments, CONST DWORD *lpArguments) AKARI_NAME(RaiseException);
AKARI_IMPORT BOOL WINAPI FreeLibrary(HMODULE hLibModule) AKARI_NAME(FreeLibrary);
AKARI_IMPORT VOID WINAPI FreeLibraryAndExitThread(HMODULE hLibModule, DWORD dwExitCode) AKARI_NAME(FreeLibraryAndExitThread);
AKARI_IMPORT BOOL WINAPI DisableThreadLibraryCalls(IN HMODULE hLibModule) AKARI_NAME(DisableThreadLibraryCalls);
AKARI_IMPORT BOOL WINAPI ClearCommBreak(HANDLE hFile) AKARI_NAME(ClearCommBreak);
AKARI_IMPORT BOOL WINAPI SetupComm(HANDLE hFile, DWORD dwInQueue, DWORD dwOutQueue) AKARI_NAME(SetupComm);
AKARI_IMPORT BOOL WINAPI EscapeCommFunction(HANDLE hFile, DWORD dwFunc) AKARI_NAME(EscapeCommFunction);
AKARI_IMPORT BOOL WINAPI GetCommMask(HANDLE hFile, LPDWORD lpEvtMask) AKARI_NAME(GetCommMask);
AKARI_IMPORT BOOL WINAPI GetCommModemStatus(HANDLE hFile, LPDWORD lpModemStat) AKARI_NAME(GetCommModemStatus);
AKARI_IMPORT BOOL WINAPI PurgeComm(HANDLE hFile, DWORD dwFlags) AKARI_NAME(PurgeComm);
AKARI_IMPORT BOOL WINAPI SetCommBreak(HANDLE hFile) AKARI_NAME(SetCommBreak);
AKARI_IMPORT BOOL WINAPI SetCommMask(HANDLE hFile, DWORD dwEvtMask) AKARI_NAME(SetCommMask);
AKARI_IMPORT BOOL WINAPI TransmitCommChar(HANDLE hFile, char cChar) AKARI_NAME(TransmitCommChar);
AKARI_IMPORT BOOL WINAPI WaitCommEvent(HANDLE hFile, LPDWORD lpEvtMask, LPOVERLAPPED lpOverlapped) AKARI_NAME(WaitCommEvent);
AKARI_IMPORT void WINAPI BatteryNotifyOfTimeChange(BOOL fForward, FILETIME *pftDelta) AKARI_NAME(BatteryNotifyOfTimeChange);
AKARI_IMPORT HANDLE WINAPI RegisterEventSourceW(LPCWSTR lpUNCServerName, LPCWSTR lpSourceName) AKARI_NAME(RegisterEventSourceW);
AKARI_IMPORT BOOL WINAPI DeregisterEventSource(HANDLE hEventLog) AKARI_NAME(DeregisterEventSource);
AKARI_IMPORT BOOL WINAPI ClearEventLogW(HANDLE hEventLog, LPCWSTR lpBackupFileName) AKARI_NAME(ClearEventLogW);
AKARI_IMPORT HANDLE WINAPI OpenEventLogW(LPCTSTR lpUNCServerName, LPCTSTR lpSourceName) AKARI_NAME(OpenEventLogW);
AKARI_IMPORT BOOL WINAPI CloseEventLog(HANDLE hEventLog) AKARI_NAME(CloseEventLog);
AKARI_IMPORT BOOL WINAPI BackupEventLogW(HANDLE hEventLog, LPCTSTR szBackupFileName) AKARI_NAME(BackupEventLogW);
AKARI_IMPORT BOOL WINAPI LockEventLog(HANDLE hEventLog) AKARI_NAME(LockEventLog);
AKARI_IMPORT BOOL WINAPI UnLockEventLog(HANDLE hEventLog) AKARI_NAME(UnLockEventLog);
AKARI_IMPORT BOOL WINAPI ReadEventLogRaw(HANDLE hEventLog, BYTE *pReadBuffer, DWORD dwReadBufferSize, DWORD *pdwBytesRead) AKARI_NAME(ReadEventLogRaw);
AKARI_IMPORT DWORD WINAPI CeCertVerify(HANDLE hFile, HANDLE * phHandle, LPCWSTR pszFileName, LPWSTR pszAccountName, DWORD cbAccountNameSize, DWORD dwFlags) AKARI_NAME(CeCertVerify);

#define BackupEventLog BackupEventLogW
#define CeGetCanonicalPathName CeGetCanonicalPathNameW
#define CharLowerBuff CharLowerBuffW
#define CharLower CharLowerW
#define CharNext CharNextW
#define CharPrev CharPrevW
#define CharUpperBuff CharUpperBuffW
#define CharUpper CharUpperW
#define ClearEventLog ClearEventLogW
#define CopyFile CopyFileW
#define CreateDirectory CreateDirectoryW
#define CreateEvent CreateEventW
#define CreateFileMapping CreateFileMappingW
#define CreateFile CreateFileW
#define CreateMutex CreateMutexW
#define CreateSemaphore CreateSemaphoreW
#define DeleteFile DeleteFileW
#define FindFirstChangeNotification FindFirstChangeNotificationW
#define FindFirstFile FindFirstFileW
#define FindNextFile FindNextFileW
#define GetCommandLine GetCommandLineW
#define GetFileAttributes GetFileAttributesW
#define GetModuleFileName GetModuleFileNameW
#define GetModuleHandle GetModuleHandleW
#define GetProcAddress GetProcAddressW
#define GetTempFileName GetTempFileNameW
#define GetTempPath GetTempPathW
#define GlobalAddAtom GlobalAddAtomW
#define GlobalFindAtom GlobalFindAtomW
#define LoadLibraryEx LoadLibraryExW
#define LoadLibrary LoadLibraryW
#define LoadString LoadStringW
#define MoveFile MoveFileW
#define OpenEventLog OpenEventLogW
#define OpenEvent OpenEventW
#define OutputDebugString OutputDebugStringW
#define RegisterEventSource RegisterEventSourceW
#define RemoveDirectory RemoveDirectoryW
#define SetFileAttributes SetFileAttributesW
#define lstrcmp lstrcmpW
#define lstrcmpi lstrcmpiW
#define wsprintf wsprintfW

#ifdef __cplusplus
}
#endif
#endif
