/* WinCE development API surface.
 * Original declarations written from a survey of CE 4.2, 5.0, and 6.0
 * public interface facts (names, types, layouts, constants, exports).
 * Not an OS, BSP, OAK, or Platform Builder component, and not a copy
 * of upstream source.
 */

#ifndef WCE_WINGDI_H
#define WCE_WINGDI_H
#include "windef.h"
#include "winnt.h"
#include "wceunk.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tagLOGPALETTE { WORD palVersion; WORD palNumEntries; PALETTEENTRY palPalEntry[1]; } LOGPALETTE, *PLOGPALETTE, *LPLOGPALETTE;
typedef struct tagBITMAP { LONG bmType; LONG bmWidth; LONG bmHeight; LONG bmWidthBytes; WORD bmPlanes; WORD bmBitsPixel; LPVOID bmBits; } BITMAP, *PBITMAP, *LPBITMAP;
typedef struct tagBITMAPFILEHEADER { WORD bfType; DWORD bfSize; WORD bfReserved1; WORD bfReserved2; DWORD bfOffBits; } BITMAPFILEHEADER, *PBITMAPFILEHEADER, *LPBITMAPFILEHEADER;
typedef struct tagHANDLETABLE { HGDIOBJ objectHandle[1]; } HANDLETABLE, *PHANDLETABLE, *LPHANDLETABLE;
typedef struct tagRGBTRIPLE { BYTE rgbtBlue; BYTE rgbtGreen; BYTE rgbtRed; } RGBTRIPLE, *PRGBTRIPLE, *LPRGBTRIPLE;
typedef struct tagCOLORADJUSTMENT { WORD caSize; WORD caFlags; WORD caIlluminantIndex; WORD caRedGamma; WORD caGreenGamma; WORD caBlueGamma; WORD caReferenceBlack; WORD caReferenceWhite; SHORT caContrast; SHORT caBrightness; SHORT caColorfulness; SHORT caRedGreenTint; } COLORADJUSTMENT, *PCOLORADJUSTMENT, *LPCOLORADJUSTMENT;
typedef struct tagLOGBRUSH { UINT lbStyle; COLORREF lbColor; LONG lbHatch; } LOGBRUSH, *PLOGBRUSH, *LPLOGBRUSH;
typedef struct tagLOGPEN { UINT lopnStyle; POINT lopnWidth; COLORREF lopnColor; } LOGPEN, *PLOGPEN, *LPLOGPEN;
typedef struct tagBITMAPCOREHEADER { DWORD bcSize; WORD bcWidth; WORD bcHeight; WORD bcPlanes; WORD bcBitCount; } BITMAPCOREHEADER, *PBITMAPCOREHEADER, *LPBITMAPCOREHEADER;
typedef struct tagBITMAPCOREINFO { BITMAPCOREHEADER bmciHeader; RGBTRIPLE bmciColors[1]; } BITMAPCOREINFO, *PBITMAPCOREINFO, *LPBITMAPCOREINFO;
typedef struct tagRGNDATAHEADER { DWORD dwSize; DWORD iType; DWORD nCount; DWORD nRgnSize; RECT rcBound; } RGNDATAHEADER, *PRGNDATAHEADER, *LPRGNDATAHEADER;
typedef struct tagRGNDATA { RGNDATAHEADER rdh; char Buffer[1]; } RGNDATA, *PRGNDATA, *LPRGNDATA;
typedef struct tagDIBSECTION2 { BITMAP dsBm; BITMAPINFOHEADER dsBmih; DWORD dsBitfields[3]; HANDLE dshSection; DWORD dsOffset; DWORD dsAlphaBitfield; } DIBSECTION2, *PDIBSECTION2, *LPDIBSECTION2;
typedef struct tagDOCINFOA { int cbSize; LPCSTR lpszDocName; LPCSTR lpszOutput; LPCSTR lpszDatatype; DWORD fwType; } DOCINFOA, *PDOCINFOA, *LPDOCINFOA;
typedef struct tagDOCINFOW { int cbSize; LPCWSTR lpszDocName; LPCWSTR lpszOutput; LPCWSTR lpszDatatype; DWORD fwType; } DOCINFOW, *PDOCINFOW, *LPDOCINFOW;
typedef struct tagGRADIENT_TRIANGLE { ULONG Vertex1; ULONG Vertex2; ULONG Vertex3; } GRADIENT_TRIANGLE, *PGRADIENT_TRIANGLE, *LPGRADIENT_TRIANGLE;
typedef struct tagGRADIENT_RECT { ULONG UpperLeft; ULONG LowerRight; } GRADIENT_RECT, *PGRADIENT_RECT, *LPGRADIENT_RECT;
typedef struct tagBLENDFUNCTION { BYTE BlendOp; BYTE BlendFlags; BYTE SourceConstantAlpha; BYTE AlphaFormat; } BLENDFUNCTION, *PBLENDFUNCTION, *LPBLENDFUNCTION;
typedef struct tagPOINTFLOAT { FLOAT x; FLOAT y; } POINTFLOAT, *PPOINTFLOAT, *LPPOINTFLOAT;
typedef struct tagGLYPHMETRICSFLOAT { FLOAT gmfBlackBoxX; FLOAT gmfBlackBoxY; POINTFLOAT gmfptGlyphOrigin; FLOAT gmfCellIncX; FLOAT gmfCellIncY; } GLYPHMETRICSFLOAT, *PGLYPHMETRICSFLOAT, *LPGLYPHMETRICSFLOAT;

WCE_IMPORT HDC WINAPI CreateCompatibleDC(HDC) WCE_LINK(CreateCompatibleDC);
WCE_IMPORT BOOL WINAPI DeleteDC(HDC) WCE_LINK(DeleteDC);
WCE_IMPORT BOOL WINAPI DeleteObject(HGDIOBJ) WCE_LINK(DeleteObject);
WCE_IMPORT COLORREF WINAPI GetBkColor(HDC) WCE_LINK(GetBkColor);
WCE_IMPORT int WINAPI GetBkMode(HDC) WCE_LINK(GetBkMode);
WCE_IMPORT HGDIOBJ WINAPI GetCurrentObject(HDC,UINT) WCE_LINK(GetCurrentObject);
WCE_IMPORT int WINAPI GetDeviceCaps(HDC,int) WCE_LINK(GetDeviceCaps);
WCE_IMPORT int WINAPI GetObjectA(HGDIOBJ, int, LPVOID) WCE_LINK(GetObjectA);
WCE_IMPORT int WINAPI GetObjectW(HGDIOBJ, int, LPVOID) WCE_LINK(GetObjectW);
WCE_IMPORT DWORD WINAPI GetObjectType(HGDIOBJ h) WCE_LINK(GetObjectType);
WCE_IMPORT HGDIOBJ WINAPI GetStockObject(int) WCE_LINK(GetStockObject);
WCE_IMPORT COLORREF WINAPI GetTextColor(HDC) WCE_LINK(GetTextColor);
WCE_IMPORT HGDIOBJ WINAPI SelectObject(HDC,HGDIOBJ) WCE_LINK(SelectObject);
WCE_IMPORT COLORREF WINAPI SetBkColor(HDC,COLORREF) WCE_LINK(SetBkColor);
WCE_IMPORT int WINAPI SetBkMode(HDC,int) WCE_LINK(SetBkMode);
WCE_IMPORT COLORREF WINAPI SetTextColor(HDC,COLORREF) WCE_LINK(SetTextColor);
WCE_IMPORT UINT WINAPI GetDIBColorTable(HDC,UINT,UINT,RGBQUAD *) WCE_LINK(GetDIBColorTable);
WCE_IMPORT UINT WINAPI SetDIBColorTable(HDC,UINT,UINT,CONST RGBQUAD *) WCE_LINK(SetDIBColorTable);
WCE_IMPORT BOOL WINAPI GetWindowOrgEx(HDC,LPPOINT) WCE_LINK(GetWindowOrgEx);
WCE_IMPORT BOOL WINAPI GetWindowExtEx(HDC,LPSIZE) WCE_LINK(GetWindowExtEx);
WCE_IMPORT BOOL WINAPI OffsetViewportOrgEx(HDC hdc, int x, int y, LPPOINT lppt) WCE_LINK(OffsetViewportOrgEx);
WCE_IMPORT BOOL WINAPI GetViewportOrgEx(HDC,LPPOINT) WCE_LINK(GetViewportOrgEx);
#if (_WIN32_WCE >= 0x600)
WCE_IMPORT BOOL WINAPI GetViewportExtEx(HDC,LPSIZE) WCE_LINK(GetViewportExtEx);
#endif
WCE_IMPORT HBRUSH WINAPI CreatePatternBrush(HBITMAP) WCE_LINK(CreatePatternBrush);
WCE_IMPORT BOOL WINAPI FillRgn(HDC, HRGN, HBRUSH) WCE_LINK(FillRgn);
WCE_IMPORT int WINAPI SetROP2(HDC, int) WCE_LINK(SetROP2);
#if (_WIN32_WCE >= 0x600)
WCE_IMPORT int WINAPI GetROP2(HDC) WCE_LINK(GetROP2);
#endif
WCE_IMPORT HBRUSH WINAPI CreateDIBPatternBrushPt(CONST VOID *,UINT) WCE_LINK(CreateDIBPatternBrushPt);
WCE_IMPORT HPEN WINAPI CreatePenIndirect(CONST LOGPEN *) WCE_LINK(CreatePenIndirect);
WCE_IMPORT HBRUSH WINAPI CreateSolidBrush(COLORREF) WCE_LINK(CreateSolidBrush);
WCE_IMPORT BOOL WINAPI DrawEdge(HDC,RECT *,UINT,UINT) WCE_LINK(DrawEdge);
WCE_IMPORT BOOL WINAPI DrawFocusRect(HDC,CONST RECT *) WCE_LINK(DrawFocusRect);
WCE_IMPORT int WINAPI FillRect(HDC,CONST RECT *,HBRUSH) WCE_LINK(FillRect);
WCE_IMPORT HBRUSH WINAPI GetSysColorBrush(int) WCE_LINK(GetSysColorBrush);
WCE_IMPORT BOOL WINAPI Polygon(HDC hdc, CONST POINT * lppt, int c) WCE_LINK(Polygon);
WCE_IMPORT BOOL WINAPI Polyline(HDC hdc, CONST POINT * lppt, int c) WCE_LINK(Polyline);
WCE_IMPORT BOOL WINAPI SetBrushOrgEx(HDC hdc, int x, int y, LPPOINT lppt) WCE_LINK(SetBrushOrgEx);
WCE_IMPORT BOOL WINAPI GetCurrentPositionEx(HDC,LPPOINT) WCE_LINK(GetCurrentPositionEx);
WCE_IMPORT LONG WINAPI SetBitmapBits(HBITMAP,DWORD,CONST VOID*) WCE_LINK(SetBitmapBits);
WCE_IMPORT int WINAPI CombineRgn(HRGN,HRGN,HRGN,int) WCE_LINK(CombineRgn);
WCE_IMPORT HRGN WINAPI CreateRectRgnIndirect(CONST RECT *) WCE_LINK(CreateRectRgnIndirect);
WCE_IMPORT BOOL WINAPI EqualRgn(HRGN,HRGN) WCE_LINK(EqualRgn);
WCE_IMPORT int WINAPI GetClipBox(HDC,LPRECT) WCE_LINK(GetClipBox);
WCE_IMPORT int WINAPI GetClipRgn(HDC,HRGN) WCE_LINK(GetClipRgn);
WCE_IMPORT DWORD WINAPI GetRegionData(HRGN,DWORD,LPRGNDATA) WCE_LINK(GetRegionData);
WCE_IMPORT int WINAPI GetRgnBox(HRGN,RECT *) WCE_LINK(GetRgnBox);
WCE_IMPORT BOOL WINAPI RectInRegion(HRGN,CONST RECT *) WCE_LINK(RectInRegion);
WCE_IMPORT int WINAPI SelectClipRgn(HDC,HRGN) WCE_LINK(SelectClipRgn);
WCE_IMPORT BOOL WINAPI RectVisible(HDC, CONST RECT *) WCE_LINK(RectVisible);
WCE_IMPORT HRGN WINAPI ExtCreateRegion(CONST XFORM *,DWORD, CONST RGNDATA *) WCE_LINK(ExtCreateRegion);
WCE_IMPORT BOOL WINAPI InvertRect(HDC hDC, CONST RECT * lprc) WCE_LINK(InvertRect);
WCE_IMPORT int WINAPI SetStretchBltMode(HDC, int) WCE_LINK(SetStretchBltMode);
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT int WINAPI GetStretchBltMode(HDC) WCE_LINK(GetStretchBltMode);
#endif
WCE_IMPORT int WINAPI AddFontResourceA(LPWSTR) WCE_LINK(AddFontResourceA);
WCE_IMPORT int WINAPI AddFontResourceW(LPCWSTR) WCE_LINK(AddFontResourceW);
#if (_WIN32_WCE >= 0x420 && _WIN32_WCE < 0x600)
WCE_IMPORT BOOL WINAPI ExtTextOutA(HDC hdc, int x, int y, UINT options, CONST RECT * lprect, LPCSTR lpString, UINT c, CONST INT * lpDx) WCE_LINK(ExtTextOutA);
#endif
WCE_IMPORT BOOL WINAPI ExtTextOutW(HDC hdc, int x, int y, UINT options, CONST RECT * lprect, LPCWSTR lpString, UINT c, CONST INT * lpDx) WCE_LINK(ExtTextOutW);
WCE_IMPORT BOOL WINAPI GetTextMetricsA(HDC,LPTEXTMETRICA) WCE_LINK(GetTextMetricsA);
WCE_IMPORT BOOL WINAPI GetTextMetricsW(HDC,LPTEXTMETRICW) WCE_LINK(GetTextMetricsW);
WCE_IMPORT BOOL WINAPI RemoveFontResourceA(LPCSTR) WCE_LINK(RemoveFontResourceA);
WCE_IMPORT BOOL WINAPI RemoveFontResourceW(LPCWSTR) WCE_LINK(RemoveFontResourceW);
WCE_IMPORT UINT WINAPI SetTextAlign(HDC,UINT) WCE_LINK(SetTextAlign);
WCE_IMPORT UINT WINAPI GetTextAlign(HDC) WCE_LINK(GetTextAlign);
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT int WINAPI SetTextCharacterExtra(HDC,int) WCE_LINK(SetTextCharacterExtra);
#endif
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT int WINAPI GetTextCharacterExtra(HDC) WCE_LINK(GetTextCharacterExtra);
#endif
WCE_IMPORT BOOL WINAPI GetCharWidth32(HDC,UINT,UINT,LPINT) WCE_LINK(GetCharWidth32);
WCE_IMPORT BOOL WINAPI GetCharABCWidths(HDC,UINT,UINT,LPABC) WCE_LINK(GetCharABCWidths);
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT DWORD WINAPI GetFontData(HDC,DWORD,DWORD,LPVOID,DWORD) WCE_LINK(GetFontData);
#endif
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT BOOL WINAPI GetCharABCWidthsI(HDC,UINT,UINT,LPWORD,LPABC) WCE_LINK(GetCharABCWidthsI);
#endif
WCE_IMPORT UINT WINAPI GetOutlineTextMetricsA(HDC,UINT,LPOUTLINETEXTMETRICA) WCE_LINK(GetOutlineTextMetricsA);
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT UINT WINAPI GetOutlineTextMetricsW(HDC,UINT,LPOUTLINETEXTMETRICW) WCE_LINK(GetOutlineTextMetricsW);
#endif
#if (_WIN32_WCE >= 0x600)
WCE_IMPORT HANDLE WINAPI AddFontMemResourceEx(PVOID,DWORD,PVOID,DWORD*) WCE_LINK(AddFontMemResourceEx);
#endif
#if (_WIN32_WCE >= 0x600)
WCE_IMPORT BOOL WINAPI RemoveFontMemResourceEx(HANDLE) WCE_LINK(RemoveFontMemResourceEx);
#endif
WCE_IMPORT int WINAPI DrawTextA(HDC,LPCSTR,int,RECT *,UINT) WCE_LINK(DrawTextA);
WCE_IMPORT int WINAPI GetTextFaceA(HDC hdc, int c, LPSTR lpName) WCE_LINK(GetTextFaceA);
WCE_IMPORT int WINAPI GetTextFaceW(HDC hdc, int c, LPWSTR lpName) WCE_LINK(GetTextFaceW);
WCE_IMPORT BOOL WINAPI EnableEUDC(BOOL) WCE_LINK(EnableEUDC);
WCE_IMPORT BOOL WINAPI TranslateCharsetInfo(DWORD *, LPCHARSETINFO, DWORD dwFlags) WCE_LINK(TranslateCharsetInfo);
WCE_IMPORT HBITMAP WINAPI CreateDIBSection(HDC,CONST BITMAPINFO *,UINT,VOID **,HANDLE,DWORD) WCE_LINK(CreateDIBSection);
WCE_IMPORT BOOL WINAPI RestoreDC(HDC,int) WCE_LINK(RestoreDC);
WCE_IMPORT int WINAPI SaveDC(HDC) WCE_LINK(SaveDC);
WCE_IMPORT HPALETTE WINAPI CreatePalette(CONST LOGPALETTE *) WCE_LINK(CreatePalette);
WCE_IMPORT UINT WINAPI GetNearestPaletteIndex(HPALETTE, COLORREF) WCE_LINK(GetNearestPaletteIndex);
WCE_IMPORT UINT WINAPI GetPaletteEntries(HPALETTE h, UINT start, UINT count, LPPALETTEENTRY lppe) WCE_LINK(GetPaletteEntries);
WCE_IMPORT UINT WINAPI GetSystemPaletteEntries(HDC hdc, UINT iStart, UINT n, LPPALETTEENTRY lppe) WCE_LINK(GetSystemPaletteEntries);
WCE_IMPORT UINT WINAPI RealizePalette(HDC) WCE_LINK(RealizePalette);
WCE_IMPORT HPALETTE WINAPI SelectPalette(HDC, HPALETTE, BOOL) WCE_LINK(SelectPalette);
WCE_IMPORT UINT WINAPI SetPaletteEntries(HPALETTE, UINT, UINT, CONST PALETTEENTRY *) WCE_LINK(SetPaletteEntries);
WCE_IMPORT COLORREF WINAPI GetNearestColor(HDC, COLORREF) WCE_LINK(GetNearestColor);
WCE_IMPORT int WINAPI AbortDoc(HDC) WCE_LINK(AbortDoc);
WCE_IMPORT int WINAPI EndDoc(HDC) WCE_LINK(EndDoc);
WCE_IMPORT int WINAPI EndPage(HDC) WCE_LINK(EndPage);
WCE_IMPORT int WINAPI StartDocA(HDC, CONST DOCINFOA *) WCE_LINK(StartDocA);
WCE_IMPORT int WINAPI StartDocW(HDC, CONST DOCINFOW *) WCE_LINK(StartDocW);
WCE_IMPORT int WINAPI StartPage(HDC) WCE_LINK(StartPage);
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT DWORD WINAPI SetLayout(HDC , DWORD) WCE_LINK(SetLayout);
#endif
#if (_WIN32_WCE >= 0x500)
WCE_IMPORT DWORD WINAPI GetLayout(HDC) WCE_LINK(GetLayout);
#endif
WCE_IMPORT int WINAPI SetMapMode(HDC, int) WCE_LINK(SetMapMode);
#if (_WIN32_WCE >= 0x420 && _WIN32_WCE < 0x600)
WCE_IMPORT BOOL WINAPI SetViewportExtEx(HDC hdc, int x, int y, LPSIZE lpsz) WCE_LINK(SetViewportExtEx);
#endif
WCE_IMPORT int WINAPI GetDIBits(HDC, HBITMAP, UINT, UINT, LPVOID, LPBITMAPINFO, UINT) WCE_LINK(GetDIBits);
#if (_WIN32_WCE >= 0x420 && _WIN32_WCE < 0x600)
WCE_IMPORT LONG WINAPI GetBitmapBits(HBITMAP, LONG, LPVOID) WCE_LINK(GetBitmapBits);
#endif
#if (_WIN32_WCE >= 0x420 && _WIN32_WCE < 0x600)
WCE_IMPORT BOOL WINAPI SetWindowExtEx(HDC hdc, int x, int y, LPSIZE lpsz) WCE_LINK(SetWindowExtEx);
#endif
WCE_IMPORT BOOL WINAPI GradientFill(HDC,PTRIVERTEX,ULONG,PVOID,ULONG,ULONG) WCE_LINK(GradientFill);
#if (_WIN32_WCE >= 0x500)
#endif

#define GetObject GetObjectW
#define AddFontResource AddFontResourceW
#define ExtTextOut ExtTextOutW
#define GetTextExtentExPoint GetTextExtentExPointW
#define GetTextMetrics GetTextMetricsW
#define RemoveFontResource RemoveFontResourceW
#define GetOutlineTextMetrics GetOutlineTextMetricsW
#define GetTextFace GetTextFaceW
#define StartDoc StartDocW
#define BS_HOLLOW BS_NULL
#ifdef __cplusplus
}
#endif
#define R2_MASKNOTPEN 3
#define ETO_OPAQUE 0x0002
#define BI_RGB 0
#define TA_LEFT 0
#define LF_FACESIZE 32
#define BS_PATTERN8X8 7
#define BS_INDEXED 4
#define BS_NULL 1
#define R2_NOP 11
#define R2_NOTCOPYPEN 4
#define R2_NOT 6
#define OPAQUE 2
#define FW_EXTRALIGHT 200
#define FF_ROMAN (1<<4)
#define BS_DIBPATTERN 5
#define FW_LIGHT 300
#define FF_DONTCARE (0<<4)
#define R2_MERGENOTPEN 12
#define NULL_PEN 8
#define BI_FOURCC 7L
#define ETO_RTLREADING 0x0080
#define TA_TOP 0
#define FF_DECORATIVE (5<<4)
#define DRAFT_QUALITY 1
#define VARIABLE_PITCH 2
#define R2_WHITE 16
#define OUT_RASTER_PRECIS 6
#define ETO_IGNORELANGUAGE 0x1000
#define FIXED_PITCH 1
#define TRANSPARENT 1
#define BI_BITFIELDS 3L
#define WHITENESS (DWORD)0x00FF0062
#define FW_SEMIBOLD 600
#define SRCPAINT (DWORD)0x00EE0086
#define WHITE_BRUSH 0
#define WHITE_PEN 6
#define ETO_CLIPPED 0x0004
#define FF_SCRIPT (4<<4)
#define MERGECOPY (DWORD)0x00C000CA
#define SRCAND (DWORD)0x008800C6
#define PS_SOLID 0
#define BS_DIBPATTERN8X8 8
#define BS_DIBPATTERNPT 6
#define R2_XORPEN 7
#define FW_HEAVY 900
#define BLACK_BRUSH 4
#define ANSI_CHARSET 0
#define TA_RIGHT 2
#define MERGEPAINT (DWORD)0x00BB0226
#define FW_EXTRABOLD 800
#define FW_BOLD 700
#define R2_NOTMERGEPEN 2
#define DEFAULT_CHARSET 1
#define R2_MERGEPEN 15
#define NOTSRCCOPY (DWORD)0x00330008
#define TA_CENTER 6
#define FW_MEDIUM 500
#define TA_BASELINE 24
#define BI_ALPHABITFIELDS 6L
#define R2_LAST 16
#define CLIP_DEFAULT_PRECIS 0
#define BS_MONOPATTERN 9
#define TA_RTLREADING 256
#define R2_NOTMASKPEN 8
#define NOTSRCERASE (DWORD)0x001100A6
#define SRCINVERT (DWORD)0x00660046
#define TA_BOTTOM 8
#define PS_NULL 5
#define OUT_STRING_PRECIS 1
#define DSTINVERT (DWORD)0x00550009
#define R2_MERGEPENNOT 14
#define FW_THIN 100
#define CLIP_STROKE_PRECIS 2
#define BS_PATTERN 3
#define SRCERASE (DWORD)0x00440328
#define PATCOPY (DWORD)0x00F00021
#define R2_NOTXORPEN 10
#define R2_MASKPENNOT 5
#define FW_DONTCARE 0
#define SRCCOPY (DWORD)0x00CC0020
#define DEFAULT_QUALITY 0
#define FF_MODERN (3<<4)
#define R2_MASKPEN 9
#define TA_UPDATECP 1
#define PATINVERT (DWORD)0x005A0049
#define R2_COPYPEN 13
#define PATPAINT (DWORD)0x00FB0A09
#define FF_SWISS (2<<4)
#define BI_SRCPREROTATE 0x8000
#define TA_NOUPDATECP 0
#define PS_DASH 1
#define FW_NORMAL 400
#define BS_SOLID 0
#define BLACKNESS (DWORD)0x00000042
#define NULL_BRUSH 5
#define OUT_DEFAULT_PRECIS 0
#define BLACK_PEN 7
#define R2_BLACK 1
#define CLIP_CHARACTER_PRECIS 1
#define TA_ALIGNMASK (TA_BASELINE | TA_CENTER )
#define TA_MASK (TA_BASELINE | TA_CENTER |TA_UPDATECP |TA_RTLREADING)
#endif

