/* Akari WinCE Development API Surface
 * Independently authored declarations for linking Windows CE 6.0 programs.
 * This is an API surface only: not an OS, BSP, OAK, SDK component, or
 * Platform Builder redistribution, and not a copy of upstream source.
 * CE calling convention: stdcall is cdecl, and DLL export names are
 * undecorated. TCHAR is a 16-bit WCHAR. Layouts that differ from desktop
 * Win32 (CRITICAL_SECTION, WIN32_FIND_DATAW, BY_HANDLE_FILE_INFORMATION,
 * OVERLAPPED) follow the CE 6.0 ABI.
 */

#ifndef AKARI_WINUSER_H
#define AKARI_WINUSER_H
#include "windef.h"
#include "winbase.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LRESULT (CALLBACK *WNDPROC)(HWND, UINT, WPARAM, LPARAM);
typedef VOID (CALLBACK *TIMERPROC)(HWND, UINT, UINT, DWORD);

typedef struct tagMSG {
    HWND hwnd;
    UINT message;
    WPARAM wParam;
    LPARAM lParam;
    DWORD time;
    POINT pt;
} MSG, *PMSG, *NPMSG, *LPMSG;

typedef struct tagWNDCLASSW {
    UINT style;
    WNDPROC lpfnWndProc;
    int cbClsExtra;
    int cbWndExtra;
    HINSTANCE hInstance;
    HICON hIcon;
    HCURSOR hCursor;
    HBRUSH hbrBackground;
    LPCWSTR lpszMenuName;
    LPCWSTR lpszClassName;
} WNDCLASSW, *PWNDCLASSW, *NPWNDCLASSW, *LPWNDCLASSW;
typedef WNDCLASSW WNDCLASS;
typedef LPWNDCLASSW LPWNDCLASS;

typedef struct tagPAINTSTRUCT {
    HDC hdc;
    BOOL fErase;
    RECT rcPaint;
    BOOL fRestore;
    BOOL fIncUpdate;
    BYTE rgbReserved[32];
} PAINTSTRUCT, *PPAINTSTRUCT, *NPPAINTSTRUCT, *LPPAINTSTRUCT;

typedef struct tagCREATESTRUCTW {
    LPVOID lpCreateParams;
    HINSTANCE hInstance;
    HMENU hMenu;
    HWND hwndParent;
    int cy;
    int cx;
    int y;
    int x;
    LONG style;
    LPCWSTR lpszName;
    LPCWSTR lpszClass;
    DWORD dwExStyle;
} CREATESTRUCTW, *LPCREATESTRUCTW;

#define MAKEINTRESOURCEW(i) ((LPWSTR)(ULONG_PTR)(WORD)(i))
#define MAKEINTRESOURCE MAKEINTRESOURCEW
#define HWND_TOP ((HWND)0)
#define HWND_BOTTOM ((HWND)1)
#define HWND_TOPMOST ((HWND)-1)
#define HWND_NOTOPMOST ((HWND)-2)
#define CW_USEDEFAULT ((int)0x80000000)

#define BS_GROUPBOX 0x00000007L
#define WM_MBUTTONDOWN 0x0207
#define DCX_INTERSECTRGN 0x00000080L
#define TPM_CENTERALIGN 0x0004L
#define CBS_DROPDOWNLIST 0x0003L
#define GWL_STYLE (-16)
#define WS_VISIBLE 0x10000000L
#define HTHSCROLL 6
#define SPI_GETMOUSEKEYS 54
#define SMTO_NORMAL 0x0000
#define WM_QUERYNEWPALETTE 0x030F
#define VK_RIGHT 0x27
#define SB_PAGEUP 2
#define SWP_FRAMECHANGED 0x0020
#define SPI_SETSOUNDSENTRY 65
#define SS_CENTERIMAGE 0x00000200L
#define DFCS_SCROLLUP 0x0000
#define VK_CRSEL 0xF7
#define DFCS_CAPTIONHELP 0x0004
#define SPI_GETEXTERNALIDLETIMEOUT 254
#define BS_PUSHLIKE 0x00001000L
#define VK_CAPITAL 0x14
#define SPI_GETDEFAULTINPUTLANG 89
#define VK_DBE_ENTERIMECONFIGMODE 0x0f8
#define WS_EX_ABOVESTARTUP 0x20000000L
#define SC_KEYMENU 0xF100
#define WM_SYSKEYUP 0x0105
#define WM_IME_REQUEST 0x0288
#define SPI_SETSHOWSOUNDS 57
#define MK_XBUTTON1 0x0020
#define MK_XBUTTON2 0x0040
#define SW_RESTORE 13
#define MF_ENABLED 0x00000000L
#define VK_MBUTTON 0x04
#define VK_KANA 0x15
#define MB_SETFOREGROUND 0x00010000L
#define SB_BOTTOM 7
#define VK_PAUSE 0x13
#define SPI_GETTOGGLEKEYS 52
#define HTCLIENT 1
#define VK_LBRACKET 0xDB
#define VK_DBE_ENTERWORDREGISTERMODE 0x0f7
#define SPI_GETPLATFORMMANUFACTURER 262
#define SM_CYBORDER 6
#define SM_CXFULLSCREEN 16
#define MB_CUR_MAX 1
#define WM_IME_CONTROL 0x0283
#define MK_MBUTTON 0x0010
#define MF_END 0x00000080L
#define SPI_SETMOUSE 4
#define DLGC_WANTTAB 0x0002
#define BS_LEFTTEXT 0x00000020L
#define SPI_SETACCESSTIMEOUT 61
#define VK_MEDIA_PREV_TRACK 0xB1
#define VK_VOLUME_UP 0xAF
#define WS_SYSMENU 0x00080000L
#define BF_TOP 0x0002
#define WM_QUIT 0x0012
#define SPI_GETHIGHCONTRAST 66
#define DI_NORMAL 0x0003
#define SB_PAGEDOWN 3
#define SM_CYDLGFRAME 8
#define WM_IME_SYSTEM 0x0287
#define CBN_DBLCLK 2
#define GW_HWNDLAST 1
#define WM_CLOSE 0x0010
#define HTBOTTOMLEFT 16
#define SPI_GETSCREENSAVETIMEOUT 14
#define WM_IM_INFO 0x010C
#define SW_SHOWMAXIMIZED 11
#define MB_RTLREADING 0x00100000L
#define SWP_NOMOVE 0x0002
#define VK_LAUNCH_MEDIA_SELECT 0xB5
#define MB_ICONQUESTION 0x00000020L
#define VK_NONAME 0xFC
#define DFCS_SCROLLRIGHT 0x0003
#define MB_ICONASTERISK 0x00000040L
#define KF_ALTDOWN 0x2000
#define EN_SETFOCUS 0x0100
#define STN_DISABLE 3
#define GW_HWNDFIRST 0
#define ES_USER_PRESENT ((DWORD)0x00000004)
#define WM_HIBERNATE 0x03FF
#define ODS_DISABLED 0x0004
#define LBS_OWNERDRAWFIXED 0x0010L
#define SB_LINEUP 0
#define MB_ICONINFORMATION MB_ICONASTERISK
#define BS_TOP 0x00000400L
#define VK_F20 0x83
#define VK_LWIN 0x5B
#define SWP_NOZORDER 0x0004
#define RDW_VALIDATE 0x0008
#define WS_HSCROLL 0x00100000L
#define VK_DBE_KATAKANA 0x0f1
#define SM_CXICON 11
#define PM_REMOVE 0x0001
#define WS_MINIMIZEBOX 0x00010000L
#define DFCS_BUTTONPUSH 0x0010
#define VK_F10 0x79
#define VK_SELECT 0x29
#define SM_CXVIRTUALSCREEN 78
#define WM_KEYDOWN 0x0100
#define WM_XBUTTONDOWN 0x020B
#define VK_DBE_ALPHANUMERIC 0x0f0
#define SPIF_UPDATEINIFILE 0x0001
#define SS_LEFTNOWORDWRAP 0x0000000CL
#define DFCS_CAPTIONMIN 0x0001
#define SM_CYICON 12
#define WM_KEYFIRST 0x0100
#define SPI_GETBATTERYIDLETIMEOUT 252
#define SPI_GETGUIDPATTERN 264
#define WM_TIMER 0x0113
#define WM_ACTIVATE 0x0006
#define VK_RBRACKET 0xDD
#define CBN_CLOSEUP 8
#define CBS_EX_CONSTSTRINGDATA 0x00000002L
#define LBS_SORT 0x0002L
#define WM_XBUTTONDBLCLK 0x020D
#define EN_HSCROLL 0x0601
#define WM_LBUTTONDBLCLK 0x0203
#define SPI_SETLANGTOGGLE 91
#define SB_LEFT 6
#define VK_F15 0x7E
#define BS_BOTTOM 0x00000800L
#define BS_OWNERDRAW 0x0000000BL
#define VK_PERIOD 0xBE
#define VK_F17 0x80
#define ODS_GRAYED 0x0002
#define MB_ICONHAND 0x00000010L
#define VK_SLASH 0xBF
#define LBS_NOTIFY 0x0001L
#define SM_CYVIRTUALSCREEN 79
#define SM_CYSMICON 50
#define WM_APP 0x8000
#define SW_SHOWNORMAL 1
#define OEM_CERTIFY_FALSE 0
#define GWL_EXSTYLE (-20)
#define VK_MEDIA_PLAY_PAUSE 0xB3
#define MB_ICONSTOP MB_ICONHAND
#define CTLCOLOR_MSGBOX 0
#define VK_NUMPAD3 0x63
#define MF_HILITE 0x00000080L
#define VK_LAUNCH_APP1 0xB6
#define QS_TIMER 0x0010
#define HTTOPLEFT 13
#define KF_REPEAT 0x4000
#define SPI_GETSTICKYKEYS 58
#define WM_CONTEXTMENU 0x007B
#define SB_VERT 1
#define GW_MAX 5
#define VK_LMENU 0xA4
#define MIIM_ID 0x00000002
#define VK_SEPARATOR 0x6C
#define HTTRANSPARENT (-1)
#define WM_IME_KEYUP 0x0291
#define CTLCOLOR_BTN 3
#define VK_INSERT 0x2D
#define WS_CLIPSIBLINGS 0x04000000L
#define GW_HWNDPREV 3
#define WS_VSCROLL 0x00200000L
#define QS_MOUSEMOVE 0x0002
#define SW_MAXIMIZE 12
#define MF_UNHILITE 0x00000000L
#define VK_OEM_102 0xE2
#define WM_SETICON 0x0080
#define HTMAXBUTTON 9
#define WM_HELP 0x0053
#define WM_CREATE 0x0001
#define SPI_SETDESKWALLPAPER 20
#define WM_ERASEBKGND 0x0014
#define EN_ALIGN_LTR_EC 0x0700
#define SM_CYICONSPACING 39
#define BS_3STATE 0x00000005L
#define CBN_SELENDOK 9
#define ES_READONLY 0x0800L
#define VK_ESCAPE 0x1B
#define CTLCOLOR_MAX 7
#define ES_CENTER 0x0001L
#define HTGROWBOX 4
#define VK_END 0x23
#define TPM_VCENTERALIGN 0x0010L
#define WM_SYSKEYDOWN 0x0104
#define SPI_SETWHEELSCROLLLINES 105
#define CTLCOLOR_STATIC 6
#define WM_MOUSEFIRST 0x0200
#define SPIF_SENDCHANGE 0x0002
#define MB_RETRYCANCEL 0x00000005L
#define BS_RIGHTBUTTON BS_LEFTTEXT
#define WM_MEASUREITEM 0x002C
#define SPI_SETHIGHCONTRAST 67
#define SPI_SETFONTSMOOTHING 0x004B
#define TPM_LEFTALIGN 0x0000L
#define SM_CXCURSOR 13
#define DLGC_BUTTON 0x2000
#define VK_NUMPAD8 0x68
#define WM_CTLCOLOREDIT 0x0133
#define STN_ENABLE 2
#define HTBOTTOMRIGHT 17
#define MB_ICONERROR MB_ICONHAND
#define VK_NUMPAD9 0x69
#define EN_MAXTEXT 0x0501
#define WM_NOTIFY 0x004E
#define LBS_EXTENDEDSEL 0x0800L
#define VK_PLAY 0xFA
#define VK_F1 0x70
#define VK_F4 0x73
#define WM_SETREDRAW 0x000B
#define VK_F6 0x75
#define VK_F7 0x76
#define VK_F9 0x78
#define WM_MOVE 0x0003
#define SB_PAGERIGHT 3
#define ODA_DRAWENTIRE 0x0001
#define MF_STRING 0x00000000L
#define CS_SAVEBITS 0x0800
#define LBN_KILLFOCUS 5
#define EN_KILLFOCUS 0x0200
#define TPM_TOPALIGN 0x0000L
#define SS_BITMAP 0x0000000EL
#define WM_DEADCHAR 0x0103
#define HWND_BROADCAST ((HWND)0xffff)
#define WM_CHAR 0x0102
#define MF_BYPOSITION 0x00000400L
#define GWL_WNDPROC (-4)
#define VK_F3 0x72
#define VK_F5 0x74
#define VK_F2 0x71
#define RDW_INVALIDATE 0x0001
#define WM_DESTROYCLIPBOARD 0x0307
#define HTMENU 5
#define BS_AUTO3STATE 0x00000006L
#define WM_UNDO 0x0304
#define QS_MOUSEBUTTON 0x0004
#define VK_F8 0x77
#define VK_MULTIPLY 0x6A
#define SB_LINERIGHT 1
#define CBN_EDITUPDATE 6
#define ES_MULTILINE 0x0004L
#define VK_DOWN 0x28
#define SM_CXDLGFRAME 7
#define MF_MENUBREAK 0x00000040L
#define VK_NUMPAD0 0x60
#define WS_EX_NODRAG 0x40000000L
#define WM_GETFONT 0x0031
#define VK_NUMPAD5 0x65
#define VK_DBE_ROMAN 0x0f5
#define SYS_COLOR_INDEX_FLAG 0x40000000
#define WM_INITDIALOG 0x0110
#define CTLCOLOR_EDIT 1
#define BS_RIGHT 0x00000200L
#define ES_AUTOVSCROLL 0x0040L
#define SB_CTL 2
#define RDW_ERASE 0x0004
#define SB_THUMBTRACK 5
#define VK_BROWSER_FAVORITES 0xAB
#define WA_ACTIVE 1
#define QS_SENDMESSAGE 0x0040
#define VK_PA1 0xFD
#define SWP_DRAWFRAME SWP_FRAMECHANGED
#define WS_TABSTOP 0x00010000L
#define WM_IME_ENDCOMPOSITION 0x010E
#define ODS_CHECKED 0x0008
#define WM_DESTROY 0x0002
#define WS_EX_RIGHT 0x00001000L
#define HWND_DESKTOP ((HWND)0)
#define KF_UP 0x8000
#define OEM_CERTIFY_RUN 1
#define VK_DELETE 0x2E
#define MIIM_SUBMENU 0x00000004
#define DFCS_CAPTIONALL 0x000F
#define HTSIZE HTGROWBOX
#define MFT_RADIOCHECK 0x00000200L
#define SIZE_MAXHIDE 4
#define ODA_SELECT 0x0002
#define DCX_CACHE 0x00000002L
#define SW_SHOWNA 8
#define LBS_DISABLENOSCROLL 0x1000L
#define BS_AUTORADIOBUTTON 0x00000009L
#define WM_RBUTTONDBLCLK 0x0206
#define ODS_SELECTED 0x0001
#define DCX_CLIPCHILDREN 0x00000008L
#define SWP_NOSIZE 0x0001
#define VK_DBE_CODEINPUT 0x0fa
#define KF_EXTENDED 0x0100
#define VK_SUBTRACT 0x6D
#define VK_DBE_NOCODEINPUT 0x0fb
#define WS_EX_CLIENTEDGE 0x00000200L
#define SM_CXICONSPACING 38
#define DFCS_CAPTIONRESTORE 0x0003
#define VK_NUMPAD1 0x61
#define VK_NUMPAD2 0x62
#define VK_NUMPAD4 0x64
#define VK_NUMPAD6 0x66
#define VK_NUMPAD7 0x67
#define CBN_SETFOCUS 3
#define VK_HANGEUL 0x15
#define HTHELP 21
#define VK_F12 0x7B
#define ES_LEFT 0x0000L
#define SPI_GETPLATFORMNAME 260
#define BS_DEFPUSHBUTTON 0x00000001L
#define WM_VKEYTOITEM 0x002E
#define LBN_SELCANCEL 3
#define HTRIGHT 11
#define VK_DBE_NOROMAN 0x0f6
#define SM_CXDOUBLECLK 36
#define VK_HANJA 0x19
#define WM_COPYDATA 0x004A
#define LBS_EX_CONSTSTRINGDATA 0x00000002L
#define SM_CYDOUBLECLK 37
#define DI_MASK 0x0001
#define CS_IME 0x00010000
#define HTNOWHERE 0
#define WS_POPUP 0x80000000L
#define VK_APOSTROPHE 0xDE
#define VK_UP 0x26
#define MB_DEFBUTTON2 0x00000100L
#define SPI_GETSHOWSOUNDS 56
#define VK_F16 0x7F
#define TPM_VERTICAL 0x0040L
#define VK_F18 0x81
#define CBS_DISABLENOSCROLL 0x0800L
#define WS_EX_TOPMOST 0x00000008L
#define LBS_NOREDRAW 0x0004L
#define SM_CXHSCROLL 21
#define MIIM_CHECKMARKS 0x00000008
#define COLOR_3DLIGHT (22 | SYS_COLOR_INDEX_FLAG)
#define WM_RBUTTONUP 0x0205
#define SM_SAMEDISPLAYFORMAT 81
#define VK_RSHIFT 0xA1
#define HTERROR (-2)
#define VK_HANGUL 0x15
#define ES_NUMBER 0x2000L
#define VK_LSHIFT 0xA0
#define GWL_USERDATA (-21)
#define SM_XVIRTUALSCREEN 76
#define MB_APPLMODAL 0x00000000L
#define WM_ENTERMENULOOP 0x0211
#define WM_GETTEXTLENGTH 0x000E
#define SW_INVALIDATE 0x0002
#define MF_MENUBARBREAK 0x00000020L
#define PM_NOREMOVE 0x0000
#define VK_DECIMAL 0x6E
#define WM_SYSCOLORCHANGE 0x0015
#define VK_KANJI 0x19
#define VK_DBE_HIRAGANA 0x0f2
#define CBS_LOWERCASE 0x4000L
#define MF_UNCHECKED 0x00000000L
#define DFC_CAPTION 1
#define VK_LCONTROL 0xA2
#define SM_CXBORDER 5
#define STN_CLICKED 0
#define LBS_NODATA 0x2000L
#define EN_CHANGE 0x0300
#define HTSYSMENU 3
#define VK_CLEAR 0x0C
#define COLOR_MENUTEXT ( 7 | SYS_COLOR_INDEX_FLAG)
#define SS_CENTER 0x00000001L
#define SM_CYEDGE 46
#define HTVSCROLL 7
#define WM_MOUSEWHEEL 0x020A
#define SPI_GETOEMINFO 258
#define ODT_MENU 1
#define SB_ENDSCROLL 8
#define BN_CLICKED 0
#define DCX_WINDOW 0x00000001L
#define CTLCOLOR_LISTBOX 2
#define VK_MEDIA_STOP 0xB2
#define VK_SEMICOLON 0xBA
#define EN_ALIGN_RTL_EC 0x0701
#define VK_SPACE 0x20
#define WM_SETFOCUS 0x0007
#define VK_F21 0x84
#define MK_RBUTTON 0x0002
#define DCX_CLIPSIBLINGS 0x00000010L
#define VK_DBE_ENTERDLGCONVERSIONMODE 0x0fd
#define WS_EX_CONTEXTHELP 0x00000400L
#define VK_F22 0x85
#define VK_F23 0x86
#define SIZE_MAXIMIZED 2
#define MFT_STRING MF_STRING
#define WS_EX_LEFTSCROLLBAR 0x00004000L
#define SPI_SETMOUSEKEYS 55
#define DFCS_INACTIVE 0x0100
#define LBN_DBLCLK 2
#define COLOR_BTNHIGHLIGHT (20 | SYS_COLOR_INDEX_FLAG)
#define TPM_HORIZONTAL 0x0000L
#define COLOR_ACTIVECAPTION ( 2 | SYS_COLOR_INDEX_FLAG)
#define SWP_NOOWNERZORDER 0x0200
#define SPI_GETPLATFORMTYPE 257
#define ODA_FOCUS 0x0004
#define GWL_ID (-12)
#define WM_DBNOTIFICATION 0x03FD
#define LBS_NOINTEGRALHEIGHT 0x0100L
#define WM_VSCROLL 0x0115
#define WM_IME_KEYLAST 0x010F
#define MB_OKCANCEL 0x00000001L
#define CS_DBLCLKS 0x0008
#define BS_RADIOBUTTON 0x00000004L
#define SPI_SETWAKEUPIDLETIMEOUT 255
#define QS_PAINT 0x0020
#define VK_XBUTTON1 0x05
#define VK_XBUTTON2 0x06
#define CBS_AUTOHSCROLL 0x0040L
#define COLOR_HIGHLIGHT (13 | SYS_COLOR_INDEX_FLAG)
#define WM_SYSCOMMAND 0x0112
#define VK_MENU 0x12
#define WS_EX_TOOLWINDOW 0x00000080L
#define ES_WANTRETURN 0x1000L
#define BN_KILLFOCUS 7
#define WM_ENABLE 0x000A
#define CBS_OEMCONVERT 0x0080L
#define WM_PAINT 0x000F
#define WS_EX_LAYOUTRTL 0x00400000L
#define WM_SETTEXT 0x000C
#define TPM_RETURNCMD 0x0100L
#define DFCS_BUTTONRADIO 0x0004
#define SB_RIGHT 7
#define CS_VREDRAW 0x0001
#define MB_YESNOCANCEL 0x00000003L
#define HTTOP 12
#define WM_QUERYDRAGICON 0x0037
#define SS_NOPREFIX 0x00000080L
#define MF_GRAYED 0x00000001L
#define RDW_NOCHILDREN 0x0040
#define WM_SYSCHAR 0x0106
#define VK_HYPHEN 0xBD
#define WS_EX_INK 0x10000000L
#define WM_NULL 0x0000
#define VK_BROWSER_SEARCH 0xAA
#define SPI_GETSOUNDSENTRY 64
#define RDW_ERASENOW 0x0200
#define ES_DISPLAY_REQUIRED ((DWORD)0x00000002)
#define WS_CHILD 0x40000000L
#define DLGC_WANTALLKEYS 0x0004
#define HTCAPTION 2
#define WM_COPY 0x0301
#define DFCS_BUTTON3STATE 0x0008
#define WM_LBUTTONDOWN 0x0201
#define BF_RIGHT 0x0004
#define ES_COMBOBOX 0x0200L
#define QS_KEY 0x0001
#define COLOR_INACTIVEBORDER (11 | SYS_COLOR_INDEX_FLAG)
#define COLOR_BTNTEXT (18 | SYS_COLOR_INDEX_FLAG)
#define ICON_BIG 1
#define RDW_UPDATENOW 0x0100
#define CBN_ERRSPACE (-1)
#define COLOR_WINDOWFRAME ( 6 | SYS_COLOR_INDEX_FLAG)
#define WM_FONTCHANGE 0x001D
#define RDW_ALLCHILDREN 0x0080
#define COLOR_STATIC (25 | SYS_COLOR_INDEX_FLAG)
#define VK_TAB 0x09
#define CBS_HASSTRINGS 0x0200L
#define WM_STYLECHANGED 0x007D
#define ES_RIGHT 0x0002L
#define VK_EXTEND_BSLASH 0xE2
#define SM_CXEDGE 45
#define MB_TOPMOST 0x00040000L
#define DFCS_SCROLLCOMBOBOX 0x0005
#define VK_LAUNCH_MAIL 0xB4
#define WM_MOUSEMOVE 0x0200
#define SM_CMONITORS 80
#define CS_NOCLOSE 0x0200
#define VK_ATTN 0xF6
#define BS_VCENTER 0x00000C00L
#define SM_YVIRTUALSCREEN 77
#define VK_EXSEL 0xF8
#define VK_NOCONVERT 0x1d
#define MFS_ENABLED MF_ENABLED
#define EN_UPDATE 0x0400
#define SIZE_MAXSHOW 3
#define SWP_NOACTIVATE 0x0010
#define VK_BROWSER_STOP 0xA9
#define VK_SNAPSHOT 0x2C
#define VK_CONTROL 0x11
#define CBS_DROPDOWN 0x0002L
#define SM_CXVSCROLL 2
#define VK_BACKSLASH 0xDC
#define VK_EREOF 0xF9
#define SM_MOUSEPRESENT 19
#define BS_MULTILINE 0x00002000L
#define EN_VSCROLL 0x0602
#define DI_IMAGE 0x0002
#define LBS_NOSEL 0x4000L
#define DFCS_CAPTIONMAX 0x0002
#define SPI_GETMOUSE 3
#define VK_BROWSER_REFRESH 0xA8
#define WM_MOUSELAST 0x020D
#define MK_SHIFT 0x0004
#define VK_RBUTTON 0x02
#define BF_SOFT 0x1000
#define WM_CTLCOLORSTATIC 0x0138
#define SPI_SETBATTERYIDLETIMEOUT 251
#define HTZOOM HTMAXBUTTON
#define WM_IME_SETCONTEXT 0x0281
#define VK_FINAL 0x18
#define SW_MINIMIZE 6
#define IMAGE_BITMAP 0
#define VK_RCONTROL 0xA3
#define DFCS_PUSHED 0x0200
#define SWP_HIDEWINDOW 0x0080
#define SC_CLOSE 0xF060
#define WS_EX_RTLREADING 0x00002000L
#define MB_DEFBUTTON4 0x00000300L
#define ODT_COMBOBOX 3
#define WM_MBUTTONUP 0x0208
#define VK_CONVERT 0x1c
#define SM_CYVSCROLL 20
#define BF_MONO 0x8000
#define MF_BYCOMMAND 0x00000000L
#define WM_RENDERFORMAT 0x0305
#define EN_ERRSPACE 0x0500
#define WS_EX_DLGMODALFRAME 0x00000001L
#define SPI_SETTOGGLEKEYS 53
#define SS_RIGHT 0x00000002L
#define WM_PALETTECHANGED 0x0311
#define CBS_UPPERCASE 0x2000L
#define VK_HOME 0x24
#define WM_MENUCHAR 0x0120
#define DCX_EXCLUDEUPDATE 0x00000100L
#define ICON_SMALL 0
#define VK_JUNJA 0x17
#define WM_WINDOWPOSCHANGED 0x0047
#define WS_BORDER 0x00800000L
#define HTCLOSE 20
#define VK_OFF 0xDF
#define VK_SCROLL 0x91
#define GW_CHILD 5
#define VK_EQUAL 0xBB
#define WM_IME_NOTIFY 0x0282
#define BF_LEFT 0x0001
#define LBS_HASSTRINGS 0x0040L
#define SM_CYMENU 15
#define HTLEFT 10
#define SS_ICON 0x00000003L
#define WS_THICKFRAME 0x00040000L
#define VK_F11 0x7A
#define VK_F13 0x7C
#define VK_F19 0x82
#define COLOR_WINDOW ( 5 | SYS_COLOR_INDEX_FLAG)
#define CS_PARENTDC 0x0080
#define WS_MAXIMIZEBOX 0x00020000L
#define WM_USER 0x0400
#define TPM_BOTTOMALIGN 0x0020L
#define SM_DEBUG 22
#define VK_DIVIDE 0x6F
#define DFCS_SCROLLLEFT 0x0002
#define WA_CLICKACTIVE 2
#define VK_DBE_FLUSHSTRING 0x0f9
#define WM_IME_COMPOSITIONFULL 0x0284
#define CBS_SORT 0x0100L
#define DFCS_SCROLLDOWN 0x0001
#define WM_RENDERALLFORMATS 0x0306
#define CS_HREDRAW 0x0002
#define WM_IME_KEYDOWN 0x0290
#define WS_EX_STATICEDGE 0x00020000L
#define ODT_LISTBOX 2
#define MIIM_TYPE 0x00000010
#define WM_IME_CHAR 0x0286
#define BS_AUTOCHECKBOX 0x00000003L
#define BN_DBLCLK 5
#define VK_BACK 0x08
#define WM_KILLFOCUS 0x0008
#define ES_SYSTEM_REQUIRED ((DWORD)0x00000001)
#define ES_AUTOHSCROLL 0x0080L
#define MF_OWNERDRAW 0x00000100L
#define WM_DRAWITEM 0x002B
#define MK_CONTROL 0x0008
#define DFCS_CAPTIONOKBTN 0x0080
#define SB_PAGELEFT 2
#define WM_XBUTTONUP 0x020C
#define GW_OWNER 4
#define WM_CTLCOLORMSGBOX 0x0132
#define WS_EX_NOACTIVATE 0x08000000L
#define COLOR_GRADIENTINACTIVECAPTION (28 | SYS_COLOR_INDEX_FLAG)
#define WM_EXITMENULOOP 0x0212
#define SIZE_MINIMIZED 1
#define SWP_NOREPOSITION SWP_NOOWNERZORDER
#define SM_CYCAPTION 4
#define SPI_SETSCREENSAVETIMEOUT 15
#define VK_HELP 0x2F
#define DFC_SCROLL 3
#define SPI_GETFONTSMOOTHING 0x004A
#define WM_KEYLAST 0x0108
#define VK_NEXT 0x22
#define SPI_GETWAKEUPIDLETIMEOUT 256
#define MFS_DEFAULT 0x00001000L
#define LBS_USETABSTOPS 0x0080L
#define VK_BROWSER_BACK 0xA6
#define VK_VOLUME_MUTE 0xAD
#define WM_COMMAND 0x0111
#define DLGC_UNDEFPUSHBUTTON 0x0020
#define ODT_BUTTON 4
#define SM_CYSCREEN 1
#define DLGC_HASSETSEL 0x0008
#define LBS_OWNERDRAWVARIABLE 0x0020L
#define MF_SEPARATOR 0x00000800L
#define WM_CANCELMODE 0x001F
#define MFT_OWNERDRAW MF_OWNERDRAW
#define SM_CYCURSOR 14
#define SM_CXFIXEDFRAME SM_CXDLGFRAME
#define WM_CLEAR 0x0303
#define WS_EX_NOANIMATION 0x04000000L
#define ODS_FOCUS 0x0010
#define VK_BROWSER_FORWARD 0xA7
#define VK_PROCESSKEY 0xE5
#define VK_EXECUTE 0x2B
#define WM_CHARTOITEM 0x002F
#define LBS_WANTKEYBOARDINPUT 0x0400L
#define WM_CTLCOLORBTN 0x0135
#define WM_CTLCOLORLISTBOX 0x0134
#define HTBORDER 18
#define WM_SETCURSOR 0x0020
#define SM_CYFULLSCREEN 17
#define HTBOTTOM 15
#define BS_PUSHBUTTON 0x00000000L
#define VK_APPS 0x5D
#define BN_SETFOCUS 6
#define SBS_HORZ 0x0000L
#define WS_EX_NOINHERITLAYOUT 0x00100000L
#define VK_COMMA 0xBC
#define VK_RMENU 0xA5
#define LR_DEFAULTCOLOR 0x0000
#define MFT_MENUBARBREAK MF_MENUBARBREAK
#define CS_GLOBALCLASS 0x4000
#define CBN_DROPDOWN 7
#define WM_IME_COMPOSITION 0x010F
#define SPI_SETDESKPATTERN 21
#define VK_PRINT 0x2A
#define MFS_UNCHECKED MF_UNCHECKED
#define VK_DBE_SBCSCHAR 0x0f3
#define MB_ABORTRETRYIGNORE 0x00000002L
#define WM_CTLCOLORDLG 0x0136
#define WM_KEYUP 0x0101
#define BF_DIAGONAL 0x0010
#define VK_NUMLOCK 0x90
#define WM_WININICHANGE 0x001A
#define VK_CANCEL 0x03
#define SPI_SETSTICKYKEYS 59
#define SW_SHOWNOACTIVATE 4
#define VK_LAUNCH_APP2 0xB7
#define WS_DISABLED 0x08000000L
#define SM_CXSMICON 49
#define WS_DLGFRAME 0x00400000L
#define DFCS_BUTTONCHECK 0x0000
#define CBN_EDITCHANGE 5
#define VK_RWIN 0x5C
#define SPI_GETWHEELSCROLLLINES 104
#define VK_PRIOR 0x21
#define WM_RBUTTONDOWN 0x0204
#define WM_SETFONT 0x0030
#define VK_LBUTTON 0x01
#define WM_IME_STARTCOMPOSITION 0x010D
#define VK_BACKQUOTE 0xC0
#define SBS_VERT 0x0001L
#define ES_PASSWORD 0x0020L
#define DLGC_RADIOBUTTON 0x0040
#define WM_IME_SELECT 0x0285
#define HTOBJECT 19
#define MB_ICONEXCLAMATION 0x00000030L
#define SB_BOTH 3
#define DLGC_WANTCHARS 0x0080
#define QS_POSTMESSAGE 0x0008
#define ES_LOWERCASE 0x0010L
#define LBS_MULTICOLUMN 0x0200L
#define HTTOPRIGHT 14
#define VK_MEDIA_NEXT_TRACK 0xB0
#define SPI_GETBOOTMENAME 261
#define COLOR_BACKGROUND ( 1 | SYS_COLOR_INDEX_FLAG)
#define BF_ADJUST 0x2000
#define RDW_NOERASE 0x0020
#define COLOR_GRAYTEXT (17 | SYS_COLOR_INDEX_FLAG)
#define DFCS_CAPTIONCLOSE 0x0000
#define SPI_GETACCESSTIMEOUT 60
#define WM_SIZE 0x0005
#define WM_CTLCOLORSCROLLBAR 0x0137
#define CTLCOLOR_SCOLLBAR 5
#define SPI_GETPROJECTNAME 259
#define BS_TEXT 0x00000000L
#define WM_GETTEXT 0x000D
#define WM_CAPTURECHANGED 0x0215
#define BS_CHECKBOX 0x00000002L
#define WS_EX_WINDOWEDGE 0x00000100L
#define DCX_EXCLUDERGN 0x00000040L
#define SW_HIDE 0
#define WM_NEXTDLGCTL 0x0028
#define VK_BROWSER_HOME 0xAC
#define MB_DEFBUTTON1 0x00000000L
#define ES_NOHIDESEL 0x0100L
#define BN_PAINT 1
#define COLOR_INACTIVECAPTION ( 3 | SYS_COLOR_INDEX_FLAG)
#define WM_MBUTTONDBLCLK 0x0209
#define HTMINBUTTON 8
#define MB_DEFBUTTON3 0x00000200L
#define SW_ERASE 0x0004
#define SS_LEFT 0x00000000L
#define DFC_BUTTON 4
#define MFT_MENUBREAK MF_MENUBREAK
#define WM_INITMENUPOPUP 0x0117
#define WS_GROUP 0x00020000L
#define MIIM_DATA 0x00000020
#define COLOR_SCROLLBAR ( 0 | SYS_COLOR_INDEX_FLAG)
#define CBN_KILLFOCUS 4
#define OEM_CERTIFY_TRUST 2
#define SB_LINELEFT 0
#define DLGC_WANTARROWS 0x0001
#define ES_OEMCONVERT 0x0400L
#define SPI_SETFONTSMOOTHINGCONTRAST 0x200D
#define WM_INPUTLANGCHANGE 0x0051
#define MF_POPUP 0x00000010L
#define SS_NOTIFY 0x00000100L
#define PM_NOYIELD 0x0002
#define SWP_SHOWWINDOW 0x0040
#define LBN_SELCHANGE 1
#define VK_F14 0x7D
#define COLOR_3DHIGHLIGHT COLOR_BTNHIGHLIGHT
#define SPI_GETWORKAREA 48
#define SW_SHOW 5
#define LBS_MULTIPLESEL 0x0008L
#define SPI_GETUUID 263
#define BF_DIAGONAL_ENDTOPLEFT (BF_DIAGONAL | BF_TOP | BF_LEFT)
#define HTSIZELAST HTBOTTOMRIGHT
#define WM_LBUTTONUP 0x0202
#define BF_FLAT 0x4000
#define SB_THUMBPOSITION 4
#define GW_HWNDNEXT 2
#define ES_CONTINUOUS ((DWORD)0x80000000)
#define SW_SCROLLCHILDREN 0x0001
#define SPI_SETEXTERNALIDLETIMEOUT 253
#define WM_COMPAREITEM 0x0039
#define VK_SLEEP 0x5F
#define MK_LBUTTON 0x0001
#define DCX_INTERSECTUPDATE 0x00000200L
#define WM_PASTE 0x0302
#define TPM_RIGHTALIGN 0x0008L
#define LBN_ERRSPACE (-2)
#define COLOR_MENU ( 4 | SYS_COLOR_INDEX_FLAG)
#define VK_VOLUME_DOWN 0xAE
#define SM_CYHSCROLL 3
#define SM_CYFIXEDFRAME SM_CYDLGFRAME
#define SB_TOP 6
#define TPM_NONOTIFY 0x0080L
#define SM_CXSCREEN 0
#define DLGC_WANTMESSAGE 0x0004
#define VK_DBE_DETERMINESTRING 0x0fc
#define BS_LEFT 0x00000100L
#define WM_HSCROLL 0x0114
#define IMAGE_CURSOR 2
#define HTSIZEFIRST HTLEFT
#define WS_SIZEBOX WS_THICKFRAME
#define WM_SYSDEADCHAR 0x0107
#define WS_CAPTION 0x00C00000L
#define VK_DBE_DBCSCHAR 0x0f4
#define BF_BOTTOM 0x0008
#define VK_ZOOM 0xFB
#define CBN_SELENDCANCEL 10
#define BF_MIDDLE 0x0800
#define VK_OEM_CLEAR 0xFE
#define COLOR_3DDKSHADOW (21 | SYS_COLOR_INDEX_FLAG)
#define WS_EX_CAPTIONOKBTN 0x80000000L
#define VK_F24 0x87
#define WA_INACTIVE 0
#define CBN_SELCHANGE 1
#define COLOR_BTNFACE (15 | SYS_COLOR_INDEX_FLAG)
#define BS_NOTIFY 0x00004000L
#define VK_RETURN 0x0D
#define RDW_INTERNALPAINT 0x0002
#define WM_GETICON 0x007F
#define SIZE_RESTORED 0
#define VK_LEFT 0x25
#define SPI_SETWORKAREA 47
#define WM_NETCONNECT 0x03FE
#define WM_CUT 0x0300
#define WM_INPUTLANGCHANGEREQUEST 0x0050
#define DLGC_STATIC 0x0100
#define MF_CHECKED 0x00000008L
#define COLOR_INACTIVECAPTIONTEXT (19 | SYS_COLOR_INDEX_FLAG)
#define BS_CENTER 0x00000300L
#define WS_CLIPCHILDREN 0x02000000L
#define CBS_NOINTEGRALHEIGHT 0x0400L
#define COLOR_GRADIENTACTIVECAPTION (27 | SYS_COLOR_INDEX_FLAG)
#define LBN_SETFOCUS 4
#define SPI_GETFONTSMOOTHINGCONTRAST 0x200C
#define MB_YESNO 0x00000004L
#define MIIM_STATE 0x00000001
#define IMAGE_ICON 1
#define SB_HORZ 0
#define ES_UPPERCASE 0x0008L
#define DFCS_CHECKED 0x0400
#define WM_HOTKEY 0x0312
#define SB_LINEDOWN 1
#define WM_DELETEITEM 0x002D
#define MB_LEN_MAX 5
#define MB_OK 0x00000000L
#define VK_ADD 0x6B
#define WM_SHOWWINDOW 0x0018
#define WM_GETDLGCODE 0x0087
#define VK_SHIFT 0x10
#define DLGC_DEFPUSHBUTTON 0x0010
#define COLOR_CAPTIONTEXT ( 9 | SYS_COLOR_INDEX_FLAG)
#define MFS_UNHILITE MF_UNHILITE
#define COLOR_ACTIVEBORDER (10 | SYS_COLOR_INDEX_FLAG)
#define COLOR_APPWORKSPACE (12 | SYS_COLOR_INDEX_FLAG)
#define QS_MOUSE (QS_MOUSEMOVE | QS_MOUSEBUTTON)
#define COLOR_INFOBK (24 | SYS_COLOR_INDEX_FLAG)
#define COLOR_BTNSHADOW (16 | SYS_COLOR_INDEX_FLAG)
#define COLOR_WINDOWTEXT ( 8 | SYS_COLOR_INDEX_FLAG)
#define MFS_HILITE MF_HILITE
#define BF_DIAGONAL_ENDBOTTOMLEFT (BF_DIAGONAL | BF_BOTTOM | BF_LEFT)
#define COLOR_DESKTOP COLOR_BACKGROUND
#define COLOR_3DFACE COLOR_BTNFACE
#define MFT_SEPARATOR MF_SEPARATOR
#define COLOR_HIGHLIGHTTEXT (14 | SYS_COLOR_INDEX_FLAG)
#define BF_DIAGONAL_ENDTOPRIGHT (BF_DIAGONAL | BF_TOP | BF_RIGHT)
#define COLOR_3DHILIGHT COLOR_BTNHIGHLIGHT
#define COLOR_STATICTEXT (26 | SYS_COLOR_INDEX_FLAG)
#define BF_TOPLEFT (BF_TOP | BF_LEFT)
#define COLOR_INFOTEXT (23 | SYS_COLOR_INDEX_FLAG)
#define MB_ICONWARNING MB_ICONEXCLAMATION
#define QS_INPUT (QS_MOUSE | QS_KEY)
#define BF_TOPRIGHT (BF_TOP | BF_RIGHT)
#define BF_BOTTOMRIGHT (BF_BOTTOM | BF_RIGHT)
#define BF_RECT (BF_LEFT | BF_RIGHT | BF_TOP | BF_BOTTOM)
#define WS_OVERLAPPED WS_BORDER | WS_CAPTION
#define WM_SETTINGCHANGE WM_WININICHANGE
#define MFS_CHECKED MF_CHECKED
#define BF_DIAGONAL_ENDBOTTOMRIGHT (BF_DIAGONAL | BF_BOTTOM | BF_RIGHT)
#define HTREDUCE HTMINBUTTON
#define BF_BOTTOMLEFT (BF_BOTTOM | BF_LEFT)
#define LBS_STANDARD (LBS_NOTIFY | LBS_SORT | WS_VSCROLL | WS_BORDER)
#define QS_ALLEVENTS (QS_INPUT | QS_POSTMESSAGE | QS_TIMER | QS_PAINT)
#define WS_EX_OVERLAPPEDWINDOW (WS_EX_WINDOWEDGE | WS_EX_CLIENTEDGE)
#define QS_ALLINPUT (QS_INPUT | QS_POSTMESSAGE | QS_TIMER | QS_PAINT | QS_SENDMESSAGE)
#define COLOR_3DSHADOW COLOR_BTNSHADOW

AKARI_IMPORT BOOL WINAPI DrawFrameControl(HDC, LPRECT, UINT, UINT) AKARI_NAME(DrawFrameControl);
AKARI_IMPORT UINT WINAPI RegisterWindowMessageW(LPCWSTR lpString) AKARI_NAME(RegisterWindowMessageW);
AKARI_IMPORT BOOL WINAPI PostMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(PostMessageW);
AKARI_IMPORT BOOL WINAPI PostThreadMessageW(DWORD idThread, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(PostThreadMessageW);
AKARI_IMPORT VOID WINAPI PostQuitMessage(int nExitCode) AKARI_NAME(PostQuitMessage);
AKARI_IMPORT LRESULT WINAPI SendMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(SendMessageW);
AKARI_IMPORT BOOL WINAPI SendNotifyMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(SendNotifyMessageW);
AKARI_IMPORT DWORD WINAPI GetMessageQueueReadyTimeStamp(HWND hWnd) AKARI_NAME(GetMessageQueueReadyTimeStamp);
AKARI_IMPORT BOOL WINAPI InSendMessage(VOID) AKARI_NAME(InSendMessage);
AKARI_IMPORT DWORD WINAPI GetQueueStatus(UINT flags) AKARI_NAME(GetQueueStatus);
AKARI_IMPORT BOOL WINAPI GetMessageW(LPMSG lpMsg, HWND hWnd , UINT wMsgFilterMin, UINT wMsgFilterMax) AKARI_NAME(GetMessageW);
AKARI_IMPORT BOOL WINAPI PeekMessageW(PMSG pMsg, HWND hWnd , UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg) AKARI_NAME(PeekMessageW);
AKARI_IMPORT BOOL WINAPI TranslateMessage(CONST MSG *pMsg) AKARI_NAME(TranslateMessage);
AKARI_IMPORT LONG WINAPI DispatchMessageW(CONST MSG *lpMsg) AKARI_NAME(DispatchMessageW);
AKARI_IMPORT DWORD WINAPI GetMessagePos(VOID) AKARI_NAME(GetMessagePos);
AKARI_IMPORT UINT WINAPI GetMessageSource(void) AKARI_NAME(GetMessageSource);
AKARI_IMPORT DWORD WINAPI MsgWaitForMultipleObjectsEx(DWORD nCount, LPHANDLE pHandles, DWORD dwMilliseconds, DWORD dwWakeMask, DWORD dwFlags) AKARI_NAME(MsgWaitForMultipleObjectsEx);
AKARI_IMPORT HWND WINAPI GetCapture(VOID) AKARI_NAME(GetCapture);
AKARI_IMPORT HWND WINAPI SetCapture(HWND hWnd) AKARI_NAME(SetCapture);
AKARI_IMPORT BOOL WINAPI ReleaseCapture(VOID) AKARI_NAME(ReleaseCapture);
AKARI_IMPORT BOOL WINAPI MoveWindow(HWND hWnd, int X, int Y, int nWidth, int nHeight, BOOL bRepaint) AKARI_NAME(MoveWindow);
AKARI_IMPORT int WINAPI SetWindowRgn(HWND hwnd, HRGN hrgn, BOOL bRedraw) AKARI_NAME(SetWindowRgn);
AKARI_IMPORT int WINAPI GetWindowRgn(HWND hwnd, HRGN hrgn) AKARI_NAME(GetWindowRgn);
AKARI_IMPORT BOOL WINAPI SetWindowPos(HWND hwnd, HWND hwndInsertAfter, int x, int y, int dx, int dy, UINT fuFlags) AKARI_NAME(SetWindowPos);
AKARI_IMPORT BOOL WINAPI GetWindowRect(HWND hwnd, LPRECT prc) AKARI_NAME(GetWindowRect);
AKARI_IMPORT int WINAPI GetWindowTextLengthW(HWND hWnd) AKARI_NAME(GetWindowTextLengthW);
AKARI_IMPORT BOOL WINAPI GetClientRect(HWND hwnd, LPRECT prc) AKARI_NAME(GetClientRect);
AKARI_IMPORT BOOL WINAPI AdjustWindowRectEx(LPRECT prc, DWORD dwStyle, BOOL bMenu, DWORD dwExStyle) AKARI_NAME(AdjustWindowRectEx);
AKARI_IMPORT BOOL WINAPI ValidateRect(HWND hWnd , CONST RECT *lpRect) AKARI_NAME(ValidateRect);
AKARI_IMPORT BOOL WINAPI InvalidateRect(HWND hwnd, LPCRECT prc, BOOL fErase) AKARI_NAME(InvalidateRect);
AKARI_IMPORT BOOL WINAPI ValidateRgn(HWND hWnd, HRGN hRgn) AKARI_NAME(ValidateRgn);
AKARI_IMPORT BOOL WINAPI InvalidateRgn(HWND hWnd, HRGN hRgn, BOOL fErase) AKARI_NAME(InvalidateRgn);
AKARI_IMPORT HWND WINAPI GetWindow(HWND hwnd, UINT uCmd) AKARI_NAME(GetWindow);
AKARI_IMPORT BOOL WINAPI BringWindowToTop(HWND hWnd) AKARI_NAME(BringWindowToTop);
AKARI_IMPORT HDWP WINAPI BeginDeferWindowPos(int nNumWindows) AKARI_NAME(BeginDeferWindowPos);
AKARI_IMPORT HDWP WINAPI DeferWindowPos(HDWP hWinPosInfo, HWND hWnd, HWND hWndInsertAfter, int x, int y, int cx, int cy, UINT uFlags) AKARI_NAME(DeferWindowPos);
AKARI_IMPORT BOOL WINAPI EndDeferWindowPos(HDWP hWinPosInfo) AKARI_NAME(EndDeferWindowPos);
AKARI_IMPORT BOOL WINAPI SetProp(HWND hWnd, LPCWSTR lpString, HANDLE hData) AKARI_NAME(SetProp);
AKARI_IMPORT HANDLE WINAPI GetProp(HWND hWnd, LPCWSTR lpString) AKARI_NAME(GetProp);
AKARI_IMPORT HANDLE WINAPI RemoveProp(HWND hWnd, LPCWSTR lpString) AKARI_NAME(RemoveProp);
AKARI_IMPORT int WINAPI ScrollWindowEx(HWND hWnd, int dx, int dy, CONST RECT *prcScroll, CONST RECT *prcClip , HRGN hrgnUpdate, LPRECT prcUpdate, UINT flags) AKARI_NAME(ScrollWindowEx);
AKARI_IMPORT BOOL WINAPI ScrollDC(HDC hDC, int dx, int dy, CONST RECT *lprcScroll, CONST RECT *lprcClip , HRGN hrgnUpdate, LPRECT lprcUpdate) AKARI_NAME(ScrollDC);
AKARI_IMPORT BOOL WINAPI CheckMenuRadioItem(HMENU, UINT, UINT, UINT, UINT) AKARI_NAME(CheckMenuRadioItem);
AKARI_IMPORT HBITMAP WINAPI LoadBitmapW(HINSTANCE hInstance, LPCWSTR lpBitmapName) AKARI_NAME(LoadBitmapW);
AKARI_IMPORT HMENU WINAPI LoadMenuW(HINSTANCE hInstance, LPCWSTR lpMenuName) AKARI_NAME(LoadMenuW);
AKARI_IMPORT BOOL WINAPI DrawMenuBar(HWND hWnd) AKARI_NAME(DrawMenuBar);
AKARI_IMPORT HMENU WINAPI CreateMenu(VOID) AKARI_NAME(CreateMenu);
AKARI_IMPORT HMENU WINAPI CreatePopupMenu(VOID) AKARI_NAME(CreatePopupMenu);
AKARI_IMPORT BOOL WINAPI DestroyMenu(HMENU hMenu) AKARI_NAME(DestroyMenu);
AKARI_IMPORT DWORD WINAPI CheckMenuItem(HMENU hMenu, UINT uIDCheckItem, UINT uCheck) AKARI_NAME(CheckMenuItem);
AKARI_IMPORT BOOL WINAPI EnableMenuItem(HMENU hMenu, UINT uIDEnableItem, UINT uEnable) AKARI_NAME(EnableMenuItem);
AKARI_IMPORT HMENU WINAPI GetSubMenu(HMENU hMenu, int nPos) AKARI_NAME(GetSubMenu);
AKARI_IMPORT BOOL WINAPI InsertMenuW(HMENU hMenu, UINT uPosition, UINT uFlags, UINT uIDNewItem, LPCWSTR lpNewItem) AKARI_NAME(InsertMenuW);
AKARI_IMPORT BOOL WINAPI AppendMenuW(HMENU hMenu, UINT uFlags, UINT uIDNewItem, LPCWSTR lpNewItem) AKARI_NAME(AppendMenuW);
AKARI_IMPORT BOOL WINAPI RemoveMenu(HMENU hMenu, UINT uPosition, UINT uFlags) AKARI_NAME(RemoveMenu);
AKARI_IMPORT BOOL WINAPI DeleteMenu(HMENU hMenu, UINT uPosition, UINT uFlags) AKARI_NAME(DeleteMenu);
AKARI_IMPORT HACCEL WINAPI LoadAcceleratorsW(HINSTANCE hInstance, LPCWSTR lpTableName) AKARI_NAME(LoadAcceleratorsW);
AKARI_IMPORT BOOL WINAPI DestroyAcceleratorTable(HACCEL hAccel) AKARI_NAME(DestroyAcceleratorTable);
AKARI_IMPORT BOOL WINAPI SetSysColors(int cElements, CONST INT * lpaElements, CONST COLORREF * lpaRgbValues) AKARI_NAME(SetSysColors);
AKARI_IMPORT BOOL WINAPI SetRect(LPRECT lprc, int xLeft, int yTop, int xRight, int yBottom) AKARI_NAME(SetRect);
AKARI_IMPORT BOOL WINAPI SetRectEmpty(LPRECT lprc) AKARI_NAME(SetRectEmpty);
AKARI_IMPORT BOOL WINAPI CopyRect(LPRECT lprcDst, CONST RECT *lprcSrc) AKARI_NAME(CopyRect);
AKARI_IMPORT BOOL WINAPI InflateRect(LPRECT lprc, int dx, int dy) AKARI_NAME(InflateRect);
AKARI_IMPORT BOOL WINAPI IntersectRect(LPRECT lprcDst, CONST RECT *lprcSrc1, CONST RECT *lprcSrc2) AKARI_NAME(IntersectRect);
AKARI_IMPORT BOOL WINAPI UnionRect(LPRECT lprcDst, CONST RECT *lprcSrc1, CONST RECT *lprcSrc2) AKARI_NAME(UnionRect);
AKARI_IMPORT BOOL WINAPI OffsetRect(LPRECT lprc, int dx, int dy) AKARI_NAME(OffsetRect);
AKARI_IMPORT BOOL WINAPI IsRectEmpty(CONST RECT *lprc) AKARI_NAME(IsRectEmpty);
AKARI_IMPORT BOOL WINAPI EqualRect(CONST RECT *lprc1, CONST RECT *lprc2) AKARI_NAME(EqualRect);
AKARI_IMPORT BOOL WINAPI PtInRect(CONST RECT *lprc, POINT pt) AKARI_NAME(PtInRect);
AKARI_IMPORT BOOL WINAPI SubtractRect(LPRECT prcDst, CONST RECT *prcSrc1, CONST RECT *prcSrc2) AKARI_NAME(SubtractRect);
AKARI_IMPORT int WINAPI MapWindowPoints(HWND hWndFrom, HWND hWndTo, LPPOINT lpPoints, UINT cPoints) AKARI_NAME(MapWindowPoints);
AKARI_IMPORT HWND WINAPI WindowFromPoint(POINT Point) AKARI_NAME(WindowFromPoint);
AKARI_IMPORT HWND WINAPI ChildWindowFromPoint(HWND hWndParent, POINT Point) AKARI_NAME(ChildWindowFromPoint);
AKARI_IMPORT BOOL WINAPI ClientToScreen(HWND hWnd, LPPOINT lpPoint) AKARI_NAME(ClientToScreen);
AKARI_IMPORT BOOL WINAPI ScreenToClient(HWND hWnd, LPPOINT lpPoint) AKARI_NAME(ScreenToClient);
AKARI_IMPORT BOOL WINAPI SetWindowTextW(HWND hWnd, LPCWSTR lpString) AKARI_NAME(SetWindowTextW);
AKARI_IMPORT int WINAPI GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount) AKARI_NAME(GetWindowTextW);
AKARI_IMPORT HDC WINAPI BeginPaint(HWND hwnd, LPPAINTSTRUCT pps) AKARI_NAME(BeginPaint);
AKARI_IMPORT BOOL WINAPI EndPaint(HWND hwnd, LPPAINTSTRUCT pps) AKARI_NAME(EndPaint);
AKARI_IMPORT BOOL WINAPI GetUpdateRect(HWND hWnd, LPRECT lpRect, BOOL bErase) AKARI_NAME(GetUpdateRect);
AKARI_IMPORT int WINAPI GetUpdateRgn(HWND hWnd, HRGN hRgn, BOOL bErase) AKARI_NAME(GetUpdateRgn);
AKARI_IMPORT HDC WINAPI GetDCEx(HWND hWnd , HRGN hrgnClip, DWORD flags) AKARI_NAME(GetDCEx);
AKARI_IMPORT HWND WINAPI GetDesktopWindow(void) AKARI_NAME(GetDesktopWindow);
AKARI_IMPORT BOOL WINAPI IsWindow(HWND hWnd) AKARI_NAME(IsWindow);
AKARI_IMPORT BOOL WINAPI IsWindowVisible(HWND hWnd) AKARI_NAME(IsWindowVisible);
AKARI_IMPORT HWND WINAPI CreateWindowExW(DWORD dwExStyle, LPCWSTR lpClassName, LPCWSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent , HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam) AKARI_NAME(CreateWindowExW);
AKARI_IMPORT BOOL WINAPI DestroyWindow(HWND hwnd) AKARI_NAME(DestroyWindow);
AKARI_IMPORT LRESULT WINAPI CallWindowProcW(WNDPROC lpPrevWndFunc, HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(CallWindowProcW);
AKARI_IMPORT DWORD WINAPI GetWindowThreadProcessId(HWND hWnd, LPDWORD lpdwProcessId) AKARI_NAME(GetWindowThreadProcessId);
AKARI_IMPORT UINT WINAPI GetDoubleClickTime(VOID) AKARI_NAME(GetDoubleClickTime);
AKARI_IMPORT int WINAPI GetSystemMetrics(int nIndex) AKARI_NAME(GetSystemMetrics);
AKARI_IMPORT DWORD WINAPI GetClassLongW(HWND hWnd, int nIndex) AKARI_NAME(GetClassLongW);
AKARI_IMPORT DWORD WINAPI SetClassLongW(HWND hWnd, int nIndex, LONG dwNewLong) AKARI_NAME(SetClassLongW);
AKARI_IMPORT ATOM WINAPI RegisterClassW(CONST WNDCLASSW *lpWndClass) AKARI_NAME(RegisterClassW);
AKARI_IMPORT BOOL WINAPI UnregisterClassW(LPCWSTR lpClassName, HINSTANCE hInstance) AKARI_NAME(UnregisterClassW);
AKARI_IMPORT BOOL WINAPI GetClassInfoW(HINSTANCE hInstance, LPCWSTR lpClassName, LPWNDCLASSW lpWndClass) AKARI_NAME(GetClassInfoW);
AKARI_IMPORT BOOL WINAPI EnableWindow(HWND hWnd, BOOL bEnable) AKARI_NAME(EnableWindow);
AKARI_IMPORT BOOL WINAPI IsWindowEnabled(HWND hWnd) AKARI_NAME(IsWindowEnabled);
AKARI_IMPORT DWORD WINAPI GetSysColor(int nIndex) AKARI_NAME(GetSysColor);
AKARI_IMPORT HDC WINAPI GetDC(HWND hwnd) AKARI_NAME(GetDC);
AKARI_IMPORT HDC WINAPI GetWindowDC(HWND hwnd) AKARI_NAME(GetWindowDC);
AKARI_IMPORT int WINAPI ReleaseDC(HWND hwnd, HDC hdc) AKARI_NAME(ReleaseDC);
AKARI_IMPORT VOID WINAPI mouse_event(DWORD dwFlags, DWORD dx, DWORD dy, DWORD cButtons, DWORD dwExtraInfo) AKARI_NAME(mouse_event);
AKARI_IMPORT int WINAPI TranslateAcceleratorW(HWND hWnd, HACCEL hAccTable, LPMSG lpMsg) AKARI_NAME(TranslateAcceleratorW);
AKARI_IMPORT void WINAPI SystemIdleTimerReset(void) AKARI_NAME(SystemIdleTimerReset);
AKARI_IMPORT LRESULT WINAPI DefWindowProcW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(DefWindowProcW);
AKARI_IMPORT LONG WINAPI GetWindowLongW(HWND hWnd, int nIndex) AKARI_NAME(GetWindowLongW);
AKARI_IMPORT LONG WINAPI SetWindowLongW(HWND hWnd, int nIndex, LONG dwNewLong) AKARI_NAME(SetWindowLongW);
AKARI_IMPORT BOOL WINAPI IsChild(HWND hWndParent, HWND hWnd) AKARI_NAME(IsChild);
AKARI_IMPORT BOOL WINAPI ShowWindow(HWND hwnd, INT nCmdShow) AKARI_NAME(ShowWindow);
AKARI_IMPORT BOOL WINAPI UpdateWindow(HWND hwnd) AKARI_NAME(UpdateWindow);
AKARI_IMPORT BOOL WINAPI RedrawWindow(HWND hwnd, CONST RECT* lprcUpdate, HRGN hrgnUpdate, UINT flags) AKARI_NAME(RedrawWindow);
AKARI_IMPORT HWND WINAPI SetParent(HWND hwnd, HWND hwndParent) AKARI_NAME(SetParent);
AKARI_IMPORT HWND WINAPI GetParent(HWND hwnd) AKARI_NAME(GetParent);
AKARI_IMPORT HWND WINAPI FindWindowW(LPCWSTR lpClassName , LPCWSTR lpWindowName) AKARI_NAME(FindWindowW);
AKARI_IMPORT int WINAPI GetClassNameW(HWND hWnd, LPWSTR lpClassName, int nMaxCount) AKARI_NAME(GetClassNameW);
AKARI_IMPORT int WINAPI MessageBoxW(HWND hWnd , LPCWSTR lpText, LPCWSTR lpCaption, UINT uType) AKARI_NAME(MessageBoxW);
AKARI_IMPORT BOOL WINAPI MessageBeep(UINT uType) AKARI_NAME(MessageBeep);
AKARI_IMPORT BOOL WINAPI CreateCaret(HWND hWnd, HBITMAP hBitmap, int nWidth, int nHeight) AKARI_NAME(CreateCaret);
AKARI_IMPORT BOOL WINAPI DestroyCaret(VOID) AKARI_NAME(DestroyCaret);
AKARI_IMPORT BOOL WINAPI HideCaret(HWND hWnd) AKARI_NAME(HideCaret);
AKARI_IMPORT BOOL WINAPI ShowCaret(HWND hWnd) AKARI_NAME(ShowCaret);
AKARI_IMPORT BOOL WINAPI SetCaretPos(int X, int Y) AKARI_NAME(SetCaretPos);
AKARI_IMPORT BOOL WINAPI GetCaretPos(LPPOINT lpPoint) AKARI_NAME(GetCaretPos);
AKARI_IMPORT BOOL WINAPI SetCaretBlinkTime(UINT uMSeconds) AKARI_NAME(SetCaretBlinkTime);
AKARI_IMPORT UINT WINAPI GetCaretBlinkTime(VOID) AKARI_NAME(GetCaretBlinkTime);
AKARI_IMPORT HWND WINAPI SetActiveWindow(HWND hWnd) AKARI_NAME(SetActiveWindow);
AKARI_IMPORT HWND WINAPI GetForegroundWindow(VOID) AKARI_NAME(GetForegroundWindow);
AKARI_IMPORT BOOL WINAPI SetForegroundWindow(HWND hWnd) AKARI_NAME(SetForegroundWindow);
AKARI_IMPORT HWND WINAPI SetFocus(HWND hWnd) AKARI_NAME(SetFocus);
AKARI_IMPORT HWND WINAPI GetActiveWindow(VOID) AKARI_NAME(GetActiveWindow);
AKARI_IMPORT HWND WINAPI GetFocus(VOID) AKARI_NAME(GetFocus);
AKARI_IMPORT SHORT WINAPI GetAsyncKeyState(int vKey) AKARI_NAME(GetAsyncKeyState);
AKARI_IMPORT SHORT WINAPI GetKeyState(int nVirtKey) AKARI_NAME(GetKeyState);
AKARI_IMPORT VOID WINAPI keybd_event(BYTE bVk, BYTE bScan, DWORD dwFlags, DWORD dwExtraInfo) AKARI_NAME(keybd_event);
AKARI_IMPORT BOOL WINAPI PostKeybdMessage(HWND hwnd, UINT VKey, UINT KeyStateFlags, UINT cCharacters, UINT *pShiftStateBuffer, UINT *pCharacterBuffer) AKARI_NAME(PostKeybdMessage);
AKARI_IMPORT int WINAPI GetKeyboardType(int nTypeFlag) AKARI_NAME(GetKeyboardType);
AKARI_IMPORT BOOL WINAPI GetKeyboardLayoutNameW(LPWSTR pwszKLID) AKARI_NAME(GetKeyboardLayoutNameW);
AKARI_IMPORT UINT WINAPI MapVirtualKeyW(UINT uCode, UINT uMapType) AKARI_NAME(MapVirtualKeyW);
AKARI_IMPORT int WINAPI SetScrollPos(HWND hwnd, int fnBar, int nPos, BOOL bRedraw) AKARI_NAME(SetScrollPos);
AKARI_IMPORT BOOL WINAPI SetScrollRange(HWND hwnd, int fnBar, int nMinPos, int nMaxPos, BOOL bRedraw) AKARI_NAME(SetScrollRange);
AKARI_IMPORT BOOL WINAPI IsDialogMessageW(HWND hDlg, LPMSG lpMsg) AKARI_NAME(IsDialogMessageW);
AKARI_IMPORT BOOL WINAPI EndDialog(HWND hDlg, int nResult) AKARI_NAME(EndDialog);
AKARI_IMPORT HWND WINAPI GetNextDlgGroupItem(HWND hDlg, HWND hCtl, BOOL bPrevious) AKARI_NAME(GetNextDlgGroupItem);
AKARI_IMPORT HWND WINAPI GetNextDlgTabItem(HWND hDlg, HWND hCtl, BOOL bPrevious) AKARI_NAME(GetNextDlgTabItem);
AKARI_IMPORT int WINAPI GetDlgCtrlID(HWND hWnd) AKARI_NAME(GetDlgCtrlID);
AKARI_IMPORT long WINAPI GetDialogBaseUnits(VOID) AKARI_NAME(GetDialogBaseUnits);
AKARI_IMPORT BOOL WINAPI MapDialogRect(HWND hwnd, LPRECT prc) AKARI_NAME(MapDialogRect);
AKARI_IMPORT HWND WINAPI GetDlgItem(HWND hDlg, int iCtrlID) AKARI_NAME(GetDlgItem);
AKARI_IMPORT LRESULT WINAPI DefDlgProcW(HWND hDlg, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(DefDlgProcW);
AKARI_IMPORT BOOL WINAPI SetDlgItemInt(HWND hDlg, int nIDDlgItem, UINT uValue, BOOL bSigned) AKARI_NAME(SetDlgItemInt);
AKARI_IMPORT UINT WINAPI GetDlgItemInt(HWND hDlg, int nIDDlgItem, BOOL *lpTranslated, BOOL bSigned) AKARI_NAME(GetDlgItemInt);
AKARI_IMPORT BOOL WINAPI CheckRadioButton(HWND hDlg, int nIDFirstButton, int nIDLastButton, int nIDCheckButton) AKARI_NAME(CheckRadioButton);
AKARI_IMPORT LONG WINAPI SendDlgItemMessageW(HWND hDlg, int nIDDlgItem, UINT Msg, WPARAM wParam, LPARAM lParam) AKARI_NAME(SendDlgItemMessageW);
AKARI_IMPORT BOOL WINAPI SetDlgItemTextW(HWND hDlg, int nIDDlgItem, LPCWSTR lpString) AKARI_NAME(SetDlgItemTextW);
AKARI_IMPORT UINT WINAPI GetDlgItemTextW(HWND hDlg, int nIDDlgItem, LPWSTR lpString, int nMaxCount) AKARI_NAME(GetDlgItemTextW);
AKARI_IMPORT BOOL WINAPI OpenClipboard(HWND hWndNewOwner) AKARI_NAME(OpenClipboard);
AKARI_IMPORT BOOL WINAPI CloseClipboard(VOID) AKARI_NAME(CloseClipboard);
AKARI_IMPORT HWND WINAPI GetClipboardOwner(VOID) AKARI_NAME(GetClipboardOwner);
AKARI_IMPORT HANDLE WINAPI SetClipboardData(UINT uFormat, HANDLE hMem) AKARI_NAME(SetClipboardData);
AKARI_IMPORT HANDLE WINAPI GetClipboardData(UINT uFormat) AKARI_NAME(GetClipboardData);
AKARI_IMPORT HANDLE WINAPI GetClipboardDataAlloc(UINT uFormat) AKARI_NAME(GetClipboardDataAlloc);
AKARI_IMPORT UINT WINAPI RegisterClipboardFormatW(LPCWSTR lpszFormat) AKARI_NAME(RegisterClipboardFormatW);
AKARI_IMPORT int WINAPI CountClipboardFormats(VOID) AKARI_NAME(CountClipboardFormats);
AKARI_IMPORT UINT WINAPI EnumClipboardFormats(UINT format) AKARI_NAME(EnumClipboardFormats);
AKARI_IMPORT int WINAPI GetClipboardFormatNameW(UINT format, LPWSTR lpszFormatName, int cchMaxCount) AKARI_NAME(GetClipboardFormatNameW);
AKARI_IMPORT BOOL WINAPI EmptyClipboard(VOID) AKARI_NAME(EmptyClipboard);
AKARI_IMPORT BOOL WINAPI IsClipboardFormatAvailable(UINT format) AKARI_NAME(IsClipboardFormatAvailable);
AKARI_IMPORT int WINAPI GetPriorityClipboardFormat(UINT *paFormatPriorityList, int cFormats) AKARI_NAME(GetPriorityClipboardFormat);
AKARI_IMPORT HWND WINAPI GetOpenClipboardWindow(VOID) AKARI_NAME(GetOpenClipboardWindow);
AKARI_IMPORT HCURSOR WINAPI LoadCursorW(HINSTANCE hInstance, LPCWSTR lpCursorName) AKARI_NAME(LoadCursorW);
AKARI_IMPORT int WINAPI ShowCursor(BOOL bShow) AKARI_NAME(ShowCursor);
AKARI_IMPORT BOOL WINAPI SetCursorPos(int X, int Y) AKARI_NAME(SetCursorPos);
AKARI_IMPORT HCURSOR WINAPI SetCursor(HCURSOR hCursor) AKARI_NAME(SetCursor);
AKARI_IMPORT BOOL WINAPI GetCursorPos(LPPOINT lpPoint) AKARI_NAME(GetCursorPos);
AKARI_IMPORT BOOL WINAPI ClipCursor(CONST RECT *lpRect) AKARI_NAME(ClipCursor);
AKARI_IMPORT BOOL WINAPI GetClipCursor(LPRECT lpRect) AKARI_NAME(GetClipCursor);
AKARI_IMPORT HCURSOR WINAPI GetCursor(VOID) AKARI_NAME(GetCursor);
AKARI_IMPORT HCURSOR WINAPI LoadAnimatedCursor(HINSTANCE hInstance, DWORD ResourceId, int cFrames, int FrameTimeInterval) AKARI_NAME(LoadAnimatedCursor);
AKARI_IMPORT UINT WINAPI SetTimer(HWND hwnd, UINT idTimer, UINT uTimeOut, TIMERPROC pfnTimerProc) AKARI_NAME(SetTimer);
AKARI_IMPORT BOOL WINAPI KillTimer(HWND hwnd, UINT idEvent) AKARI_NAME(KillTimer);
AKARI_IMPORT DWORD WINAPI GetKeyboardStatus(VOID) AKARI_NAME(GetKeyboardStatus);
AKARI_IMPORT BOOL WINAPI EnableHardwareKeyboard(BOOL fEnable) AKARI_NAME(EnableHardwareKeyboard);
AKARI_IMPORT BOOL WINAPI RegisterHotKey(HWND hWnd, int id, UINT fsModifiers, UINT vk) AKARI_NAME(RegisterHotKey);
AKARI_IMPORT BOOL WINAPI UnregisterHotKey(HWND hWnd, int id) AKARI_NAME(UnregisterHotKey);
AKARI_IMPORT BOOL WINAPI AllKeys(BOOL bAllKeys) AKARI_NAME(AllKeys);
AKARI_IMPORT BOOL WINAPI SystemParametersInfoW(UINT uiAction, UINT uiParam, PVOID pvParam, UINT fWinIni) AKARI_NAME(SystemParametersInfoW);
AKARI_IMPORT void WINAPI AccessibilitySoundSentryEvent(void) AKARI_NAME(AccessibilitySoundSentryEvent);
AKARI_IMPORT HICON WINAPI LoadIconW(HINSTANCE hInstance, LPCWSTR lpIconName) AKARI_NAME(LoadIconW);
AKARI_IMPORT BOOL WINAPI DestroyIcon(HICON hIcon) AKARI_NAME(DestroyIcon);
AKARI_IMPORT BOOL WINAPI DrawIconEx(HDC hdc, int xLeft, int yTop, HICON hIcon, int cxWidth, int cyWidth, UINT istepIfAniCur, HBRUSH hbrFlickerFreeDraw, UINT diFlags) AKARI_NAME(DrawIconEx);
AKARI_IMPORT HANDLE WINAPI LoadImageW(HINSTANCE, LPCWSTR, UINT, int, int, UINT) AKARI_NAME(LoadImageW);
AKARI_IMPORT HCURSOR WINAPI CreateCursor(HINSTANCE hInst, int xHotSpot, int yHotSpot, int nWidth, int nHeight, CONST VOID *pvANDPlane, CONST VOID *pvXORPlane) AKARI_NAME(CreateCursor);
AKARI_IMPORT BOOL WINAPI DestroyCursor(HCURSOR hCursor) AKARI_NAME(DestroyCursor);

#define AppendMenu AppendMenuW
#define CallWindowProc CallWindowProcW
#define CreateWindowEx CreateWindowExW
#define DefDlgProc DefDlgProcW
#define DefWindowProc DefWindowProcW
#define DispatchMessage DispatchMessageW
#define FindWindow FindWindowW
#define GetClassInfo GetClassInfoW
#define GetClassName GetClassNameW
#define GetClipboardFormatName GetClipboardFormatNameW
#define GetDlgItemText GetDlgItemTextW
#define GetKeyboardLayoutName GetKeyboardLayoutNameW
#define GetMessage GetMessageW
#define GetWindowLong GetWindowLongW
#define GetWindowTextLength GetWindowTextLengthW
#define GetWindowText GetWindowTextW
#define InsertMenu InsertMenuW
#define IsDialogMessage IsDialogMessageW
#define LoadAccelerators LoadAcceleratorsW
#define LoadBitmap LoadBitmapW
#define LoadCursor LoadCursorW
#define LoadIcon LoadIconW
#define LoadImage LoadImageW
#define LoadMenu LoadMenuW
#define MapVirtualKey MapVirtualKeyW
#define MessageBox MessageBoxW
#define PeekMessage PeekMessageW
#define PostMessage PostMessageW
#define PostThreadMessage PostThreadMessageW
#define RegisterClass RegisterClassW
#define RegisterClipboardFormat RegisterClipboardFormatW
#define RegisterWindowMessage RegisterWindowMessageW
#define SendDlgItemMessage SendDlgItemMessageW
#define SendMessage SendMessageW
#define SendNotifyMessage SendNotifyMessageW
#define SetDlgItemText SetDlgItemTextW
#define SetWindowLong SetWindowLongW
#define SetWindowText SetWindowTextW
#define SystemParametersInfo SystemParametersInfoW
#define TranslateAccelerator TranslateAcceleratorW
#define UnregisterClass UnregisterClassW

#ifdef __cplusplus
}
#endif
#endif
