#!/usr/bin/env python3
"""def-gap.py -- which documented link libraries have no import-lib .def.

Every `-doc.def` in this tree is an import library for one documented CE
module.  The set of modules is not a matter of opinion: it is the set of
distinct `Library:` / `Link Library:` values printed by the Requirements block
of the harvested corpus.  A documented library with no .def is a module this
SDK cannot link against, and no existing audit reports it -- `defcheck` only
validates the defs that exist, so an absent one is invisible.

Usage:
    tools/def-gap.py [--corpus DIR] [--md docs/def-gap.md]
"""
import argparse
import collections
import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import importlib.util


def _load(name):
    spec = importlib.util.spec_from_file_location(
        name, os.path.join(HERE, name.replace("-", "_") + ".py")
        if os.path.exists(os.path.join(HERE, name.replace("-", "_") + ".py"))
        else os.path.join(HERE, name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


dc = _load("declare-from-corpus")

# Libraries that are static archives or link-time-only inputs in Windows CE.
# A .def describes the export table of a DLL; these have none, so generating
# `LIBRARY <name>.dll` for them would describe a module that does not exist.
NOT_A_DLL = {
    "nk.lib", "nkmain.lib", "nkstub.lib", "oemmain.lib", "coremain.lib",
    "corelibc.lib", "kitl.lib", "ddvdids.lib", "dmamdd.lib", "pcireg.lib",
    "gdcfg.lib", "sdhclib.lib", "ndislib.lib", "hidparse_lib.lib",
    "gpe_lib.lib", "layoutmanager.lib", "device.lib", "lfapi.lib",
    "touchgesture.lib", "dwconn.lib", "dwdmptxt.lib",
}
# GUID-only libraries: their pages print IIDs, not functions.  The tree's
# standing rule is never to generate a def for a GUID-only library.
GUID_ONLY = {"uuid.lib", "dmoguid.lib", "dmoguids.lib"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default=os.environ.get(
        "WINCE_CORPUS", "/home/user/wince-docs-corpus"))
    ap.add_argument("--md", default="docs/def-gap.md")
    a = ap.parse_args()

    libs = collections.Counter()
    for d in sorted(os.listdir(a.corpus)):
        p = os.path.join(a.corpus, d)
        if not os.path.isdir(p) or d in ("catalogs", ".git"):
            continue
        for f in os.listdir(p):
            if not f.endswith(".html"):
                continue
            raw = open(os.path.join(p, f), encoding="utf-8",
                       errors="replace").read()
            _, lib = dc.requirements(raw)
            if not lib:
                continue
            for one in re.split(r"[,;]| and ", lib):
                one = one.strip().strip(".").lower()
                if one.endswith(".lib"):
                    libs[one] += 1

    shipped, ndefs = set(), 0
    for f in os.listdir(os.path.join(ROOT, "def")):
        if f.endswith(".def"):
            ndefs += 1
            base = f[:-4]
            # a def is named either <lib>.def or <lib>-doc.def
            shipped.add(re.sub(r"-doc$", "", base).lower() + ".lib")
            shipped.add(base.lower() + ".lib")

    missing = sorted(l for l in libs if l not in shipped)
    dll = [l for l in missing if l not in NOT_A_DLL and l not in GUID_ONLY]
    static = [l for l in missing if l in NOT_A_DLL]
    guid = [l for l in missing if l in GUID_ONLY]

    md = a.md if os.path.isabs(a.md) else os.path.join(ROOT, a.md)
    L = ["# Link libraries documented by the corpus that have no .def",
         "",
         "Generated by `python3 tools/def-gap.py`. Do not edit by hand.",
         "",
         "Distinct `Library:` / `Link Library:` values in the harvested corpus:",
         "**%d**. Import libraries shipped: **%d** (.def files in `def/`)." % (
            len(libs), ndefs),
         "",
         "## Documented libraries with no .def, by kind",
         "",
         "| kind | count | meaning |",
         "| --- | --- | --- |",
         "| DLL-backed, no .def | %d | this SDK cannot link these modules |"
         % len(dll),
         "| static archive | %d | no export table, so no .def is correct |"
         % len(static),
         "| GUID-only | %d | pages print IIDs, not functions; a def would be "
         "wrong |" % len(guid),
         "",
         "## DLL-backed libraries with no .def",
         "",
         "| library | pages citing it |",
         "| --- | --- |"]
    for l in dll:
        L.append("| `%s` | %d |" % (l, libs[l]))
    L += ["", "## Excluded, with the reason", "",
          "| library | pages | why no .def |", "| --- | --- | --- |"]
    for l in static:
        L.append("| `%s` | %d | static archive in Windows CE |" % (l, libs[l]))
    for l in guid:
        L.append("| `%s` | %d | GUID-only; pages print IIDs |" % (l, libs[l]))
    open(md, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("documented libraries: %d ; .def files shipped: %d" % (len(libs), ndefs))
    print("no .def: %d  (DLL-backed %d, static %d, GUID-only %d)"
          % (len(missing), len(dll), len(static), len(guid)))
    for l in dll:
        print("  %-26s %4d pages" % (l, libs[l]))
    print("wrote %s" % md, file=sys.stderr)


if __name__ == "__main__":
    main()
