#!/usr/bin/env python3
"""Generate the initial clean-room Windows CE API surface from JSON facts."""
import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
INPUT = ROOT / "data" / "apis" / "gettickcount.json"
OUTPUTS = {
    ROOT / "generated" / "include" / "winbase.h": "header",
    ROOT / "generated" / "link" / "gettickcount.link.json": "link",
}


def load_record():
    record = json.loads(INPUT.read_text(encoding="utf-8"))
    required = {"name", "header", "prototype", "types", "availability", "link_library", "unknowns", "corpus"}
    missing = required - record.keys()
    if record.get("schema_version") != 1 or missing:
        raise ValueError(f"unsupported or incomplete source record (missing: {', '.join(sorted(missing))})")
    if record["prototype"] != {"return_type": "DWORD", "parameters": []}:
        raise ValueError("unsupported GetTickCount prototype")
    if record["types"].get("DWORD", {}).get("width_bits") != 32:
        raise ValueError("DWORD must be a 32-bit type")
    return record


def render_header(record):
    corpus = record["corpus"]
    return "\n".join((
        "/* Generated by tools/generate_surface.py; do not edit. */",
        "/* Clean-room declaration derived from public interface facts. */",
        f"/* Evidence: {corpus['repository']}@{corpus['commit']}:{corpus['record']} */",
        "#ifndef AKARI_WINBASE_H",
        "#define AKARI_WINBASE_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef uint32_t DWORD;",
        "",
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif",
        "",
        "DWORD GetTickCount(void);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* AKARI_WINBASE_H */",
        "",
    ))


def render_link(record):
    return json.dumps({
        "schema_version": 1,
        "api": record["name"],
        "availability": record["availability"],
        "link_library": record["link_library"],
        "dll_module": None,
        "export_name": None,
        "ordinal": None,
        "unknowns": record["unknowns"],
        "corpus": record["corpus"],
    }, indent=2, sort_keys=True) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    record = load_record()
    rendered = {
        ROOT / "generated" / "include" / "winbase.h": render_header(record),
        ROOT / "generated" / "link" / "gettickcount.link.json": render_link(record),
    }
    stale = []
    for path, content in rendered.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("stale generated files: " + ", ".join(map(str, stale)), file=sys.stderr)
        return 1
    print(f"[generate-surface] {'checked' if args.check else 'generated'} {len(rendered)} file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
