#!/usr/bin/env python3
"""Generate clean-room Windows CE declarations from local fact records."""
import argparse, json, pathlib, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
INPUT = ROOT / "data/apis/winbase.json"

def load():
    r = json.loads(INPUT.read_text())
    if r.get("schema_version") != 1 or r.get("header") != "winbase.h" or not r.get("apis"):
        raise ValueError("unsupported or incomplete winbase source record")
    if r["types"].get("DWORD", {}).get("width_bits") != 32: raise ValueError("DWORD must be 32-bit")
    for a in r["apis"]:
        if not {"name","return_type","parameters","availability","link_library","corpus_record"} <= a.keys(): raise ValueError("incomplete API record")
        if a["link_library"] != "Coredll.lib": raise ValueError("unexpected linker requirement")
    return r

def declaration(a):
    p = ", ".join(x["type"] + " " + x["name"] for x in a["parameters"]) or "void"
    return f'{a["return_type"]} {a["name"]}({p});'

def header(r):
    e=r["corpus"]; lines=["/* Generated by tools/generate_surface.py; do not edit. */","/* Clean-room declarations derived from public interface facts. */",f'/* Evidence: {e["repository"]}@{e["commit"]}; records: ' + ", ".join(a["corpus_record"] for a in r["apis"])+" */","#ifndef AKARI_WINBASE_H","#define AKARI_WINBASE_H","","#include <stdint.h>","","typedef uint32_t DWORD;","","#ifdef __cplusplus","extern \"C\" {","#endif",""]
    lines += [declaration(a) for a in r["apis"]]
    return "\n".join(lines+["","#ifdef __cplusplus","}","#endif","","#endif /* AKARI_WINBASE_H */",""])
def link(r):
    return json.dumps({"schema_version":1,"header":r["header"],"apis":[{"name":a["name"],"availability":a["availability"],"link_library":a["link_library"]} for a in r["apis"]],"dll_module":None,"export_name":None,"ordinal":None,"unknowns":r["unknowns"],"corpus":r["corpus"]},indent=2,sort_keys=True)+"\n"
def main():
    c=argparse.ArgumentParser(); c.add_argument("--check",action="store_true"); a=c.parse_args(); r=load(); files={ROOT/"generated/include/winbase.h":header(r),ROOT/"generated/link/winbase.link.json":link(r)}; stale=[]
    for p,s in files.items():
        if a.check:
            if not p.is_file() or p.read_text()!=s: stale.append(str(p.relative_to(ROOT)))
        else: p.parent.mkdir(parents=True,exist_ok=True); p.write_text(s)
    if stale: print("stale generated files: "+", ".join(stale),file=sys.stderr); return 1
    print(f"[generate-surface] {'checked' if a.check else 'generated'} {len(files)} file(s)")
if __name__ == "__main__": sys.exit(main() or 0)
